import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

interface ExportRequest {
  projectId: string;
  format: 'html' | 'react' | 'nextjs' | 'vue' | 'static';
}

function generateReactExport(html: string, css: string, projectName: string): string {
  // Extract the body content from the HTML
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/);
  const bodyContent = bodyMatch ? bodyMatch[1].trim() : html;

  // Clean up the body content for React (remove script/style tags, convert class to className)
  let reactContent = bodyContent
    .replace(/class=/g, 'className=')
    .replace(/<script[^>]*>[\s\S]*?<\/script>/g, '')
    .replace(/<style[^>]*>[\s\S]*?<\/style>/g, '');

  const component = `import React from 'react';
import './${projectName.replace(/\s+/g, '-').toLowerCase()}.css';

export default function ${projectName.replace(/\s+/g, '').replace(/[^a-zA-Z0-9]/g, '')}Page() {
  return (
    <div className="page-container">
      ${reactContent}
    </div>
  );
}
`;

  const cssFile = css || `/* Extracted styles for ${projectName} */\n`;

  return JSON.stringify({
    files: [
      { name: `${projectName.replace(/\s+/g, '').replace(/[^a-zA-Z0-9]/g, '')}Page.tsx`, content: component },
      { name: `${projectName.replace(/\s+/g, '-').toLowerCase()}.css`, content: cssFile },
    ],
    format: 'react',
  });
}

function generateNextJsExport(html: string, css: string, projectName: string): string {
  // Extract the body content from the HTML
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/);
  const bodyContent = bodyMatch ? bodyMatch[1].trim() : html;

  // Clean up for React/Next.js
  let reactContent = bodyContent
    .replace(/class=/g, 'className=')
    .replace(/<script[^>]*>[\s\S]*?<\/script>/g, '')
    .replace(/<style[^>]*>[\s\S]*?<\/style>/g, '');

  // If there's JavaScript, extract it
  const scriptMatches = html.match(/<script[^>]*>([\s\S]*?)<\/script>/g);
  let jsContent = '';
  if (scriptMatches) {
    for (const scriptTag of scriptMatches) {
      if (!scriptTag.match(/<script[^>]*src=/)) {
        const contentMatch = scriptTag.match(/<script[^>]*>([\s\S]*?)<\/script>/);
        if (contentMatch) {
          jsContent += contentMatch[1] + '\n';
        }
      }
    }
  }

  const componentName = projectName.replace(/\s+/g, '').replace(/[^a-zA-Z0-9]/g, '') || 'Home';

  const pageFile = `import { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by Forge AI',
};

export default function Page() {
  return (
    <main className="page-container">
      ${reactContent}
    </main>
  );
}
`;

  const cssFile = css || `/* Extracted styles */\n`;
  const jsFile = jsContent ? `'use client';

${jsContent}` : '';

  const layoutFile = `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by Forge AI Website Builder',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;

  const files = [
    { name: 'app/page.tsx', content: pageFile },
    { name: 'app/layout.tsx', content: layoutFile },
    { name: 'app/globals.css', content: cssFile },
  ];

  if (jsFile) {
    files.push({ name: 'app/script.ts', content: jsFile });
  }

  return JSON.stringify({
    files,
    format: 'nextjs',
  });
}

function generateVueExport(html: string, css: string, projectName: string): string {
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/);
  const bodyContent = bodyMatch ? bodyMatch[1].trim() : html;

  let vueContent = bodyContent
    .replace(/class=/g, 'class=');

  const scriptMatches = html.match(/<script[^>]*>([\s\S]*?)<\/script>/g);
  let jsContent = '';
  if (scriptMatches) {
    for (const scriptTag of scriptMatches) {
      if (!scriptTag.match(/<script[^>]*src=/)) {
        const contentMatch = scriptTag.match(/<script[^>]*>([\s\S]*?)<\/script>/);
        if (contentMatch) {
          jsContent += contentMatch[1] + '\n';
        }
      }
    }
  }

  const component = `<template>
  <div class="page-container">
    ${vueContent}
  </div>
</template>

<script>
export default {
  name: '${projectName.replace(/\s+/g, '').replace(/[^a-zA-Z0-9]/g, '') || 'Home'}',
  mounted() {
    ${jsContent}
  }
}
</script>

<style scoped>
${css || '/* Extracted styles */'}
</style>
`;

  return JSON.stringify({
    files: [
      { name: `${projectName.replace(/\s+/g, '').replace(/[^a-zA-Z0-9]/g, '') || 'Home'}.vue`, content: component },
    ],
    format: 'vue',
  });
}

function generateStaticExport(html: string): string {
  // For static format, just return the full HTML as-is
  // It's already a self-contained document
  return JSON.stringify({
    files: [
      { name: 'index.html', content: html },
    ],
    format: 'static',
  });
}

export async function POST(request: NextRequest) {
  try {
    const body: ExportRequest = await request.json();
    const { projectId, format } = body;

    if (!projectId) {
      return NextResponse.json(
        { error: 'projectId is required' },
        { status: 400 }
      );
    }

    const validFormats = ['html', 'react', 'nextjs', 'vue', 'static'];
    if (!format || !validFormats.includes(format)) {
      return NextResponse.json(
        { error: `format must be one of: ${validFormats.join(', ')}` },
        { status: 400 }
      );
    }

    // Get project with pages
    const project = await db.project.findUnique({
      where: { id: projectId },
      include: { pages: true },
    });

    if (!project) {
      return NextResponse.json(
        { error: 'Project not found' },
        { status: 404 }
      );
    }

    // Get the main page (home page)
    const homePage = project.pages.find(p => p.route === '/') || project.pages[0];

    if (!homePage) {
      return NextResponse.json(
        { error: 'No pages found in project' },
        { status: 404 }
      );
    }

    const fullHtml = homePage.html;
    const css = homePage.css;
    const projectName = project.name;

    let exportResult: string;

    switch (format) {
      case 'html':
        // Return raw HTML directly
        exportResult = fullHtml;
        break;

      case 'react':
        exportResult = generateReactExport(fullHtml, css, projectName);
        break;

      case 'nextjs':
        exportResult = generateNextJsExport(fullHtml, css, projectName);
        break;

      case 'vue':
        exportResult = generateVueExport(fullHtml, css, projectName);
        break;

      case 'static':
        exportResult = generateStaticExport(fullHtml);
        break;

      default:
        return NextResponse.json(
          { error: 'Unsupported format' },
          { status: 400 }
        );
    }

    return NextResponse.json({
      export: exportResult,
      format,
      projectName,
      totalPages: project.pages.length,
    });
  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json(
      { error: 'Internal server error during export' },
      { status: 500 }
    );
  }
}
