// ─── Theme Palette System — 150+ diverse, beautiful palettes ────────────────
// Includes Persian themes, varied layouts, and stunning color combinations

export interface ThemePalette {
  id: string
  name: string
  nameFa?: string
  category: string
  description: string
  descriptionFa?: string
  colors: {
    primary: string
    accent: string
    background: string
    surface: string
    text: string
    muted: string
  }
  layoutStyle: string
  thumbnailGradient: string
  fontSuggestion: string
  mood: string
}

// ─── Persian / Iranian ──────────────────────────────────────────────────────

const PERSIAN_PALETTES: ThemePalette[] = [
  {
    id: 'persian-carpet',
    name: 'Persian Carpet',
    nameFa: 'فرش ایرانی',
    category: 'Persian',
    description: 'Rich, ornate palette inspired by traditional Persian rug patterns',
    descriptionFa: 'پالت غنی و تزئینی الهام‌گرفته از طرح‌های فرش ایرانی',
    colors: { primary: '#C9A06B', accent: '#8B4513', background: '#2D1B0E', surface: '#3D2B1F', text: '#F5E9DA', muted: '#9C8B78' },
    layoutStyle: 'mosaic/tessellated grid',
    thumbnailGradient: 'linear-gradient(135deg, #2D1B0E 0%, #C9A06B 40%, #8B4513 70%, #F5E9DA 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'ornate, woven, heritage, warm depth',
  },
  {
    id: 'isfahan-blue',
    name: 'Isfahan Blue',
    nameFa: 'آبی اصفهان',
    category: 'Persian',
    description: 'Iconic turquoise-blue of Isfahan\'s mosques and tilework',
    descriptionFa: 'آبی فیروزه‌ای نمادین مسجدها و کاشیکاری اصفهان',
    colors: { primary: '#1A8FCA', accent: '#F5D76E', background: '#0A1628', surface: '#1A2540', text: '#F0E6D3', muted: '#7A8B9C' },
    layoutStyle: 'radial/circular arrangement',
    thumbnailGradient: 'linear-gradient(180deg, #0A1628 0%, #1A8FCA 35%, #F5D76E 60%, #F0E6D3 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'spiritual, majestic, celestial blue',
  },
  {
    id: 'bazaar-gold',
    name: 'Bazaar Gold',
    nameFa: 'طلای بازار',
    category: 'Persian',
    description: 'Warm gold and spice tones of a bustling Persian bazaar',
    descriptionFa: 'تن‌های طلایی و ادویه‌ای بازار شلوغ ایرانی',
    colors: { primary: '#D4A843', accent: '#E8531E', background: '#1A130A', surface: '#2A2018', text: '#F5EDD8', muted: '#8A7D6A' },
    layoutStyle: 'horizontal scroll gallery',
    thumbnailGradient: 'linear-gradient(45deg, #1A130A 0%, #D4A843 30%, #E8531E 65%, #F5EDD8 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'bustling, aromatic, golden warmth',
  },
  {
    id: 'calligraphy-night',
    name: 'Calligraphy Night',
    nameFa: 'شب خطاطی',
    category: 'Persian',
    description: 'Dark backdrop with flowing white calligraphic strokes',
    descriptionFa: 'پشت‌صحنه تاریک با خطوط سفید خوشنویسی جاری',
    colors: { primary: '#FFFFFF', accent: '#C9A06B', background: '#0A0A12', surface: '#141425', text: '#E8E0D5', muted: '#6A6A80' },
    layoutStyle: 'centered editorial with large typography',
    thumbnailGradient: 'linear-gradient(160deg, #0A0A12 0%, #141425 25%, #C9A06B 50%, #FFFFFF 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'artistic, flowing, ink on night',
  },
  {
    id: 'pomegranate',
    name: 'Pomegranate',
    nameFa: 'انار',
    category: 'Persian',
    description: 'Deep ruby red of pomegranate seeds with warm green accents',
    descriptionFa: 'سرخ عمیق دانه‌های انار با تاکیدهای سبز گرم',
    colors: { primary: '#C41E3A', accent: '#4A7C4F', background: '#1A0A10', surface: '#2A1518', text: '#F5E8E0', muted: '#8A6A6A' },
    layoutStyle: 'split-screen hero (image left, text right)',
    thumbnailGradient: 'linear-gradient(120deg, #1A0A10 0%, #C41E3A 35%, #4A7C4F 65%, #F5E8E0 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'luscious, seeded abundance, festive',
  },
  {
    id: 'saffron',
    name: 'Saffron',
    nameFa: 'زعفران',
    category: 'Persian',
    description: 'The golden-orange of precious saffron threads on cream',
    descriptionFa: 'طلایی-نارنجی رشته‌های زعفران گرانبها روی خامه',
    colors: { primary: '#E3A830', accent: '#B87333', background: '#FAF6F0', surface: '#FFFFFF', text: '#2D1B0E', muted: '#7A6A5A' },
    layoutStyle: 'minimal centered with generous whitespace',
    thumbnailGradient: 'linear-gradient(90deg, #FAF6F0 0%, #E3A830 40%, #B87333 70%, #2D1B0E 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'precious, aromatic, sun-kissed',
  },
  {
    id: 'turquoise-mosque',
    name: 'Turquoise Mosque',
    nameFa: 'فیروزه مسجد',
    category: 'Persian',
    description: 'Cool turquoise and warm terracotta of Persian mosque interiors',
    descriptionFa: 'فیروزه خنک و گل‌خشک گرم داخل مسجد ایرانی',
    colors: { primary: '#40B5AD', accent: '#CC5500', background: '#F0EBE0', surface: '#FFFFFF', text: '#1A1A2E', muted: '#6A7A80' },
    layoutStyle: 'overlay cards on full-bleed image',
    thumbnailGradient: 'linear-gradient(200deg, #F0EBE0 0%, #40B5AD 35%, #CC5500 70%, #1A1A2E 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'spiritual, tiled, serene yet vivid',
  },
  {
    id: 'desert-rose',
    name: 'Desert Rose',
    nameFa: 'گل رز صحرا',
    category: 'Persian',
    description: 'Soft pink and sand tones of the Iranian desert at dawn',
    descriptionFa: 'تن‌های ملایم گل‌رز و ماسه صحرای ایران در سپیده‌دم',
    colors: { primary: '#D4A5A5', accent: '#C9A06B', background: '#F5EDE5', surface: '#FFFFFF', text: '#3C2415', muted: '#8A7A6A' },
    layoutStyle: 'floating cards over gradient background',
    thumbnailGradient: 'linear-gradient(135deg, #F5EDE5 0%, #D4A5A5 30%, #C9A06B 60%, #3C2415 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'dawn, dusted pink, ethereal calm',
  },
  {
    id: 'shiraz-wine',
    name: 'Shiraz Wine',
    nameFa: 'شراب شیراز',
    category: 'Persian',
    description: 'Deep burgundy of Shiraz wine with gold and dark accents',
    descriptionFa: 'بورگاندی عمیق شراب شیراز با تاکیدهای طلایی و تاریک',
    colors: { primary: '#722F37', accent: '#D4A843', background: '#0E0A08', surface: '#1A1510', text: '#F5E8DA', muted: '#7A6A58' },
    layoutStyle: 'asymmetric masonry layout',
    thumbnailGradient: 'linear-gradient(150deg, #0E0A08 0%, #722F37 30%, #D4A843 60%, #F5E8DA 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'velvet, cellar, rich and deep',
  },
  {
    id: 'persepolis',
    name: 'Persepolis',
    nameFa: 'پارسه (پرسبولیس)',
    category: 'Persian',
    description: 'Stone columns and golden reliefs of the ancient palace',
    descriptionFa: 'ستون‌های سنگی و نقش‌برجسته‌های طلایی کاخ باستانی',
    colors: { primary: '#C9B896', accent: '#D4A843', background: '#E8DCC8', surface: '#F5EDD8', text: '#2D1B0E', muted: '#8A7A5A' },
    layoutStyle: 'vertical stack with alternating backgrounds',
    thumbnailGradient: 'linear-gradient(180deg, #E8DCC8 0%, #C9B896 30%, #D4A843 55%, #2D1B0E 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'ancient, monumental, stone and gold',
  },
  {
    id: 'parsa-marble',
    name: 'Parsa Marble',
    nameFa: 'مرمر پارسه',
    category: 'Persian',
    description: 'Cool white marble veined with grey and gold',
    descriptionFa: 'مرمر سفید خنک با رگه‌های خاکستری و طلایی',
    colors: { primary: '#E8E0D5', accent: '#C9A06B', background: '#F5F0E8', surface: '#FFFFFF', text: '#2D2418', muted: '#8A8070' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(45deg, #F5F0E8 0%, #E8E0D5 25%, #C9A06B 50%, #2D2418 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'polished, veined, classical elegance',
  },
  {
    id: 'iranian-miniature',
    name: 'Iranian Miniature',
    nameFa: 'نگارگری ایرانی',
    category: 'Persian',
    description: 'Vivid blues, greens, and golds of Persian miniature painting',
    descriptionFa: 'آبی‌ها، سبزها و طلاهای زنده نگارگری ایرانی',
    colors: { primary: '#1A8FCA', accent: '#4A7C4F', background: '#F5EDD8', surface: '#FFFFFF', text: '#2D1B0E', muted: '#7A8B70' },
    layoutStyle: 'comic-strip sequential layout',
    thumbnailGradient: 'linear-gradient(100deg, #F5EDD8 0%, #1A8FCA 25%, #4A7C4F 50%, #D4A843 80%, #2D1B0E 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'illustrated, vivid, story-telling',
  },
  {
    id: 'haft-seen',
    name: 'Haft-Seen',
    nameFa: 'هفت‌سین',
    category: 'Persian',
    description: 'Nowruz table with green sprouts, gold coins, and red berries',
    descriptionFa: 'سفره نوروز با سبزه، سکه طلایی و سرخ شاله',
    colors: { primary: '#4CAF50', accent: '#D4A843', background: '#0A1A0E', surface: '#1A2A1E', text: '#F5E8D5', muted: '#7A8A70' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #0A1A0E 0%, #4CAF50 25%, #D4A843 55%, #C41E3A 85%, #F5E8D5 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'festive, renewal, seven symbolic items',
  },
  {
    id: 'mashhad-green',
    name: 'Mashhad Green',
    nameFa: 'سبز مشهد',
    category: 'Persian',
    description: 'Sacred green and gold of the Imam Reza shrine',
    descriptionFa: 'سبز و طلای مقدس حرم امام رضا',
    colors: { primary: '#2E7D32', accent: '#D4A843', background: '#F0F5E8', surface: '#FFFFFF', text: '#1A1A2E', muted: '#6A7A5A' },
    layoutStyle: 'radial/circular arrangement',
    thumbnailGradient: 'linear-gradient(180deg, #F0F5E8 0%, #2E7D32 30%, #D4A843 55%, #1A1A2E 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'sacred, pilgrimage, spiritual green',
  },
  {
    id: 'tehran-modern',
    name: 'Tehran Modern',
    nameFa: 'تهران مدرن',
    category: 'Persian',
    description: 'Contemporary Tehran — sleek dark with neon Persian accents',
    descriptionFa: 'تهران معاصر — تاریک شیک با تاکیدهای نئونی ایرانی',
    colors: { primary: '#A855F7', accent: '#F59E0B', background: '#0A0A0F', surface: '#1A1A2E', text: '#F8FAFC', muted: '#94A3B8' },
    layoutStyle: 'dashboard-style with widget grid',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A0F 0%, #1A1A2E 20%, #A855F7 45%, #F59E0B 70%, #F8FAFC 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'urban, sleek, neon-meets-tradition',
  },
  {
    id: 'tabriz-bazaar',
    name: 'Tabriz Bazaar',
    nameFa: 'بازار تبریز',
    category: 'Persian',
    description: 'Earthy reds and warm browns of the world\'s largest covered bazaar',
    descriptionFa: 'سرخ‌های خاکی و قهوه‌ای‌های گرم بزرگ‌ترین بازار سرپوشیده جهان',
    colors: { primary: '#A0522D', accent: '#CD853F', background: '#1E1008', surface: '#2D1F10', text: '#F5E0C5', muted: '#8A6A50' },
    layoutStyle: 'horizontal scroll gallery',
    thumbnailGradient: 'linear-gradient(90deg, #1E1008 0%, #A0522D 30%, #CD853F 60%, #F5E0C5 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'vaulted, echoing, ancient commerce',
  },
  {
    id: 'kashan-pottery',
    name: 'Kashan Pottery',
    nameFa: 'سرامیک کاشان',
    category: 'Persian',
    description: 'Blue-on-white ceramic tradition of Kashan artisans',
    descriptionFa: 'سنت سرامیک آبی‌رو‌سفید صنعتگران کاشان',
    colors: { primary: '#1565C0', accent: '#E8E0D5', background: '#F5F0E5', surface: '#FFFFFF', text: '#1A1A2E', muted: '#6A7A8A' },
    layoutStyle: 'floating cards over gradient background',
    thumbnailGradient: 'linear-gradient(135deg, #F5F0E5 0%, #1565C0 35%, #E8E0D5 65%, #1A1A2E 100%)',
    fontSuggestion: 'Vazirmatn',
    mood: 'crafted, glazed, blue-on-white',
  },
]

// ─── Japanese / Asian ────────────────────────────────────────────────────────

const JAPANESE_PALETTES: ThemePalette[] = [
  {
    id: 'sakura',
    name: 'Sakura',
    category: 'Japanese',
    description: 'Soft pink cherry blossoms against pale sky',
    colors: { primary: '#FFB7C5', accent: '#8B4557', background: '#FFF5F7', surface: '#FFFFFF', text: '#2D1B2E', muted: '#C0A0B0' },
    layoutStyle: 'floating cards over gradient background',
    thumbnailGradient: 'linear-gradient(180deg, #FFF5F7 0%, #FFB7C5 40%, #8B4557 80%, #2D1B2E 100%)',
    fontSuggestion: 'Noto Sans JP',
    mood: 'delicate, ephemeral, petal-fall',
  },
  {
    id: 'zen-garden',
    name: 'Zen Garden',
    category: 'Japanese',
    description: 'Stone grey and moss green — raked sand simplicity',
    colors: { primary: '#5D7B6F', accent: '#8B7355', background: '#F5F0E8', surface: '#FFFFFF', text: '#2D2418', muted: '#9A9080' },
    layoutStyle: 'minimal centered with generous whitespace',
    thumbnailGradient: 'linear-gradient(135deg, #F5F0E8 0%, #5D7B6F 30%, #8B7355 60%, #2D2418 100%)',
    fontSuggestion: 'Noto Sans JP',
    mood: 'still, raked, breath-between',
  },
  {
    id: 'wabi-sabi',
    name: 'Wabi-Sabi',
    category: 'Japanese',
    description: 'Imperfect beauty — muted earth tones with aged textures',
    colors: { primary: '#8B7355', accent: '#6B5B45', background: '#E8DCC8', surface: '#D5C8B5', text: '#2D1B0E', muted: '#7A6A5A' },
    layoutStyle: 'asymmetric masonry layout',
    thumbnailGradient: 'linear-gradient(150deg, #E8DCC8 0%, #8B7355 25%, #6B5B45 50%, #2D1B0E 100%)',
    fontSuggestion: 'Noto Sans JP',
    mood: 'aged, imperfect, serene acceptance',
  },
  {
    id: 'bamboo-forest',
    name: 'Bamboo Forest',
    category: 'Japanese',
    description: 'Vertical green stalks with dappled golden light',
    colors: { primary: '#4A7C4F', accent: '#D4A843', background: '#0E1A0E', surface: '#1A2A1A', text: '#E8F0E5', muted: '#6A8A60' },
    layoutStyle: 'vertical stack with alternating backgrounds',
    thumbnailGradient: 'linear-gradient(180deg, #0E1A0E 0%, #4A7C4F 30%, #D4A843 55%, #E8F0E5 100%)',
    fontSuggestion: 'Noto Sans JP',
    mood: 'vertical, filtered light, rustling',
  },
  {
    id: 'tea-ceremony',
    name: 'Tea Ceremony',
    category: 'Japanese',
    description: 'Warm matcha green and dark lacquer — ritual calm',
    colors: { primary: '#6B8E23', accent: '#1A1A2E', background: '#F0E8D5', surface: '#E5DCC8', text: '#2D1B0E', muted: '#7A6A5A' },
    layoutStyle: 'centered editorial with large typography',
    thumbnailGradient: 'linear-gradient(135deg, #F0E8D5 0%, #6B8E23 35%, #1A1A2E 65%, #2D1B0E 100%)',
    fontSuggestion: 'Noto Sans JP',
    mood: 'ritual, measured, lacquered calm',
  },
  {
    id: 'kintsugi',
    name: 'Kintsugi',
    category: 'Japanese',
    description: 'Gold-repaired cracks on dark ceramic — beauty in breakage',
    colors: { primary: '#D4A843', accent: '#E8C06A', background: '#1A1208', surface: '#2A2015', text: '#F5E8D5', muted: '#8A7A5A' },
    layoutStyle: 'overlay cards on full-bleed image',
    thumbnailGradient: 'linear-gradient(160deg, #1A1208 0%, #2A2015 20%, #D4A843 45%, #E8C06A 65%, #F5E8D5 100%)',
    fontSuggestion: 'Noto Sans JP',
    mood: 'repaired, golden scars, resilience',
  },
  {
    id: 'ukiyoe',
    name: 'Ukiyo-e',
    category: 'Japanese',
    description: 'Floating world — bold blue waves and vermilion accents',
    colors: { primary: '#1A5276', accent: '#E74C3C', background: '#F5F0E5', surface: '#FFFFFF', text: '#1A1A2E', muted: '#7A8A80' },
    layoutStyle: 'comic-strip sequential layout',
    thumbnailGradient: 'linear-gradient(100deg, #F5F0E5 0%, #1A5276 30%, #E74C3C 55%, #1A1A2E 100%)',
    fontSuggestion: 'Noto Sans JP',
    mood: 'floating world, wave crests, vivid',
  },
  {
    id: 'oni-fire',
    name: 'Oni Fire',
    category: 'Japanese',
    description: 'Demon fire — infernal red and black with electric accents',
    colors: { primary: '#FF2D2D', accent: '#FF6B35', background: '#0A0A0A', surface: '#1A1A1A', text: '#F8FAFC', muted: '#6A6A6A' },
    layoutStyle: 'parallax depth layers',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A0A 0%, #FF2D2D 30%, #FF6B35 55%, #F8FAFC 100%)',
    fontSuggestion: 'Noto Sans JP',
    mood: 'infernal, fierce, mythical',
  },
  {
    id: 'sumi-ink',
    name: 'Sumi Ink',
    category: 'Japanese',
    description: 'Black ink wash painting — shades of grey on rice paper',
    colors: { primary: '#2D2D2D', accent: '#5A5A5A', background: '#F5F0E8', surface: '#E8DCC8', text: '#1A1A1A', muted: '#8A8A8A' },
    layoutStyle: 'centered editorial with large typography',
    thumbnailGradient: 'linear-gradient(180deg, #F5F0E8 0%, #5A5A5A 35%, #2D2D2D 65%, #1A1A1A 100%)',
    fontSuggestion: 'Noto Sans JP',
    mood: 'ink wash, monochrome, contemplation',
  },
  {
    id: 'matcha',
    name: 'Matcha',
    category: 'Japanese',
    description: 'Powdered green tea — vibrant green on cream',
    colors: { primary: '#6B8E23', accent: '#8B7355', background: '#FAF6F0', surface: '#FFFFFF', text: '#2D1B0E', muted: '#7A6A5A' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #FAF6F0 0%, #6B8E23 35%, #8B7355 65%, #2D1B0E 100%)',
    fontSuggestion: 'Noto Sans JP',
    mood: 'grounded, vibrant green, grounded calm',
  },
  {
    id: 'yuzu-citrus',
    name: 'Yuzu Citrus',
    category: 'Japanese',
    description: 'Bright yuzu yellow-green with clean white backgrounds',
    colors: { primary: '#B8D430', accent: '#5D7B6F', background: '#FFFFFF', surface: '#F5F0E8', text: '#1A1A2E', muted: '#8A8A70' },
    layoutStyle: 'full-width hero + card grid below',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFFF 0%, #B8D430 35%, #5D7B6F 65%, #1A1A2E 100%)',
    fontSuggestion: 'Noto Sans JP',
    mood: 'zesty, bright, clean and crisp',
  },
  {
    id: 'shinto-red',
    name: 'Shinto Red',
    category: 'Japanese',
    description: 'Sacred vermillion torii gates against forest green',
    colors: { primary: '#C41E3A', accent: '#4A7C4F', background: '#F5F0E5', surface: '#FFFFFF', text: '#1A1A2E', muted: '#7A7A6A' },
    layoutStyle: 'radial/circular arrangement',
    thumbnailGradient: 'linear-gradient(200deg, #F5F0E5 0%, #C41E3A 30%, #4A7C4F 60%, #1A1A2E 100%)',
    fontSuggestion: 'Noto Sans JP',
    mood: 'sacred gate, forest path, threshold',
  },
]

// ─── Nordic / Scandinavian ───────────────────────────────────────────────────

const NORDIC_PALETTES: ThemePalette[] = [
  {
    id: 'fjord',
    name: 'Fjord',
    category: 'Nordic',
    description: 'Deep teal waters between grey cliffs',
    colors: { primary: '#2E8B8B', accent: '#5A7A8A', background: '#F0F5F5', surface: '#FFFFFF', text: '#1A2A3A', muted: '#8A9A9A' },
    layoutStyle: 'split-screen hero (image left, text right)',
    thumbnailGradient: 'linear-gradient(180deg, #F0F5F5 0%, #2E8B8B 35%, #5A7A8A 65%, #1A2A3A 100%)',
    fontSuggestion: 'Inter',
    mood: 'deep water, cliff face, Nordic clarity',
  },
  {
    id: 'aurora-borealis',
    name: 'Aurora Borealis',
    category: 'Nordic',
    description: 'Green-purple aurora dancing over dark polar sky',
    colors: { primary: '#00E676', accent: '#A855F7', background: '#0A0A1A', surface: '#1A1A2E', text: '#F0F0F0', muted: '#5A6A7A' },
    layoutStyle: 'parallax depth layers',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A1A 0%, #00E676 25%, #A855F7 50%, #F0F0F0 100%)',
    fontSuggestion: 'Inter',
    mood: 'dancing lights, polar night, wonder',
  },
  {
    id: 'midnight-sun',
    name: 'Midnight Sun',
    category: 'Nordic',
    description: 'Warm golden light persisting through the Arctic night',
    colors: { primary: '#F59E0B', accent: '#E8531E', background: '#1A1520', surface: '#2A2535', text: '#F8FAFC', muted: '#7A7080' },
    layoutStyle: 'fullscreen immersive hero',
    thumbnailGradient: 'linear-gradient(180deg, #1A1520 0%, #F59E0B 40%, #E8531E 70%, #F8FAFC 100%)',
    fontSuggestion: 'Inter',
    mood: 'golden persistence, Arctic warmth',
  },
  {
    id: 'birch-forest',
    name: 'Birch Forest',
    category: 'Nordic',
    description: 'White birch trunks with autumn gold leaves',
    colors: { primary: '#E8DCC8', accent: '#D4A843', background: '#F5F0E8', surface: '#FFFFFF', text: '#2D2418', muted: '#8A8070' },
    layoutStyle: 'vertical stack with alternating backgrounds',
    thumbnailGradient: 'linear-gradient(135deg, #F5F0E8 0%, #E8DCC8 25%, #D4A843 55%, #2D2418 100%)',
    fontSuggestion: 'Inter',
    mood: 'white trunks, golden canopy, autumn',
  },
  {
    id: 'arctic-ice',
    name: 'Arctic Ice',
    category: 'Nordic',
    description: 'Frozen blue-white with crystalline clarity',
    colors: { primary: '#B8D4E3', accent: '#5A8A9A', background: '#FFFFFF', surface: '#F0F5F8', text: '#1A2A3A', muted: '#8A9AA0' },
    layoutStyle: 'minimal centered with generous whitespace',
    thumbnailGradient: 'linear-gradient(180deg, #FFFFFF 0%, #B8D4E3 35%, #5A8A9A 65%, #1A2A3A 100%)',
    fontSuggestion: 'Inter',
    mood: 'crystalline, frozen, clear to the core',
  },
  {
    id: 'nordic-ember',
    name: 'Nordic Ember',
    category: 'Nordic',
    description: 'Warm fire glow in a dark Scandinavian cabin',
    colors: { primary: '#E8531E', accent: '#D4A843', background: '#1A1208', surface: '#2A2015', text: '#F5E8D5', muted: '#7A6A5A' },
    layoutStyle: 'asymmetric masonry layout',
    thumbnailGradient: 'linear-gradient(150deg, #1A1208 0%, #E8531E 30%, #D4A843 55%, #F5E8D5 100%)',
    fontSuggestion: 'Inter',
    mood: 'fire inside, warm hearth, cabin glow',
  },
  {
    id: 'lapland-frost',
    name: 'Lapland Frost',
    category: 'Nordic',
    description: 'Frosted silver and snow white with pine green',
    colors: { primary: '#C0C8D0', accent: '#4A7C4F', background: '#F8FAFC', surface: '#FFFFFF', text: '#1A2A2E', muted: '#8A90A0' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #F8FAFC 0%, #C0C8D0 25%, #4A7C4F 50%, #1A2A2E 100%)',
    fontSuggestion: 'Inter',
    mood: 'frosted, pine-scented, winter silence',
  },
  {
    id: 'scandinavian-blush',
    name: 'Scandinavian Blush',
    category: 'Nordic',
    description: 'Soft blush pink with warm grey — Nordic warmth',
    colors: { primary: '#E8D0D0', accent: '#B08080', background: '#F5F0F0', surface: '#FFFFFF', text: '#2D2424', muted: '#8A8080' },
    layoutStyle: 'floating cards over gradient background',
    thumbnailGradient: 'linear-gradient(135deg, #F5F0F0 0%, #E8D0D0 30%, #B08080 60%, #2D2424 100%)',
    fontSuggestion: 'Inter',
    mood: 'soft warmth, hygge, gentle comfort',
  },
]

// ─── Tropical / Nature ───────────────────────────────────────────────────────

const TROPICAL_PALETTES: ThemePalette[] = [
  {
    id: 'coral-reef',
    name: 'Coral Reef',
    category: 'Tropical',
    description: 'Living coral pink and turquoise ocean depths',
    colors: { primary: '#FF7F50', accent: '#40E0D0', background: '#0A1A25', surface: '#1A2A35', text: '#F0F5F5', muted: '#6A8A90' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #0A1A25 0%, #FF7F50 30%, #40E0D0 60%, #F0F5F5 100%)',
    fontSuggestion: 'Inter',
    mood: 'underwater garden, living color',
  },
  {
    id: 'jungle-canopy',
    name: 'Jungle Canopy',
    category: 'Tropical',
    description: 'Deep emerald layers with sunlit lime highlights',
    colors: { primary: '#2E7D32', accent: '#A8D830', background: '#0A1A0E', surface: '#1A2A1E', text: '#E8F0E5', muted: '#5A8A50' },
    layoutStyle: 'vertical stack with alternating backgrounds',
    thumbnailGradient: 'linear-gradient(180deg, #0A1A0E 0%, #2E7D32 30%, #A8D830 55%, #E8F0E5 100%)',
    fontSuggestion: 'Inter',
    mood: 'layered canopy, filtered sun, deep green',
  },
  {
    id: 'monsoon',
    name: 'Monsoon',
    category: 'Tropical',
    description: 'Dark storm clouds with sudden flashes of teal',
    colors: { primary: '#2E8B8B', accent: '#F0E68C', background: '#1A1A2A', surface: '#2A2A3A', text: '#E8E0D5', muted: '#5A6A7A' },
    layoutStyle: 'fullscreen immersive hero',
    thumbnailGradient: 'linear-gradient(135deg, #1A1A2A 0%, #2E8B8B 30%, #F0E68C 55%, #E8E0D5 100%)',
    fontSuggestion: 'Inter',
    mood: 'storm drama, sudden flash, relief',
  },
  {
    id: 'volcano-ember',
    name: 'Volcano Ember',
    category: 'Tropical',
    description: 'Glowing magma red and black volcanic rock',
    colors: { primary: '#FF4500', accent: '#FF8C00', background: '#0A0A08', surface: '#1A1A15', text: '#F5E8D5', muted: '#6A5A4A' },
    layoutStyle: 'parallax depth layers',
    thumbnailGradient: 'linear-gradient(180deg, #0A0A08 0%, #FF4500 30%, #FF8C00 55%, #F5E8D5 100%)',
    fontSuggestion: 'Inter',
    mood: 'molten, explosive, primal heat',
  },
  {
    id: 'ocean-deep',
    name: 'Ocean Deep',
    category: 'Tropical',
    description: 'Bioluminescent blues in the midnight zone',
    colors: { primary: '#00BCD4', accent: '#1A237E', background: '#0A0A1A', surface: '#1A1A2E', text: '#E0F7FA', muted: '#5A6A8A' },
    layoutStyle: 'glassmorphic floating panels',
    thumbnailGradient: 'linear-gradient(180deg, #0A0A1A 0%, #1A237E 30%, #00BCD4 55%, #E0F7FA 100%)',
    fontSuggestion: 'Inter',
    mood: 'bioluminescent, midnight zone, quiet glow',
  },
  {
    id: 'sahara-dusk',
    name: 'Sahara Dusk',
    category: 'Tropical',
    description: 'Warm amber and burnt sienna of endless sand',
    colors: { primary: '#D4A843', accent: '#CC5500', background: '#FAF0E0', surface: '#F5EDD8', text: '#2D1B0E', muted: '#8A7A5A' },
    layoutStyle: 'full-width hero + card grid below',
    thumbnailGradient: 'linear-gradient(135deg, #FAF0E0 0%, #D4A843 30%, #CC5500 55%, #2D1B0E 100%)',
    fontSuggestion: 'Inter',
    mood: 'endless sand, amber horizon, warm vastness',
  },
  {
    id: 'rainforest-mist',
    name: 'Rainforest Mist',
    category: 'Tropical',
    description: 'Foggy greens and damp earth — dawn in the canopy',
    colors: { primary: '#5D7B6F', accent: '#A8D830', background: '#E8F0E5', surface: '#F0F5F0', text: '#1A2A1E', muted: '#6A8A60' },
    layoutStyle: 'asymmetric masonry layout',
    thumbnailGradient: 'linear-gradient(135deg, #E8F0E5 0%, #5D7B6F 30%, #A8D830 55%, #1A2A1E 100%)',
    fontSuggestion: 'Inter',
    mood: 'damp mist, filtered dawn, alive',
  },
  {
    id: 'tropical-sunset',
    name: 'Tropical Sunset',
    category: 'Tropical',
    description: 'Mango orange fading to deep purple over the sea',
    colors: { primary: '#FF8C00', accent: '#6A0DAD', background: '#1A0A1A', surface: '#2A1A2A', text: '#F5F0E5', muted: '#7A6A7A' },
    layoutStyle: 'split-screen hero (image left, text right)',
    thumbnailGradient: 'linear-gradient(180deg, #1A0A1A 0%, #6A0DAD 25%, #FF8C00 55%, #F5F0E5 100%)',
    fontSuggestion: 'Inter',
    mood: 'mango fade, purple sea, golden hour',
  },
  {
    id: 'palm-lagoon',
    name: 'Palm Lagoon',
    category: 'Tropical',
    description: 'Turquoise lagoon beneath coconut palms',
    colors: { primary: '#40E0D0', accent: '#D4A843', background: '#F0F5F5', surface: '#FFFFFF', text: '#1A2A3A', muted: '#8A9A90' },
    layoutStyle: 'overlay cards on full-bleed image',
    thumbnailGradient: 'linear-gradient(135deg, #F0F5F5 0%, #40E0D0 35%, #D4A843 60%, #1A2A3A 100%)',
    fontSuggestion: 'Inter',
    mood: 'turquoise calm, coconut shade, island',
  },
  {
    id: 'hibiscus-flame',
    name: 'Hibiscus Flame',
    category: 'Tropical',
    description: 'Vivid hibiscus red and tropical green foliage',
    colors: { primary: '#E74C3C', accent: '#4A7C4F', background: '#F5F0E5', surface: '#FFFFFF', text: '#1A1A2E', muted: '#7A7A6A' },
    layoutStyle: 'comic-strip sequential layout',
    thumbnailGradient: 'linear-gradient(100deg, #F5F0E5 0%, #E74C3C 30%, #4A7C4F 55%, #1A1A2E 100%)',
    fontSuggestion: 'Inter',
    mood: 'tropical vivid, petals and leaves',
  },
  {
    id: 'mangrove-root',
    name: 'Mangrove Root',
    category: 'Tropical',
    description: 'Tangled dark roots with brackish green water',
    colors: { primary: '#5D7B6F', accent: '#3D5A4F', background: '#E8DCC8', surface: '#D5C8B5', text: '#2D2418', muted: '#6A7A5A' },
    layoutStyle: 'asymmetric masonry layout',
    thumbnailGradient: 'linear-gradient(150deg, #E8DCC8 0%, #5D7B6F 30%, #3D5A4F 55%, #2D2418 100%)',
    fontSuggestion: 'Inter',
    mood: 'tangled, brackish, intertidal',
  },
  {
    id: 'koi-pond',
    name: 'Koi Pond',
    category: 'Tropical',
    description: 'Orange-red koi swimming in jade-green water',
    colors: { primary: '#FF6B35', accent: '#2E8B57', background: '#0A1A15', surface: '#1A2A20', text: '#F0F5E8', muted: '#6A8A5A' },
    layoutStyle: 'floating cards over gradient background',
    thumbnailGradient: 'linear-gradient(135deg, #0A1A15 0%, #2E8B57 25%, #FF6B35 50%, #F0F5E8 100%)',
    fontSuggestion: 'Inter',
    mood: 'swimming orange, jade calm, ripple',
  },
]

// ─── Tech / Cyber ────────────────────────────────────────────────────────────

const TECH_PALETTES: ThemePalette[] = [
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    category: 'Tech',
    description: 'Neon pink and cyan on dark urban future',
    colors: { primary: '#FF2D95', accent: '#00F0FF', background: '#0A0A0F', surface: '#1A1A2E', text: '#F0F0F0', muted: '#5A6A7A' },
    layoutStyle: 'dashboard-style with widget grid',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A0F 0%, #FF2D95 30%, #00F0FF 55%, #F0F0F0 100%)',
    fontSuggestion: 'Fira Code',
    mood: 'neon-lit street, chrome, dystopian glow',
  },
  {
    id: 'neo-tokyo',
    name: 'Neo Tokyo',
    category: 'Tech',
    description: 'Japanese neon meets dark tech — holographic accents',
    colors: { primary: '#A855F7', accent: '#00F0FF', background: '#0F0F1A', surface: '#1A1A30', text: '#E0E0F0', muted: '#6A6A80' },
    layoutStyle: 'glassmorphic floating panels',
    thumbnailGradient: 'linear-gradient(135deg, #0F0F1A 0%, #A855F7 25%, #00F0FF 50%, #E0E0F0 100%)',
    fontSuggestion: 'Fira Code',
    mood: 'holographic, neon kanji, future city',
  },
  {
    id: 'matrix-green',
    name: 'Matrix Green',
    category: 'Tech',
    description: 'CRT green phosphor on pure black terminal',
    colors: { primary: '#00FF41', accent: '#008F11', background: '#000000', surface: '#0A0A0A', text: '#00FF41', muted: '#004F09' },
    layoutStyle: 'vertical stack with alternating backgrounds',
    thumbnailGradient: 'linear-gradient(180deg, #000000 0%, #008F11 30%, #00FF41 55%, #000000 100%)',
    fontSuggestion: 'Fira Code',
    mood: 'terminal phosphor, digital rain, code',
  },
  {
    id: 'quantum-field',
    name: 'Quantum Field',
    category: 'Tech',
    description: 'Subatomic blue-purple probability clouds',
    colors: { primary: '#6366F1', accent: '#A855F7', background: '#0A0A1A', surface: '#1A1A2E', text: '#F0F0F0', muted: '#5A5A7A' },
    layoutStyle: 'radial/circular arrangement',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A1A 0%, #6366F1 30%, #A855F7 55%, #F0F0F0 100%)',
    fontSuggestion: 'Fira Code',
    mood: 'probability cloud, subatomic, uncertainty',
  },
  {
    id: 'blockchain',
    name: 'Blockchain',
    category: 'Tech',
    description: 'Distributed ledger — gold nodes on dark network',
    colors: { primary: '#F7931A', accent: '#FFFFFF', background: '#0A0A0F', surface: '#1A1A1A', text: '#F0F0F0', muted: '#5A5A5A' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A0F 0%, #F7931A 35%, #FFFFFF 65%, #5A5A5A 100%)',
    fontSuggestion: 'Fira Code',
    mood: 'distributed, node-link, immutable',
  },
  {
    id: 'hologram',
    name: 'Hologram',
    category: 'Tech',
    description: 'Translucent cyan projections on dark matter',
    colors: { primary: '#00E5FF', accent: '#FF2D95', background: '#0A0A1A', surface: 'rgba(0,229,255,0.08)', text: '#E0F7FA', muted: '#5A7A8A' },
    layoutStyle: 'glassmorphic floating panels',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A1A 0%, #00E5FF 30%, #FF2D95 55%, #E0F7FA 100%)',
    fontSuggestion: 'Fira Code',
    mood: 'projected light, translucent, speculative',
  },
  {
    id: 'terminal-amber',
    name: 'Terminal Amber',
    category: 'Tech',
    description: 'Warm amber monochrome on dark — retro terminal',
    colors: { primary: '#FFB000', accent: '#FF8C00', background: '#0A0A0A', surface: '#1A1A1A', text: '#FFB000', muted: '#6A5A00' },
    layoutStyle: 'centered editorial with large typography',
    thumbnailGradient: 'linear-gradient(180deg, #0A0A0A 0%, #FF8C00 30%, #FFB000 55%, #0A0A0A 100%)',
    fontSuggestion: 'Fira Code',
    mood: 'amber phosphor, warm terminal, retro',
  },
  {
    id: 'neural-network',
    name: 'Neural Network',
    category: 'Tech',
    description: 'Connected nodes pulsing with electric blue',
    colors: { primary: '#00BCD4', accent: '#E91E63', background: '#0A0A1A', surface: '#1A1A2E', text: '#E0F7FA', muted: '#5A6A8A' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A1A 0%, #00BCD4 30%, #E91E63 55%, #E0F7FA 100%)',
    fontSuggestion: 'Fira Code',
    mood: 'connected nodes, pulsing, electric',
  },
  {
    id: 'dark-matter',
    name: 'Dark Matter',
    category: 'Tech',
    description: 'Near-black with faint gravitational distortion',
    colors: { primary: '#1A1A2E', accent: '#2E2E4E', background: '#0A0A0F', surface: '#151520', text: '#C0C0D0', muted: '#4A4A5A' },
    layoutStyle: 'minimal centered with generous whitespace',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A0F 0%, #1A1A2E 30%, #2E2E4E 55%, #C0C0D0 100%)',
    fontSuggestion: 'Fira Code',
    mood: 'invisible mass, gravitational, near-void',
  },
  {
    id: 'ai-core',
    name: 'AI Core',
    category: 'Tech',
    description: 'Electric violet and silver — machine intelligence',
    colors: { primary: '#7C3AED', accent: '#C0C0D0', background: '#0F0F1A', surface: '#1A1A30', text: '#F0F0F0', muted: '#5A6A7A' },
    layoutStyle: 'dashboard-style with widget grid',
    thumbnailGradient: 'linear-gradient(135deg, #0F0F1A 0%, #7C3AED 30%, #C0C0D0 55%, #F0F0F0 100%)',
    fontSuggestion: 'Fira Code',
    mood: 'electric intellect, synthetic, processing',
  },
  {
    id: 'satellite-uplink',
    name: 'Satellite Uplink',
    category: 'Tech',
    description: 'Cold steel grey with signal green bursts',
    colors: { primary: '#4CAF50', accent: '#B0BEC5', background: '#1A1A2A', surface: '#2A2A3A', text: '#E8E0D5', muted: '#6A7A8A' },
    layoutStyle: 'sidebar navigation + content area',
    thumbnailGradient: 'linear-gradient(135deg, #1A1A2A 0%, #4CAF50 30%, #B0BEC5 55%, #E8E0D5 100%)',
    fontSuggestion: 'Fira Code',
    mood: 'signal burst, orbital, cold steel',
  },
  {
    id: 'chrome-surface',
    name: 'Chrome Surface',
    category: 'Tech',
    description: 'Reflective metallic silver on gunmetal',
    colors: { primary: '#C0C0C0', accent: '#E0E0E0', background: '#2A2A2A', surface: '#3A3A3A', text: '#F0F0F0', muted: '#6A6A6A' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #2A2A2A 0%, #C0C0C0 30%, #E0E0E0 55%, #F0F0F0 100%)',
    fontSuggestion: 'Inter',
    mood: 'reflective, metallic, precision finish',
  },
]

// ─── Art / Movement ──────────────────────────────────────────────────────────

const ART_PALETTES: ThemePalette[] = [
  {
    id: 'bauhaus',
    name: 'Bauhaus',
    category: 'Art',
    description: 'Primary colors on white — geometric functionalism',
    colors: { primary: '#E74C3C', accent: '#2980B9', background: '#FFFFFF', surface: '#F5F5F5', text: '#1A1A1A', muted: '#6A6A6A' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFFF 0%, #E74C3C 25%, #2980B9 50%, #F59E0B 75%, #1A1A1A 100%)',
    fontSuggestion: 'Inter',
    mood: 'primary colors, geometric, form follows function',
  },
  {
    id: 'art-deco',
    name: 'Art Deco',
    category: 'Art',
    description: 'Gold and black geometric elegance — 1920s glamour',
    colors: { primary: '#D4A843', accent: '#1A1A2E', background: '#F5EDD8', surface: '#FFFFFF', text: '#2D1B0E', muted: '#8A7A5A' },
    layoutStyle: 'radial/circular arrangement',
    thumbnailGradient: 'linear-gradient(135deg, #F5EDD8 0%, #D4A843 30%, #1A1A2E 60%, #2D1B0E 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'gold geometry, 1920s glamour, jazz age',
  },
  {
    id: 'pop-art',
    name: 'Pop Art',
    category: 'Art',
    description: 'Warhol-style bright primary clashes on white',
    colors: { primary: '#FF2D2D', accent: '#FFD700', background: '#FFFFFF', surface: '#F5F5F5', text: '#1A1A1A', muted: '#8A8A8A' },
    layoutStyle: 'comic-strip sequential layout',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFFF 0%, #FF2D2D 25%, #FFD700 50%, #00CED1 75%, #1A1A1A 100%)',
    fontSuggestion: 'Inter',
    mood: 'bold clash, mass-produced, vivid',
  },
  {
    id: 'surrealism',
    name: 'Surrealism',
    category: 'Art',
    description: 'Dreamlike distortion — unexpected color juxtapositions',
    colors: { primary: '#6A0DAD', accent: '#FF6B35', background: '#E8DCC8', surface: '#D5C8B5', text: '#2D1B0E', muted: '#7A6A5A' },
    layoutStyle: 'asymmetric masonry layout',
    thumbnailGradient: 'linear-gradient(150deg, #E8DCC8 0%, #6A0DAD 30%, #FF6B35 55%, #2D1B0E 100%)',
    fontSuggestion: 'Georgia',
    mood: 'dream-logic, impossible, juxtaposed',
  },
  {
    id: 'impressionism',
    name: 'Impressionism',
    category: 'Art',
    description: 'Soft dappled light — lavender, pale green, cream',
    colors: { primary: '#9B8BB4', accent: '#A8D8A0', background: '#F5F0E8', surface: '#FFFFFF', text: '#2D2418', muted: '#8A8070' },
    layoutStyle: 'floating cards over gradient background',
    thumbnailGradient: 'linear-gradient(135deg, #F5F0E8 0%, #9B8BB4 30%, #A8D8A0 55%, #2D2418 100%)',
    fontSuggestion: 'Georgia',
    mood: 'dappled light, softened, atmospheric',
  },
  {
    id: 'cubism',
    name: 'Cubism',
    category: 'Art',
    description: 'Fragmented planes — earth tones with sharp angles',
    colors: { primary: '#8B7355', accent: '#5A8A5A', background: '#E8DCC8', surface: '#D5C0A8', text: '#2D1B0E', muted: '#7A6A5A' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #E8DCC8 0%, #8B7355 25%, #5A8A5A 50%, #C41E3A 75%, #2D1B0E 100%)',
    fontSuggestion: 'Inter',
    mood: 'fragmented, multi-angle, reassembled',
  },
  {
    id: 'renaissance',
    name: 'Renaissance',
    category: 'Art',
    description: 'Warm umber and sienna — classical masterworks',
    colors: { primary: '#A0522D', accent: '#D4A843', background: '#F5EDD8', surface: '#E8DCC8', text: '#2D1B0E', muted: '#8A7A5A' },
    layoutStyle: 'centered editorial with large typography',
    thumbnailGradient: 'linear-gradient(135deg, #F5EDD8 0%, #A0522D 30%, #D4A843 55%, #2D1B0E 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'masterwork, classical, warm depth',
  },
  {
    id: 'expressionism',
    name: 'Expressionism',
    category: 'Art',
    description: 'Raw emotional color — stark contrast and intensity',
    colors: { primary: '#C41E3A', accent: '#1A5276', background: '#0A0A0A', surface: '#1A1A1A', text: '#F0F0F0', muted: '#5A5A5A' },
    layoutStyle: 'asymmetric masonry layout',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A0A 0%, #C41E3A 30%, #1A5276 55%, #F0F0F0 100%)',
    fontSuggestion: 'Inter',
    mood: 'raw emotion, stark, inner turmoil',
  },
  {
    id: 'pointillism',
    name: 'Pointillism',
    category: 'Art',
    description: 'Dotted color atoms that blend at distance',
    colors: { primary: '#2E8B57', accent: '#E74C3C', background: '#F5F0E5', surface: '#FFFFFF', text: '#2D1B0E', muted: '#7A7A6A' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #F5F0E5 0%, #2E8B57 25%, #E74C3C 50%, #FFD700 75%, #2D1B0E 100%)',
    fontSuggestion: 'Inter',
    mood: 'atomic dots, optical blend, speckled',
  },
  {
    id: 'baroque-gold',
    name: 'Baroque Gold',
    category: 'Art',
    description: 'Opulent gold and deep burgundy — dramatic ornate',
    colors: { primary: '#D4A843', accent: '#722F37', background: '#0E0A08', surface: '#1A1510', text: '#F5E8DA', muted: '#7A6A58' },
    layoutStyle: 'overlay cards on full-bleed image',
    thumbnailGradient: 'linear-gradient(150deg, #0E0A08 0%, #722F37 25%, #D4A843 50%, #F5E8DA 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'opulent, dramatic, ornate excess',
  },
  {
    id: 'romanticism',
    name: 'Romanticism',
    category: 'Art',
    description: 'Misty landscape — soft blue and warm ochre',
    colors: { primary: '#5A8A9A', accent: '#D4A843', background: '#F0F5F0', surface: '#FFFFFF', text: '#2D2418', muted: '#8A9080' },
    layoutStyle: 'fullscreen immersive hero',
    thumbnailGradient: 'linear-gradient(135deg, #F0F5F0 0%, #5A8A9A 30%, #D4A843 55%, #2D2418 100%)',
    fontSuggestion: 'Georgia',
    mood: 'misty sublime, nature reverie, pathos',
  },
  {
    id: 'fauvism',
    name: 'Fauvism',
    category: 'Art',
    description: 'Wild color — intense unmixed pigments on white',
    colors: { primary: '#FF2D2D', accent: '#00CED1', background: '#FFFFFF', surface: '#F5F5F5', text: '#1A1A1A', muted: '#8A8A8A' },
    layoutStyle: 'comic-strip sequential layout',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFFF 0%, #FF2D2D 20%, #FFD700 35%, #00CED1 50%, #FF6B35 65%, #1A1A1A 100%)',
    fontSuggestion: 'Inter',
    mood: 'wild color, unmixed, fierce joy',
  },
]

// ─── Minimal / Clean ─────────────────────────────────────────────────────────

const MINIMAL_PALETTES: ThemePalette[] = [
  {
    id: 'swiss-design',
    name: 'Swiss Design',
    category: 'Minimal',
    description: 'Helvetica precision — red accent on pure white grid',
    colors: { primary: '#E74C3C', accent: '#1A1A1A', background: '#FFFFFF', surface: '#F5F5F5', text: '#1A1A1A', muted: '#8A8A8A' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFFF 0%, #E74C3C 30%, #1A1A1A 60%, #8A8A8A 100%)',
    fontSuggestion: 'Inter',
    mood: 'grid precision, red accent, Helvetica',
  },
  {
    id: 'material-light',
    name: 'Material Light',
    category: 'Minimal',
    description: 'Google Material — elevation shadows on white',
    colors: { primary: '#6366F1', accent: '#F59E0B', background: '#FFFFFF', surface: '#F5F5F5', text: '#1A1A1A', muted: '#8A8A8A' },
    layoutStyle: 'full-width hero + card grid below',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFFF 0%, #6366F1 30%, #F59E0B 55%, #1A1A1A 100%)',
    fontSuggestion: 'Inter',
    mood: 'elevated, shadow-layers, responsive',
  },
  {
    id: 'flat-design',
    name: 'Flat Design',
    category: 'Minimal',
    description: 'Zero-depth color blocks — no shadows no gradients',
    colors: { primary: '#00BCD4', accent: '#E74C3C', background: '#FFFFFF', surface: '#F0F0F0', text: '#1A1A1A', muted: '#8A8A8A' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFFF 0%, #00BCD4 30%, #E74C3C 55%, #1A1A1A 100%)',
    fontSuggestion: 'Inter',
    mood: 'zero-depth, flat blocks, no shadows',
  },
  {
    id: 'brutalist-web',
    name: 'Brutalist Web',
    category: 'Minimal',
    description: 'Raw HTML aesthetic — black borders, monospace, no pretense',
    colors: { primary: '#000000', accent: '#FFFFFF', background: '#FFFFFF', surface: '#F0F0F0', text: '#000000', muted: '#5A5A5A' },
    layoutStyle: 'vertical stack with alternating backgrounds',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFFF 0%, #000000 50%, #FFFFFF 100%)',
    fontSuggestion: 'Fira Code',
    mood: 'raw, unstyled, honest markup',
  },
  {
    id: 'paper-white',
    name: 'Paper White',
    category: 'Minimal',
    description: 'Pure white paper with subtle graphite marks',
    colors: { primary: '#2D2D2D', accent: '#C0C0C0', background: '#FFFFFF', surface: '#F8F8F8', text: '#2D2D2D', muted: '#A0A0A0' },
    layoutStyle: 'minimal centered with generous whitespace',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFFF 0%, #C0C0C0 30%, #2D2D2D 60%, #A0A0A0 100%)',
    fontSuggestion: 'Georgia',
    mood: 'blank page, graphite mark, quiet',
  },
  {
    id: 'mono-grey',
    name: 'Mono Grey',
    category: 'Minimal',
    description: 'All greys — charcoal to silver, zero color',
    colors: { primary: '#3A3A3A', accent: '#B0B0B0', background: '#F0F0F0', surface: '#E8E8E8', text: '#1A1A1A', muted: '#8A8A8A' },
    layoutStyle: 'centered editorial with large typography',
    thumbnailGradient: 'linear-gradient(135deg, #F0F0F0 0%, #3A3A3A 30%, #B0B0B0 55%, #1A1A1A 100%)',
    fontSuggestion: 'Inter',
    mood: 'zero-saturation, grey scale, neutral',
  },
  {
    id: 'ink-black',
    name: 'Ink Black',
    category: 'Minimal',
    description: 'Reversed — white text on pure black void',
    colors: { primary: '#FFFFFF', accent: '#C0C0C0', background: '#000000', surface: '#1A1A1A', text: '#FFFFFF', muted: '#6A6A6A' },
    layoutStyle: 'minimal centered with generous whitespace',
    thumbnailGradient: 'linear-gradient(135deg, #000000 0%, #6A6A6A 30%, #FFFFFF 60%, #C0C0C0 100%)',
    fontSuggestion: 'Inter',
    mood: 'void reversed, white on black, stark',
  },
  {
    id: 'ivory-serif',
    name: 'Ivory Serif',
    category: 'Minimal',
    description: 'Warm ivory background with elegant serif headings',
    colors: { primary: '#2D1B0E', accent: '#C9A06B', background: '#FFFFF0', surface: '#F5F0E0', text: '#2D1B0E', muted: '#8A7A5A' },
    layoutStyle: 'centered editorial with large typography',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFF0 0%, #C9A06B 30%, #2D1B0E 60%, #8A7A5A 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'ivory paper, serif elegance, refined',
  },
]

// ─── Luxury / Premium ────────────────────────────────────────────────────────

const LUXURY_PALETTES: ThemePalette[] = [
  {
    id: 'gold-standard',
    name: 'Gold Standard',
    category: 'Luxury',
    description: 'Pure gold on deep black — absolute opulence',
    colors: { primary: '#D4A843', accent: '#FFD700', background: '#0A0A08', surface: '#1A1A12', text: '#F5E8D5', muted: '#7A6A5A' },
    layoutStyle: 'centered editorial with large typography',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A08 0%, #D4A843 30%, #FFD700 55%, #F5E8D5 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'absolute gold, black backdrop, opulent',
  },
  {
    id: 'diamond-ice',
    name: 'Diamond Ice',
    category: 'Luxury',
    description: 'Crystalline white with platinum blue highlights',
    colors: { primary: '#B8D4E3', accent: '#C0C0C0', background: '#FFFFFF', surface: '#F0F5F8', text: '#1A2A3A', muted: '#8A9AA0' },
    layoutStyle: 'floating cards over gradient background',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFFF 0%, #B8D4E3 30%, #C0C0C0 55%, #1A2A3A 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'crystalline, platinum, flawless',
  },
  {
    id: 'velvet-night',
    name: 'Velvet Night',
    category: 'Luxury',
    description: 'Deep burgundy velvet with gold thread accents',
    colors: { primary: '#722F37', accent: '#D4A843', background: '#0E0A08', surface: '#1A1510', text: '#F5E0C5', muted: '#7A5A50' },
    layoutStyle: 'overlay cards on full-bleed image',
    thumbnailGradient: 'linear-gradient(150deg, #0E0A08 0%, #722F37 30%, #D4A843 55%, #F5E0C5 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'velvet touch, gold thread, deep luxury',
  },
  {
    id: 'championne',
    name: 'Champagne',
    category: 'Luxury',
    description: 'Effervescent gold bubbles on cream',
    colors: { primary: '#F5E6D3', accent: '#D4A843', background: '#FAF6F0', surface: '#FFFFFF', text: '#2D1B0E', muted: '#8A7A5A' },
    layoutStyle: 'minimal centered with generous whitespace',
    thumbnailGradient: 'linear-gradient(135deg, #FAF6F0 0%, #F5E6D3 30%, #D4A843 55%, #2D1B0E 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'effervescent, bubbly gold, celebration',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'Luxury',
    description: 'Volcanic glass black with mirror-shine silver',
    colors: { primary: '#1A1A1A', accent: '#E0E0E0', background: '#000000', surface: '#0A0A0A', text: '#F0F0F0', muted: '#4A4A4A' },
    layoutStyle: 'dashboard-style with widget grid',
    thumbnailGradient: 'linear-gradient(135deg, #000000 0%, #1A1A1A 30%, #E0E0E0 55%, #F0F0F0 100%)',
    fontSuggestion: 'Inter',
    mood: 'volcanic glass, mirror black, absolute',
  },
  {
    id: 'silk-road',
    name: 'Silk Road',
    category: 'Luxury',
    description: 'Lustrous indigo silk with amber spice accents',
    colors: { primary: '#1A237E', accent: '#D4A843', background: '#F5EDD8', surface: '#FFFFFF', text: '#2D1B0E', muted: '#7A7A6A' },
    layoutStyle: 'horizontal scroll gallery',
    thumbnailGradient: 'linear-gradient(135deg, #F5EDD8 0%, #1A237E 30%, #D4A843 55%, #2D1B0E 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'lustrous silk, amber spice, ancient trade',
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    category: 'Luxury',
    description: 'Warm copper-pink metallic on soft cream',
    colors: { primary: '#B76E79', accent: '#E8C8B0', background: '#FAF0F0', surface: '#FFFFFF', text: '#2D2020', muted: '#9A8A8A' },
    layoutStyle: 'floating cards over gradient background',
    thumbnailGradient: 'linear-gradient(135deg, #FAF0F0 0%, #B76E79 30%, #E8C8B0 55%, #2D2020 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'copper-pink, metallic warmth, refined',
  },
  {
    id: 'mahogany',
    name: 'Mahogany',
    category: 'Luxury',
    description: 'Deep red-brown polished wood with brass',
    colors: { primary: '#4E2A1A', accent: '#B5A642', background: '#0A0808', surface: '#1A1210', text: '#E8DCC8', muted: '#7A6A5A' },
    layoutStyle: 'overlay cards on full-bleed image',
    thumbnailGradient: 'linear-gradient(150deg, #0A0808 0%, #4E2A1A 30%, #B5A642 55%, #E8DCC8 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'polished wood, brass fitting, estate',
  },
]

// ─── Retro / Vintage ─────────────────────────────────────────────────────────

const RETRO_PALETTES: ThemePalette[] = [
  {
    id: '80s-neon',
    name: '80s Neon',
    category: 'Retro',
    description: 'Hot pink and electric blue — synthwave dreams',
    colors: { primary: '#FF2D95', accent: '#00F0FF', background: '#0A0A1A', surface: '#1A1A2E', text: '#F0F0F0', muted: '#5A6A7A' },
    layoutStyle: 'parallax depth layers',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A1A 0%, #FF2D95 30%, #00F0FF 55%, #F0F0F0 100%)',
    fontSuggestion: 'Inter',
    mood: 'synthwave, arc, hot neon dreams',
  },
  {
    id: '70s-groove',
    name: '70s Groove',
    category: 'Retro',
    description: 'Warm mustard and avocado green — earthy funk',
    colors: { primary: '#D4A843', accent: '#6B8E23', background: '#FAF0E0', surface: '#F5EDD8', text: '#2D1B0E', muted: '#8A7A5A' },
    layoutStyle: 'asymmetric masonry layout',
    thumbnailGradient: 'linear-gradient(135deg, #FAF0E0 0%, #D4A843 30%, #6B8E23 55%, #2D1B0E 100%)',
    fontSuggestion: 'Georgia',
    mood: 'mustard funk, avocado, earthy groove',
  },
  {
    id: '50s-diner',
    name: '50s Diner',
    category: 'Retro',
    description: 'Cherry red and cream — chrome diner aesthetic',
    colors: { primary: '#C41E3A', accent: '#C0C0C0', background: '#FFFFF0', surface: '#FFFFFF', text: '#1A1A1A', muted: '#8A8A8A' },
    layoutStyle: 'split-screen hero (image left, text right)',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFF0 0%, #C41E3A 30%, #C0C0C0 55%, #1A1A1A 100%)',
    fontSuggestion: 'Georgia',
    mood: 'chrome counter, cherry red, milkshake',
  },
  {
    id: 'victorian',
    name: 'Victorian',
    category: 'Retro',
    description: 'Deep emerald and brass — ornate dark elegance',
    colors: { primary: '#2E5E4E', accent: '#D4A843', background: '#1A1A0E', surface: '#2A2A1E', text: '#E8DCC8', muted: '#6A7A5A' },
    layoutStyle: 'centered editorial with large typography',
    thumbnailGradient: 'linear-gradient(135deg, #1A1A0E 0%, #2E5E4E 30%, #D4A843 55%, #E8DCC8 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'ornate, gaslight, brass and emerald',
  },
  {
    id: 'art-nouveau',
    name: 'Art Nouveau',
    category: 'Retro',
    description: 'Organic flowing forms — peacock blue and gold',
    colors: { primary: '#008080', accent: '#D4A843', background: '#F5EDD8', surface: '#FFFFFF', text: '#2D1B0E', muted: '#7A8A7A' },
    layoutStyle: 'radial/circular arrangement',
    thumbnailGradient: 'linear-gradient(135deg, #F5EDD8 0%, #008080 30%, #D4A843 55%, #2D1B0E 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'organic flow, peacock, whiplash curve',
  },
  {
    id: 'sepia-film',
    name: 'Sepia Film',
    category: 'Retro',
    description: 'Aged photograph tones — warm brown monochrome',
    colors: { primary: '#704214', accent: '#A0522D', background: '#F5E6D3', surface: '#EDE0CC', text: '#3C2415', muted: '#8B7355' },
    layoutStyle: 'fullscreen immersive hero',
    thumbnailGradient: 'linear-gradient(135deg, #F5E6D3 0%, #704214 30%, #A0522D 55%, #3C2415 100%)',
    fontSuggestion: 'Georgia',
    mood: 'aged photo, brown mono, warm memory',
  },
  {
    id: 'pixel-8bit',
    name: 'Pixel 8-Bit',
    category: 'Retro',
    description: 'Retro gaming — limited palette, chunky pixels',
    colors: { primary: '#FF2D2D', accent: '#00FF41', background: '#1A1A2E', surface: '#2A2A40', text: '#F0F0F0', muted: '#5A5A7A' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #1A1A2E 0%, #FF2D2D 30%, #00FF41 55%, #F0F0F0 100%)',
    fontSuggestion: 'Fira Code',
    mood: 'chunky pixel, limited palette, cartridge',
  },
  {
    id: 'western-desert',
    name: 'Western Desert',
    category: 'Retro',
    description: 'Dusty frontier — sandstone, rust, and worn leather',
    colors: { primary: '#CC5500', accent: '#8B7355', background: '#F5E6D3', surface: '#EDE0CC', text: '#3C2415', muted: '#8B7355' },
    layoutStyle: 'split-screen hero (image left, text right)',
    thumbnailGradient: 'linear-gradient(135deg, #F5E6D3 0%, #CC5500 30%, #8B7355 55%, #3C2415 100%)',
    fontSuggestion: 'Georgia',
    mood: 'dusty frontier, sandstone, worn leather',
  },
  {
    id: 'disco-gold',
    name: 'Disco Gold',
    category: 'Retro',
    description: 'Mirror-ball sparkle — gold on purple funk',
    colors: { primary: '#FFD700', accent: '#6A0DAD', background: '#1A0A1A', surface: '#2A1A2A', text: '#F5F0E5', muted: '#7A6A7A' },
    layoutStyle: 'comic-strip sequential layout',
    thumbnailGradient: 'linear-gradient(135deg, #1A0A1A 0%, #6A0DAD 30%, #FFD700 55%, #F5F0E5 100%)',
    fontSuggestion: 'Inter',
    mood: 'mirror-ball, funk groove, sparkle',
  },
  {
    id: 'polaroid',
    name: 'Polaroid',
    category: 'Retro',
    description: 'Instant photo aesthetic — white border, warm tint',
    colors: { primary: '#E8DCC8', accent: '#C41E3A', background: '#F5F0E8', surface: '#FFFFFF', text: '#2D1B0E', muted: '#8A8070' },
    layoutStyle: 'floating cards over gradient background',
    thumbnailGradient: 'linear-gradient(135deg, #F5F0E8 0%, #E8DCC8 30%, #C41E3A 55%, #2D1B0E 100%)',
    fontSuggestion: 'Georgia',
    mood: 'instant photo, white border, warm tint',
  },
  {
    id: 'cassette-tape',
    name: 'Cassette Tape',
    category: 'Retro',
    description: 'Magnetic tape brown with plastic case accents',
    colors: { primary: '#8B4513', accent: '#C0C0C0', background: '#E8DCC8', surface: '#D5C0A8', text: '#2D1B0E', muted: '#7A6A5A' },
    layoutStyle: 'horizontal scroll gallery',
    thumbnailGradient: 'linear-gradient(135deg, #E8DCC8 0%, #8B4513 30%, #C0C0C0 55%, #2D1B0E 100%)',
    fontSuggestion: 'Inter',
    mood: 'magnetic tape, plastic case, mixtape',
  },
  {
    id: 'typewriter',
    name: 'Typewriter',
    category: 'Retro',
    description: 'Olive-green machine on cream paper — mechanical',
    colors: { primary: '#5D7B6F', accent: '#2D2D2D', background: '#FFFFF0', surface: '#F5F0E0', text: '#2D1B0E', muted: '#8A7A5A' },
    layoutStyle: 'centered editorial with large typography',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFF0 0%, #5D7B6F 30%, #2D2D2D 55%, #2D1B0E 100%)',
    fontSuggestion: 'Courier New',
    mood: 'mechanical keys, cream paper, ink ribbon',
  },
]

// ─── Ethnic / Regional ───────────────────────────────────────────────────────

const ETHNIC_PALETTES: ThemePalette[] = [
  {
    id: 'african-tribal',
    name: 'African Tribal',
    category: 'Ethnic',
    description: 'Bold earth tones — terracotta, kente gold, deep brown',
    colors: { primary: '#CC5500', accent: '#FFD700', background: '#2D1B0E', surface: '#3D2B1F', text: '#F5E0C5', muted: '#8A6A50' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #2D1B0E 0%, #CC5500 30%, #FFD700 55%, #F5E0C5 100%)',
    fontSuggestion: 'Inter',
    mood: 'kente weave, terracotta, ancestral bold',
  },
  {
    id: 'indian-festival',
    name: 'Indian Festival',
    category: 'Ethnic',
    description: 'Holi color explosion — magenta, saffron, turquoise',
    colors: { primary: '#E91E63', accent: '#FF9933', background: '#FFFFFF', surface: '#F5F5F5', text: '#1A1A2E', muted: '#8A8A8A' },
    layoutStyle: 'comic-strip sequential layout',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFFF 0%, #E91E63 25%, #FF9933 50%, #40E0D0 75%, #1A1A2E 100%)',
    fontSuggestion: 'Inter',
    mood: 'Holi powder, festival, color explosion',
  },
  {
    id: 'mexican-folk',
    name: 'Mexican Folk',
    category: 'Ethnic',
    description: 'Dia de los Muertos — vibrant skull colors on warm',
    colors: { primary: '#FF6B35', accent: '#8B008B', background: '#F5E6D3', surface: '#FFFFFF', text: '#2D1B0E', muted: '#8A7A6A' },
    layoutStyle: 'asymmetric masonry layout',
    thumbnailGradient: 'linear-gradient(135deg, #F5E6D3 0%, #FF6B35 25%, #8B008B 50%, #00CED1 75%, #2D1B0E 100%)',
    fontSuggestion: 'Inter',
    mood: 'skull vivid, marigold, remembrance',
  },
  {
    id: 'moroccan-zellige',
    name: 'Moroccan Zellige',
    category: 'Ethnic',
    description: 'Geometric tile patterns — teal, terracotta, white',
    colors: { primary: '#008080', accent: '#CC5500', background: '#F5EDD8', surface: '#FFFFFF', text: '#2D1B0E', muted: '#7A8A7A' },
    layoutStyle: 'mosaic/tessellated grid',
    thumbnailGradient: 'linear-gradient(135deg, #F5EDD8 0%, #008080 30%, #CC5500 55%, #2D1B0E 100%)',
    fontSuggestion: 'Inter',
    mood: 'tile geometry, zellige, intricate pattern',
  },
  {
    id: 'turkish-bazaar',
    name: 'Turkish Bazaar',
    category: 'Ethnic',
    description: 'Spice market warmth — cinnabar, indigo, copper',
    colors: { primary: '#E34234', accent: '#1A237E', background: '#F5E6D3', surface: '#FFFFFF', text: '#2D1B0E', muted: '#7A7A6A' },
    layoutStyle: 'horizontal scroll gallery',
    thumbnailGradient: 'linear-gradient(135deg, #F5E6D3 0%, #E34234 30%, #1A237E 55%, #2D1B0E 100%)',
    fontSuggestion: 'Inter',
    mood: 'spice heap, lantern-lit, copper glow',
  },
  {
    id: 'maori-greenstone',
    name: 'Maori Greenstone',
    category: 'Ethnic',
    description: 'Pounamu green and dark earth — Pacific carving',
    colors: { primary: '#2E7D32', accent: '#A0522D', background: '#0A1A0E', surface: '#1A2A1E', text: '#E8F0E5', muted: '#6A8A60' },
    layoutStyle: 'radial/circular arrangement',
    thumbnailGradient: 'linear-gradient(135deg, #0A1A0E 0%, #2E7D32 30%, #A0522D 55%, #E8F0E5 100%)',
    fontSuggestion: 'Inter',
    mood: 'carved stone, Pacific, deep green',
  },
  {
    id: 'navajo-sand',
    name: 'Navajo Sand',
    category: 'Ethnic',
    description: 'Desert sand painting — rust, turquoise, ochre',
    colors: { primary: '#CC5500', accent: '#40E0D0', background: '#E8DCC8', surface: '#D5C0A8', text: '#3C2415', muted: '#7A6A5A' },
    layoutStyle: 'mosaic/tessellated grid',
    thumbnailGradient: 'linear-gradient(135deg, #E8DCC8 0%, #CC5500 30%, #40E0D0 55%, #3C2415 100%)',
    fontSuggestion: 'Inter',
    mood: 'sand painting, geometric, desert wisdom',
  },
  {
    id: 'celtic-mist',
    name: 'Celtic Mist',
    category: 'Ethnic',
    description: 'Misty green highlands with stone grey',
    colors: { primary: '#5D7B6F', accent: '#C0C8D0', background: '#F0F5F0', surface: '#FFFFFF', text: '#2D2418', muted: '#8A9A80' },
    layoutStyle: 'radial/circular arrangement',
    thumbnailGradient: 'linear-gradient(135deg, #F0F5F0 0%, #5D7B6F 30%, #C0C8D0 55%, #2D2418 100%)',
    fontSuggestion: 'Inter',
    mood: 'highland mist, standing stones, green grey',
  },
  {
    id: 'thai-gold',
    name: 'Thai Gold',
    category: 'Ethnic',
    description: 'Temple gold and deep red — Southeast Asian grandeur',
    colors: { primary: '#D4A843', accent: '#C41E3A', background: '#0A0A08', surface: '#1A1A12', text: '#F5E8D5', muted: '#7A6A5A' },
    layoutStyle: 'overlay cards on full-bleed image',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A08 0%, #D4A843 30%, #C41E3A 55%, #F5E8D5 100%)',
    fontSuggestion: 'Inter',
    mood: 'temple spire, deep red, gold grandeur',
  },
  {
    id: 'inca-sun',
    name: 'Inca Sun',
    category: 'Ethnic',
    description: 'Golden Inti sun on terracotta mountain',
    colors: { primary: '#D4A843', accent: '#CC5500', background: '#F5E6D3', surface: '#FFFFFF', text: '#3C2415', muted: '#8B7355' },
    layoutStyle: 'radial/circular arrangement',
    thumbnailGradient: 'linear-gradient(135deg, #F5E6D3 0%, #D4A843 30%, #CC5500 55%, #3C2415 100%)',
    fontSuggestion: 'Inter',
    mood: 'Inti sun, terracotta, mountain terraces',
  },
  {
    id: 'aboriginal-dots',
    name: 'Aboriginal Dots',
    category: 'Ethnic',
    description: 'Pointillist desert story — ochre dots on dark earth',
    colors: { primary: '#CC5500', accent: '#FFD700', background: '#1A1008', surface: '#2A2015', text: '#F5E0C5', muted: '#8A6A50' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #1A1008 0%, #CC5500 30%, #FFD700 55%, #F5E0C5 100%)',
    fontSuggestion: 'Inter',
    mood: 'dot story, ochre track, desert dreaming',
  },
  {
    id: 'korean-hanbok',
    name: 'Korean Hanbok',
    category: 'Ethnic',
    description: 'Traditional dress — jade green and vibrant pink',
    colors: { primary: '#00A86B', accent: '#FF6B9D', background: '#FFFFFF', surface: '#F5F5F5', text: '#1A1A2E', muted: '#8A8A8A' },
    layoutStyle: 'floating cards over gradient background',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFFF 0%, #00A86B 30%, #FF6B9D 55%, #1A1A2E 100%)',
    fontSuggestion: 'Noto Sans KR',
    mood: 'hanbok grace, jade and pink, tradition',
  },
]

// ─── Fantasy / Fiction ───────────────────────────────────────────────────────

const FANTASY_PALETTES: ThemePalette[] = [
  {
    id: 'elven-forest',
    name: 'Elven Forest',
    category: 'Fantasy',
    description: 'Silver birch and twilight green — elvish refinement',
    colors: { primary: '#C0D0C0', accent: '#5D7B6F', background: '#F0F5F0', surface: '#FFFFFF', text: '#2D2418', muted: '#8A9A80' },
    layoutStyle: 'minimal centered with generous whitespace',
    thumbnailGradient: 'linear-gradient(135deg, #F0F5F0 0%, #C0D0C0 30%, #5D7B6F 55%, #2D2418 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'silver birch, twilight green, elvish',
  },
  {
    id: 'space-opera',
    name: 'Space Opera',
    category: 'Fantasy',
    description: 'Starfield black with plasma nebula accents',
    colors: { primary: '#6366F1', accent: '#FF2D95', background: '#0A0A1A', surface: '#1A1A2E', text: '#F0F0F0', muted: '#5A6A7A' },
    layoutStyle: 'parallax depth layers',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A1A 0%, #6366F1 30%, #FF2D95 55%, #F0F0F0 100%)',
    fontSuggestion: 'Inter',
    mood: 'starfield, plasma, epic saga',
  },
  {
    id: 'dragon-fire',
    name: 'Dragon Fire',
    category: 'Fantasy',
    description: 'Ember scales — molten orange on ash grey',
    colors: { primary: '#FF4500', accent: '#5A5A5A', background: '#1A1A1A', surface: '#2A2A2A', text: '#F0F0F0', muted: '#6A6A6A' },
    layoutStyle: 'fullscreen immersive hero',
    thumbnailGradient: 'linear-gradient(135deg, #1A1A1A 0%, #FF4500 30%, #5A5A5A 55%, #F0F0F0 100%)',
    fontSuggestion: 'Georgia',
    mood: 'dragon scale, ember breath, ash',
  },
  {
    id: 'mermaid-depths',
    name: 'Mermaid Depths',
    category: 'Fantasy',
    description: 'Bioluminescent aqua and coral pink underwater',
    colors: { primary: '#00E5FF', accent: '#FF7F50', background: '#0A1A25', surface: '#1A2A35', text: '#E0F7FA', muted: '#5A8A9A' },
    layoutStyle: 'glassmorphic floating panels',
    thumbnailGradient: 'linear-gradient(135deg, #0A1A25 0%, #00E5FF 30%, #FF7F50 55%, #E0F7FA 100%)',
    fontSuggestion: 'Inter',
    mood: 'underwater glow, coral cave, bioluminescent',
  },
  {
    id: 'wizard-library',
    name: 'Wizard Library',
    category: 'Fantasy',
    description: 'Ancient parchment and purple magic glow',
    colors: { primary: '#6A0DAD', accent: '#D4A843', background: '#F5E6D3', surface: '#FFFFFF', text: '#2D1B0E', muted: '#8A7A6A' },
    layoutStyle: 'sidebar navigation + content area',
    thumbnailGradient: 'linear-gradient(135deg, #F5E6D3 0%, #6A0DAD 30%, #D4A843 55%, #2D1B0E 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'parchment scroll, purple glow, arcane',
  },
  {
    id: 'frost-kingdom',
    name: 'Frost Kingdom',
    category: 'Fantasy',
    description: 'Ice palace — crystalline blue-white with silver',
    colors: { primary: '#B8D4E3', accent: '#C0C8D0', background: '#F8FAFC', surface: '#FFFFFF', text: '#1A2A3A', muted: '#8A9AA0' },
    layoutStyle: 'minimal centered with generous whitespace',
    thumbnailGradient: 'linear-gradient(135deg, #F8FAFC 0%, #B8D4E3 30%, #C0C8D0 55%, #1A2A3A 100%)',
    fontSuggestion: 'Inter',
    mood: 'ice crystal, frozen throne, silver frost',
  },
  {
    id: 'shadow-realm',
    name: 'Shadow Realm',
    category: 'Fantasy',
    description: 'Void black with purple shadow wisps',
    colors: { primary: '#2E2E4E', accent: '#7C3AED', background: '#0A0A0F', surface: '#151520', text: '#C0C0D0', muted: '#4A4A5A' },
    layoutStyle: 'asymmetric masonry layout',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A0F 0%, #2E2E4E 30%, #7C3AED 55%, #C0C0D0 100%)',
    fontSuggestion: 'Inter',
    mood: 'shadow wisp, void, lurking purple',
  },
  {
    id: 'phoenix-rise',
    name: 'Phoenix Rise',
    category: 'Fantasy',
    description: 'Rebirth flame — gold ascending from ash red',
    colors: { primary: '#D4A843', accent: '#C41E3A', background: '#1A0A08', surface: '#2A1510', text: '#F5E8D5', muted: '#7A5A4A' },
    layoutStyle: 'parallax depth layers',
    thumbnailGradient: 'linear-gradient(180deg, #1A0A08 0%, #C41E3A 30%, #D4A843 55%, #F5E8D5 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'rebirth flame, ascending gold, ash to wing',
  },
]

// ─── Seasonal / Time ─────────────────────────────────────────────────────────

const SEASONAL_PALETTES: ThemePalette[] = [
  {
    id: 'spring-bloom',
    name: 'Spring Bloom',
    category: 'Seasonal',
    description: 'Fresh green and soft lilac — new growth',
    colors: { primary: '#4CAF50', accent: '#9B8BB4', background: '#F0F5F0', surface: '#FFFFFF', text: '#2D2418', muted: '#8A9A80' },
    layoutStyle: 'floating cards over gradient background',
    thumbnailGradient: 'linear-gradient(135deg, #F0F5F0 0%, #4CAF50 30%, #9B8BB4 55%, #2D2418 100%)',
    fontSuggestion: 'Inter',
    mood: 'new leaf, bud break, fresh rain',
  },
  {
    id: 'summer-heat',
    name: 'Summer Heat',
    category: 'Seasonal',
    description: 'Blazing orange and golden yellow — peak warmth',
    colors: { primary: '#FF8C00', accent: '#FFD700', background: '#FFF8F0', surface: '#FFFFFF', text: '#2D1B0E', muted: '#8A7A6A' },
    layoutStyle: 'full-width hero + card grid below',
    thumbnailGradient: 'linear-gradient(135deg, #FFF8F0 0%, #FF8C00 30%, #FFD700 55%, #2D1B0E 100%)',
    fontSuggestion: 'Inter',
    mood: 'peak heat, blazing, sun-drenched',
  },
  {
    id: 'autumn-harvest',
    name: 'Autumn Harvest',
    category: 'Seasonal',
    description: 'Burnt sienna and amber — fallen leaves and pumpkins',
    colors: { primary: '#A0522D', accent: '#D4A843', background: '#F5E6D3', surface: '#EDE0CC', text: '#3C2415', muted: '#8B7355' },
    layoutStyle: 'vertical stack with alternating backgrounds',
    thumbnailGradient: 'linear-gradient(135deg, #F5E6D3 0%, #A0522D 30%, #D4A843 55%, #3C2415 100%)',
    fontSuggestion: 'Georgia',
    mood: 'fallen leaf, pumpkin, amber warmth',
  },
  {
    id: 'winter-frost',
    name: 'Winter Frost',
    category: 'Seasonal',
    description: 'Ice blue and silver white — crystalline cold',
    colors: { primary: '#B8D4E3', accent: '#E8E8E8', background: '#FFFFFF', surface: '#F8FAFC', text: '#1A2A3A', muted: '#8A9AA0' },
    layoutStyle: 'minimal centered with generous whitespace',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFFF 0%, #B8D4E3 30%, #E8E8E8 55%, #1A2A3A 100%)',
    fontSuggestion: 'Inter',
    mood: 'crystalline, frozen breath, silver white',
  },
  {
    id: 'dawn-glow',
    name: 'Dawn Glow',
    category: 'Seasonal',
    description: 'First light — pale peach over cool grey',
    colors: { primary: '#FFDAB9', accent: '#B0BEC5', background: '#F5F0F0', surface: '#FFFFFF', text: '#2D2424', muted: '#8A90A0' },
    layoutStyle: 'split-screen hero (image left, text right)',
    thumbnailGradient: 'linear-gradient(135deg, #F5F0F0 0%, #FFDAB9 30%, #B0BEC5 55%, #2D2424 100%)',
    fontSuggestion: 'Inter',
    mood: 'first light, peach horizon, waking',
  },
  {
    id: 'twilight-purple',
    name: 'Twilight Purple',
    category: 'Seasonal',
    description: 'Dusk purple fading to deep night blue',
    colors: { primary: '#6A0DAD', accent: '#1A237E', background: '#0A0A1A', surface: '#1A1A2E', text: '#F0F0F0', muted: '#5A6A7A' },
    layoutStyle: 'fullscreen immersive hero',
    thumbnailGradient: 'linear-gradient(180deg, #0A0A1A 0%, #6A0DAD 35%, #1A237E 65%, #F0F0F0 100%)',
    fontSuggestion: 'Inter',
    mood: 'fading dusk, purple veil, night descent',
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    category: 'Seasonal',
    description: 'Photography\'s magic hour — warm amber on soft blue',
    colors: { primary: '#D4A843', accent: '#5A8A9A', background: '#F5F0E8', surface: '#FFFFFF', text: '#2D2418', muted: '#8A9080' },
    layoutStyle: 'overlay cards on full-bleed image',
    thumbnailGradient: 'linear-gradient(135deg, #F5F0E8 0%, #D4A843 30%, #5A8A9A 55%, #2D2418 100%)',
    fontSuggestion: 'Georgia',
    mood: 'magic hour, amber glow, warm lens',
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    category: 'Seasonal',
    description: 'Deepest hour — navy black with silver moon',
    colors: { primary: '#1A1A2E', accent: '#C0C0C0', background: '#0A0A0F', surface: '#151520', text: '#E0E0F0', muted: '#4A4A5A' },
    layoutStyle: 'minimal centered with generous whitespace',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A0F 0%, #1A1A2E 30%, #C0C0C0 55%, #E0E0F0 100%)',
    fontSuggestion: 'Inter',
    mood: 'deepest hour, silver moon, navy void',
  },
]

// ─── Food / Culinary ─────────────────────────────────────────────────────────

const FOOD_PALETTES: ThemePalette[] = [
  {
    id: 'coffee-house',
    name: 'Coffee House',
    category: 'Food',
    description: 'Rich espresso brown with cream foam',
    colors: { primary: '#3C2415', accent: '#F5E6D3', background: '#FAF0E0', surface: '#FFFFFF', text: '#2D1B0E', muted: '#8A7A5A' },
    layoutStyle: 'sidebar navigation + content area',
    thumbnailGradient: 'linear-gradient(135deg, #FAF0E0 0%, #3C2415 30%, #F5E6D3 55%, #2D1B0E 100%)',
    fontSuggestion: 'Georgia',
    mood: 'espresso depth, cream layer, roasted',
  },
  {
    id: 'wine-cellar',
    name: 'Wine Cellar',
    category: 'Food',
    description: 'Deep burgundy and oak — barrel-aged elegance',
    colors: { primary: '#722F37', accent: '#8B7355', background: '#0E0A08', surface: '#1A1510', text: '#F5E0C5', muted: '#7A5A50' },
    layoutStyle: 'centered editorial with large typography',
    thumbnailGradient: 'linear-gradient(150deg, #0E0A08 0%, #722F37 30%, #8B7355 55%, #F5E0C5 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'barrel-aged, oak tannin, cellar depth',
  },
  {
    id: 'spice-market',
    name: 'Spice Market',
    category: 'Food',
    description: 'Cinnabar red, turmeric gold, cardamom green',
    colors: { primary: '#E34234', accent: '#E3A830', background: '#F5E6D3', surface: '#FFFFFF', text: '#2D1B0E', muted: '#8A7A6A' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #F5E6D3 0%, #E34234 25%, #E3A830 50%, #4A7C4F 75%, #2D1B0E 100%)',
    fontSuggestion: 'Inter',
    mood: 'spice mound, aromatic, layered color',
  },
  {
    id: 'chocolate-dark',
    name: 'Chocolate Dark',
    category: 'Food',
    description: 'Bittersweet dark chocolate with gold drizzle',
    colors: { primary: '#3C1414', accent: '#D4A843', background: '#0E0808', surface: '#1A0E0E', text: '#F5E8D5', muted: '#6A5A4A' },
    layoutStyle: 'overlay cards on full-bleed image',
    thumbnailGradient: 'linear-gradient(135deg, #0E0808 0%, #3C1414 30%, #D4A843 55%, #F5E8D5 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'bittersweet, gold drizzle, dark melt',
  },
  {
    id: 'olive-grove',
    name: 'Olive Grove',
    category: 'Food',
    description: 'Mediterranean olive green with warm stone',
    colors: { primary: '#6B8E23', accent: '#C9A06B', background: '#F5EDD8', surface: '#FFFFFF', text: '#2D1B0E', muted: '#7A7A5A' },
    layoutStyle: 'floating cards over gradient background',
    thumbnailGradient: 'linear-gradient(135deg, #F5EDD8 0%, #6B8E23 30%, #C9A06B 55%, #2D1B0E 100%)',
    fontSuggestion: 'Inter',
    mood: 'olive grove, warm stone, Mediterranean',
  },
  {
    id: 'sushi-fresh',
    name: 'Sushi Fresh',
    category: 'Food',
    description: 'Clean white with salmon accent and nori green',
    colors: { primary: '#FA8072', accent: '#2E7D32', background: '#FFFFFF', surface: '#F8F8F8', text: '#1A1A2E', muted: '#8A8A8A' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFFF 0%, #FA8072 30%, #2E7D32 55%, #1A1A2E 100%)',
    fontSuggestion: 'Inter',
    mood: 'fresh cut, clean white, salmon slice',
  },
  {
    id: 'berry-tart',
    name: 'Berry Tart',
    category: 'Food',
    description: 'Blueberry and raspberry on pastry cream',
    colors: { primary: '#4A5899', accent: '#C41E3A', background: '#FFFFF0', surface: '#FFFFFF', text: '#2D1B0E', muted: '#8A8A7A' },
    layoutStyle: 'floating cards over gradient background',
    thumbnailGradient: 'linear-gradient(135deg, #FFFFF0 0%, #4A5899 30%, #C41E3A 55%, #2D1B0E 100%)',
    fontSuggestion: 'Georgia',
    mood: 'berry burst, pastry cream, tart sweet',
  },
  {
    id: 'honey-amber',
    name: 'Honey Amber',
    category: 'Food',
    description: 'Liquid amber honey on warm oat',
    colors: { primary: '#D4A843', accent: '#CC5500', background: '#FAF6F0', surface: '#FFFFFF', text: '#2D1B0E', muted: '#8A7A5A' },
    layoutStyle: 'minimal centered with generous whitespace',
    thumbnailGradient: 'linear-gradient(135deg, #FAF6F0 0%, #D4A843 30%, #CC5500 55%, #2D1B0E 100%)',
    fontSuggestion: 'Georgia',
    mood: 'liquid amber, slow pour, warm oat',
  },
]

// ─── Music / Dance ───────────────────────────────────────────────────────────

const MUSIC_PALETTES: ThemePalette[] = [
  {
    id: 'jazz-club',
    name: 'Jazz Club',
    category: 'Music',
    description: 'Smoke-haze brass and deep blue — late night set',
    colors: { primary: '#D4A843', accent: '#1A237E', background: '#0A0A08', surface: '#1A1A12', text: '#F5E0C5', muted: '#6A5A5A' },
    layoutStyle: 'sidebar navigation + content area',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A08 0%, #1A237E 30%, #D4A843 55%, #F5E0C5 100%)',
    fontSuggestion: 'Georgia',
    mood: 'brass smoke, late set, blue note',
  },
  {
    id: 'symphony',
    name: 'Symphony',
    category: 'Music',
    description: 'Classical gravitas — burgundy velvet and gold',
    colors: { primary: '#722F37', accent: '#D4A843', background: '#F5EDD8', surface: '#FFFFFF', text: '#2D1B0E', muted: '#8A7A5A' },
    layoutStyle: 'centered editorial with large typography',
    thumbnailGradient: 'linear-gradient(135deg, #F5EDD8 0%, #722F37 30%, #D4A843 55%, #2D1B0E 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'concert hall, velvet seat, crescendo',
  },
  {
    id: 'hip-hop',
    name: 'Hip Hop',
    category: 'Music',
    description: 'Street gold and boom-bap black — raw beats',
    colors: { primary: '#FFD700', accent: '#FFFFFF', background: '#0A0A0A', surface: '#1A1A1A', text: '#F0F0F0', muted: '#5A5A5A' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A0A 0%, #FFD700 30%, #FFFFFF 55%, #F0F0F0 100%)',
    fontSuggestion: 'Inter',
    mood: 'boom-bap, street gold, raw beats',
  },
  {
    id: 'electronic-wave',
    name: 'Electronic Wave',
    category: 'Music',
    description: 'Oscillating synth — cyan pulse on dark bass',
    colors: { primary: '#00E5FF', accent: '#FF2D95', background: '#0A0A1A', surface: '#1A1A2E', text: '#E0F7FA', muted: '#5A6A8A' },
    layoutStyle: 'dashboard-style with widget grid',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A1A 0%, #00E5FF 30%, #FF2D95 55%, #E0F7FA 100%)',
    fontSuggestion: 'Fira Code',
    mood: 'synth pulse, oscillating, bass dark',
  },
  {
    id: 'blues-road',
    name: 'Blues Road',
    category: 'Music',
    description: 'Delta mud and sky blue — highway melancholy',
    colors: { primary: '#5A8A9A', accent: '#8B7355', background: '#E8DCC8', surface: '#D5C0A8', text: '#2D1B0E', muted: '#7A6A5A' },
    layoutStyle: 'split-screen hero (image left, text right)',
    thumbnailGradient: 'linear-gradient(135deg, #E8DCC8 0%, #5A8A9A 30%, #8B7355 55%, #2D1B0E 100%)',
    fontSuggestion: 'Georgia',
    mood: 'delta mud, highway blue, melancholy',
  },
  {
    id: 'opera-red',
    name: 'Opera Red',
    category: 'Music',
    description: 'Grand curtain red and gilded stage',
    colors: { primary: '#C41E3A', accent: '#D4A843', background: '#0E0A08', surface: '#1A1510', text: '#F5E0C5', muted: '#7A5A50' },
    layoutStyle: 'fullscreen immersive hero',
    thumbnailGradient: 'linear-gradient(150deg, #0E0A08 0%, #C41E3A 30%, #D4A843 55%, #F5E0C5 100%)',
    fontSuggestion: 'Playfair Display',
    mood: 'curtain rise, gilded stage, grand aria',
  },
]

// ─── Cosmic / Space ──────────────────────────────────────────────────────────

const COSMIC_PALETTES: ThemePalette[] = [
  {
    id: 'nebula',
    name: 'Nebula',
    category: 'Cosmic',
    description: 'Interstellar gas clouds — violet and magenta swirl',
    colors: { primary: '#A855F7', accent: '#FF2D95', background: '#0A0A1A', surface: '#1A1A2E', text: '#E0E0F0', muted: '#5A6A7A' },
    layoutStyle: 'parallax depth layers',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A1A 0%, #A855F7 25%, #6366F1 45%, #FF2D95 65%, #E0E0F0 100%)',
    fontSuggestion: 'Inter',
    mood: 'gas cloud, violet swirl, stellar nursery',
  },
  {
    id: 'supernova',
    name: 'Supernova',
    category: 'Cosmic',
    description: 'Explosive white core with expanding ring of fire',
    colors: { primary: '#FFFFFF', accent: '#FF4500', background: '#0A0A0A', surface: '#1A1A1A', text: '#F0F0F0', muted: '#5A5A5A' },
    layoutStyle: 'radial/circular arrangement',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A0A 0%, #FFFFFF 20%, #FF4500 40%, #FFD700 60%, #0A0A0A 100%)',
    fontSuggestion: 'Inter',
    mood: 'core flash, expanding ring, stellar death',
  },
  {
    id: 'dark-matter-cosmic',
    name: 'Dark Matter',
    category: 'Cosmic',
    description: 'Unseen gravitational glue — near-black distortion',
    colors: { primary: '#1A1A2E', accent: '#3A3A5A', background: '#0A0A0F', surface: '#151520', text: '#C0C0D0', muted: '#4A4A5A' },
    layoutStyle: 'minimal centered with generous whitespace',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A0F 0%, #1A1A2E 30%, #3A3A5A 55%, #C0C0D0 100%)',
    fontSuggestion: 'Inter',
    mood: 'invisible mass, lensing, void structure',
  },
  {
    id: 'solar-wind',
    name: 'Solar Wind',
    category: 'Cosmic',
    description: 'Coronal gold streaming through aurora teal',
    colors: { primary: '#FFD700', accent: '#00E5FF', background: '#0A0A1A', surface: '#1A1A30', text: '#F0F0F0', muted: '#5A6A7A' },
    layoutStyle: 'fullscreen immersive hero',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A1A 0%, #00E5FF 30%, #FFD700 55%, #F0F0F0 100%)',
    fontSuggestion: 'Inter',
    mood: 'coronal stream, aurora ribbon, charged',
  },
  {
    id: 'mars-red',
    name: 'Mars Red',
    category: 'Cosmic',
    description: 'Iron oxide rust under thin salmon sky',
    colors: { primary: '#CC5500', accent: '#FA8072', background: '#1A0A08', surface: '#2A1510', text: '#F5E0C5', muted: '#7A5A4A' },
    layoutStyle: 'bento grid (mixed-size cards)',
    thumbnailGradient: 'linear-gradient(135deg, #1A0A08 0%, #CC5500 30%, #FA8072 55%, #F5E0C5 100%)',
    fontSuggestion: 'Inter',
    mood: 'iron rust, thin sky, red desert planet',
  },
  {
    id: 'saturn-ring',
    name: 'Saturn Ring',
    category: 'Cosmic',
    description: 'Pale gold ring against deep space navy',
    colors: { primary: '#E8DCC8', accent: '#D4A843', background: '#0A0A1A', surface: '#1A1A2E', text: '#F0F0F0', muted: '#5A6A7A' },
    layoutStyle: 'radial/circular arrangement',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A1A 0%, #D4A843 30%, #E8DCC8 55%, #F0F0F0 100%)',
    fontSuggestion: 'Inter',
    mood: 'orbital ring, pale gold, gas giant',
  },
  {
    id: 'comet-tail',
    name: 'Comet Tail',
    category: 'Cosmic',
    description: 'Luminous trail streaking through dark void',
    colors: { primary: '#E0F7FA', accent: '#FFD700', background: '#0A0A1A', surface: '#1A1A2E', text: '#E0E0F0', muted: '#5A6A7A' },
    layoutStyle: 'parallax depth layers',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A1A 0%, #E0F7FA 25%, #FFD700 50%, #E0E0F0 100%)',
    fontSuggestion: 'Inter',
    mood: 'luminous trail, streaking, celestial visitor',
  },
  {
    id: 'milky-way',
    name: 'Milky Way',
    category: 'Cosmic',
    description: 'Dust-lane galaxy — warm stars in cool dark',
    colors: { primary: '#C9A06B', accent: '#6366F1', background: '#0A0A1A', surface: '#1A1A2E', text: '#E0E0F0', muted: '#5A6A7A' },
    layoutStyle: 'fullscreen immersive hero',
    thumbnailGradient: 'linear-gradient(135deg, #0A0A1A 0%, #C9A06B 25%, #6366F1 50%, #E0E0F0 100%)',
    fontSuggestion: 'Inter',
    mood: 'dust lane, star field, galactic arm',
  },
]

// ─── Combine all palettes ────────────────────────────────────────────────────

export const ALL_PALETTES: ThemePalette[] = [
  ...PERSIAN_PALETTES,
  ...JAPANESE_PALETTES,
  ...NORDIC_PALETTES,
  ...TROPICAL_PALETTES,
  ...TECH_PALETTES,
  ...ART_PALETTES,
  ...MINIMAL_PALETTES,
  ...LUXURY_PALETTES,
  ...RETRO_PALETTES,
  ...ETHNIC_PALETTES,
  ...FANTASY_PALETTES,
  ...SEASONAL_PALETTES,
  ...FOOD_PALETTES,
  ...MUSIC_PALETTES,
  ...COSMIC_PALETTES,
]

export const PALETTE_CATEGORIES = Array.from(new Set(ALL_PALETTES.map(p => p.category)))
