import type { IndustryMeta } from './types';

// ─── E-commerce & Retail industries ───────────────────────────────────────
// 13 industries in this group.

export const ECOMMERCE_INDUSTRIES: IndustryMeta[] = [
  {
    id: 'carpet',
    nameEn: 'Carpet & Rug Store',
    nameFa: 'فروشگاه فرش و قالی',
    group: 'E-commerce',
    groupFa: 'فروشگاهی',
    keywords: ['carpet', 'rug', 'فرش', 'قالی', 'گلیم', 'carpet store', 'rug store', 'persian rug', 'قالی ایرانی', 'فرش دستباف', 'قالین', 'carpet shop'],
    subIndustries: [
      { id: 'persian-traditional', nameEn: 'Persian Traditional', nameFa: 'سنتی ایرانی', keywords: ['persian', 'traditional', 'ایرانی', 'سنتی', 'اصیل', 'كرمان', 'كاشان', 'تبريز', 'قوين'] },
      { id: 'modern-designer', nameEn: 'Modern Designer Rugs', nameFa: 'طراح مدرن', keywords: ['modern', 'designer', 'مدرن', 'طراحی', 'مدرن', 'طراح'] },
      { id: 'vintage-antique', nameEn: 'Vintage & Antique', nameFa: 'عتیقه و قدیمی', keywords: ['vintage', 'antique', 'عتیقه', 'قدیمی', 'نادر'] },
      { id: 'machine-made', nameEn: 'Machine-made', nameFa: 'دستگاهی', keywords: ['machine', 'دستگاهی', 'ماشینی', 'مکانیزه'] },
    ],
    palette: {
      light: { bg: '#FAF6F0', surface: '#FFFFFF', accent: '#8B4513', text: '#2D1B0E', muted: '#7A6A5A' },
      dark: { bg: '#1A1310', surface: '#241B16', accent: '#C9A06B', text: '#F5E9DA', muted: '#9C8B78' },
    },
    suggestedSections: ['hero', 'featured-collections', 'product-grid', 'origin-story', 'craftsmanship', 'material-guide', 'sizing-guide', 'testimonials', 'newsletter', 'contact'],
    sampleProducts: ['Silk Isfahan Rug 9x12', 'Tabriz Mahi Pattern 6x9', 'Kashan Wool Rug 8x10', 'Vintage Heriz 10x14', 'Modern Geometric 5x7', 'Runner Rug 2.5x10', 'Kilim Flatweave 4x6', 'Round Carpet 8ft'],
    imageSearchKeywords: {
      hero: ['persian carpet luxury', 'oriental rug pattern', 'carpet showroom elegant'],
      product: ['persian rug closeup', 'handwoven carpet detail', 'oriental rug folded'],
      lifestyle: ['carpet in living room', 'rug on wood floor', 'persian rug interior'],
      team: ['carpet weaver artisan', 'rug maker working', 'craftsman at loom'],
      workspace: ['carpet showroom interior', 'rug store display', 'carpet shop'],
      detail: ['carpet knot detail', 'rug weaving closeup', 'silk thread texture'],
    },
    fontPairing: 'Playfair Display + Inter',
    patternHint: 'subtle Persian arabesque (بته‌جقه) motifs in section dividers',
  },
  {
    id: 'fashion',
    nameEn: 'Fashion & Clothing',
    nameFa: 'مد و پوشاک',
    group: 'E-commerce',
    groupFa: 'فروشگاهی',
    keywords: ['fashion', 'clothing', 'پوشاک', 'لباس', 'apparel', 'clothes', 'boutique', 'مد', 'فشن', 'تیشرت', 'پیراهن', 'شلوار', 'پالتو', 'مانتو', 'fashion store', 'clothing store'],
    subIndustries: [
      { id: 'women', nameEn: "Women's Fashion", nameFa: 'لباس زنانه', keywords: ['women', 'زنانه', 'دخترانه', 'woman'] },
      { id: 'men', nameEn: "Men's Fashion", nameFa: 'لباس مردانه', keywords: ['men', 'مردانه', 'پسرانه', 'man'] },
      { id: 'kids', nameEn: "Kids' Fashion", nameFa: 'لباس کودک', keywords: ['kids', 'کودک', 'بچگانه', 'children', 'kids'] },
      { id: 'sportswear', nameEn: 'Sportswear', nameFa: 'ورزشی', keywords: ['sport', 'ورزشی', 'activewear', 'fitness wear'] },
      { id: 'accessories', nameEn: 'Accessories', nameFa: 'اکسسوری', keywords: ['accessories', 'اکسسوری', 'bag', 'کیف', 'belt', 'کمربند'] },
    ],
    palette: {
      light: { bg: '#FFFFFF', surface: '#F8F8F8', accent: '#E11D48', text: '#0A0A0A', muted: '#6B7280' },
      dark: { bg: '#0A0A0A', surface: '#171717', accent: '#FB7185', text: '#FAFAFA', muted: '#9CA3AF' },
    },
    suggestedSections: ['hero', 'new-arrivals', 'category-grid', 'featured-collection', 'lookbook', 'sale-banner', 'instagram-feed', 'newsletter', 'footer'],
    sampleProducts: ['Wool Overcoat', 'Linen Shirt', 'Pleated Midi Skirt', 'Oversized Tee', 'Selvedge Denim', 'Cashmere Sweater', 'Tailored Blazer', 'Silk Scarf'],
    imageSearchKeywords: {
      hero: ['fashion model editorial', 'clothing brand banner', 'fashion photography elegant'],
      product: ['clothing product shot', 'folded shirt flatlay', 'dress on hanger'],
      lifestyle: ['street style fashion', 'outfit lookbook', 'fashion lifestyle outdoor'],
      team: ['fashion designer studio', 'tailor working', 'designer at sewing machine'],
      workspace: ['boutique store interior', 'clothing rack display', 'fashion retail shop'],
      detail: ['fabric texture closeup', 'button stitching detail', 'denim weave texture'],
    },
    fontPairing: 'Playfair Display + Inter',
  },
  {
    id: 'digital',
    nameEn: 'Digital & Electronics',
    nameFa: 'دیجیتال و الکترونیک',
    group: 'E-commerce',
    groupFa: 'فروشگاهی',
    keywords: ['digital', 'electronic', 'دیجیتال', 'الکترونیک', 'gadget', 'tech store', 'گجت', 'موبایل', 'لپتاپ', 'تلفن همراه', 'کامپیوتر', 'electronics store'],
    subIndustries: [
      { id: 'mobile', nameEn: 'Mobile & Tablets', nameFa: 'موبایل و تبلت', keywords: ['mobile', 'phone', 'موبایل', 'گوشی', 'tablet', 'تبلت', 'smartphone'] },
      { id: 'laptop', nameEn: 'Laptops & Computers', nameFa: 'لپتاپ و کامپیوتر', keywords: ['laptop', 'computer', 'لپتاپ', 'کامپیوتر', 'pc', 'notebook'] },
      { id: 'audio', nameEn: 'Audio & Headphones', nameFa: 'صوتی و هدفون', keywords: ['audio', 'headphone', 'هدفون', 'اسپیکر', 'speaker', 'earbud'] },
      { id: 'smart-home', nameEn: 'Smart Home', nameFa: 'خانه هوشمند', keywords: ['smart home', 'خانه هوشمند', 'iot', 'smart device'] },
      { id: 'gaming', nameEn: 'Gaming', nameFa: 'گیمینگ', keywords: ['gaming', 'گیمینگ', 'game', 'بازی', 'console', 'کنسول'] },
    ],
    palette: {
      light: { bg: '#FFFFFF', surface: '#F1F5F9', accent: '#0EA5E9', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0B1120', surface: '#131C31', accent: '#38BDF8', text: '#F1F5F9', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'brands-strip', 'category-cards', 'featured-products', 'tech-specs', 'comparison-table', 'reviews', 'warranty', 'newsletter', 'footer'],
    sampleProducts: ['Wireless Noise-Cancelling Headphones', '4K Action Camera', 'Smartwatch Series 9', 'Mechanical Keyboard RGB', 'Power Bank 20000mAh', 'Bluetooth Speaker', 'VR Headset', 'Drone Pro 4K'],
    imageSearchKeywords: {
      hero: ['tech gadget banner', 'electronics hero dark', 'smart device flatlay'],
      product: ['headphone product shot', 'smartwatch on white', 'laptop product photo'],
      lifestyle: ['person using laptop', 'tech lifestyle workspace', 'gadgets on desk'],
      team: ['tech support team', 'engineer working', 'repair technician'],
      workspace: ['electronics store modern', 'tech shop interior', 'apple store style'],
      detail: ['circuit board closeup', 'headphone port detail', 'tech texture macro'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'home',
    nameEn: 'Home & Furniture',
    nameFa: 'لوازم خانگی و مبلمان',
    group: 'E-commerce',
    groupFa: 'فروشگاهی',
    keywords: ['home goods', 'لوازم خانگی', 'furniture', 'مبل', 'decor', 'دکوراسیون', 'home store', 'furniture store', 'home decor', 'آشپزخانه', 'خوابگاه'],
    subIndustries: [
      { id: 'living-room', nameEn: 'Living Room', nameFa: 'پذیرایی', keywords: ['living room', 'پذیرایی', 'sofa', 'مبل', 'couch'] },
      { id: 'bedroom', nameEn: 'Bedroom', nameFa: 'خوابگاه', keywords: ['bedroom', 'خوابگاه', 'bed', 'تخت'] },
      { id: 'kitchen', nameEn: 'Kitchen', nameFa: 'آشپزخانه', keywords: ['kitchen', 'آشپزخانه', 'cookware', 'ظروف'] },
      { id: 'lighting', nameEn: 'Lighting', nameFa: 'نورپردازی', keywords: ['lighting', 'نور', 'lamp', 'چراغ', 'chandelier'] },
      { id: 'decor', nameEn: 'Decor', nameFa: 'دکوری', keywords: ['decor', 'دکوری', 'vase', 'گلدان', 'art'] },
    ],
    palette: {
      light: { bg: '#FAFAF7', surface: '#FFFFFF', accent: '#92400E', text: '#1C1917', muted: '#78716C' },
      dark: { bg: '#1C1917', surface: '#292524', accent: '#D6A065', text: '#FAFAF7', muted: '#A8A29E' },
    },
    suggestedSections: ['hero', 'room-categories', 'featured-collections', 'design-inspiration', 'materials-guide', 'delivery-info', 'reviews', 'newsletter', 'footer'],
    sampleProducts: ['3-Seater Linen Sofa', 'Oak Dining Table', 'Velvet Accent Chair', 'Marble Coffee Table', 'Brass Floor Lamp', 'Walnut Bookshelf', 'King Bed Frame', 'Wool Area Rug'],
    imageSearchKeywords: {
      hero: ['modern living room interior', 'home decor banner', 'furniture showroom'],
      product: ['sofa product photo', 'chair isolated white', 'table product shot'],
      lifestyle: ['cozy living room', 'scandinavian interior', 'modern bedroom design'],
      team: ['interior designer working', 'furniture maker workshop', 'designer sketching'],
      workspace: ['furniture showroom interior', 'home goods store', 'furniture warehouse'],
      detail: ['wood grain texture', 'fabric swatch closeup', 'metal hardware detail'],
    },
    fontPairing: 'Cormorant Garamond + Inter',
  },
  {
    id: 'beauty',
    nameEn: 'Beauty & Cosmetics',
    nameFa: 'زیبایی و آرایشی',
    group: 'E-commerce',
    groupFa: 'فروشگاهی',
    keywords: ['beauty', 'cosmetics', 'آرایشی', 'زیبایی', 'makeup', 'skincare', 'آرایش', 'مراقبت پوست', 'عطر', 'perfume', 'beauty store'],
    subIndustries: [
      { id: 'makeup', nameEn: 'Makeup', nameFa: 'آرایش', keywords: ['makeup', 'آرایش', 'lipstick', 'رژ لب', 'foundation'] },
      { id: 'skincare', nameEn: 'Skincare', nameFa: 'مراقبت پوست', keywords: ['skincare', 'پوست', 'cream', 'کرم', 'serum'] },
      { id: 'fragrance', nameEn: 'Fragrance', nameFa: 'عطر', keywords: ['fragrance', 'عطر', 'perfume', 'ادکلن', 'cologne'] },
      { id: 'haircare', nameEn: 'Haircare', nameFa: 'مراقبت مو', keywords: ['hair', 'مو', 'shampoo', 'شامپو', 'haircare'] },
    ],
    palette: {
      light: { bg: '#FDF2F8', surface: '#FFFFFF', accent: '#DB2777', text: '#500724', muted: '#9D8B96' },
      dark: { bg: '#1A0F18', surface: '#261822', accent: '#F472B6', text: '#FDF2F8', muted: '#A78AA0' },
    },
    suggestedSections: ['hero', 'new-arrivals', 'best-sellers', 'shop-by-concern', 'ingredients-story', 'tutorial-videos', 'reviews', 'newsletter', 'footer'],
    sampleProducts: ['Hydrating Serum Vitamin C', 'Matte Lipstick Crimson', 'Foundation Full Coverage', 'Eyeshadow Palette 12-pan', 'Night Retinol Cream', 'Hair Repair Mask', 'Eau de Parfum 50ml', 'Facial Cleanser'],
    imageSearchKeywords: {
      hero: ['beauty product banner', 'cosmetics flatlay pink', 'makeup editorial'],
      product: ['cosmetic bottle product', 'lipstick isolated white', 'skincare jar product'],
      lifestyle: ['woman applying makeup', 'beauty routine lifestyle', 'skincare model'],
      team: ['makeup artist working', 'beauty professional portrait', 'cosmetic chemist lab'],
      workspace: ['beauty store interior', 'cosmetics shop display', 'makeup studio'],
      detail: ['cosmetic texture macro', 'cream swirl closeup', 'perfume bottle detail'],
    },
    fontPairing: 'Cormorant Garamond + Inter',
  },
  {
    id: 'jewelry',
    nameEn: 'Jewelry & Watches',
    nameFa: 'جواهر و ساعت',
    group: 'E-commerce',
    groupFa: 'فروشگاهی',
    keywords: ['jewelry', 'جواهر', 'gold', 'طلا', 'silver', 'نقره', 'diamond', 'الماس', 'watch', 'ساعت', 'jewelry store', 'jeweller'],
    subIndustries: [
      { id: 'gold', nameEn: 'Gold Jewelry', nameFa: 'طلا', keywords: ['gold', 'طلا', 'golden', 'gold jewelry'] },
      { id: 'silver', nameEn: 'Silver Jewelry', nameFa: 'نقره', keywords: ['silver', 'نقره', 'sterling'] },
      { id: 'diamond', nameEn: 'Diamond', nameFa: 'الماس', keywords: ['diamond', 'الماس', 'brilliant'] },
      { id: 'watches', nameEn: 'Watches', nameFa: 'ساعت', keywords: ['watch', 'ساعت', 'timepiece', 'clock'] },
      { id: 'gemstones', nameEn: 'Gemstones', nameFa: 'سنگ قیمتی', keywords: ['gemstone', 'سنگ', 'ruby', 'یاقوت', 'emerald', 'زمرد'] },
    ],
    palette: {
      light: { bg: '#FFFBF0', surface: '#FFFFFF', accent: '#B45309', text: '#1F2937', muted: '#9CA3AF' },
      dark: { bg: '#0A0A0A', surface: '#161616', accent: '#FBBF24', text: '#FAFAFA', muted: '#9CA3AF' },
    },
    suggestedSections: ['hero', 'collections', 'featured-pieces', 'craftsmanship', 'materials-guide', 'certifications', 'custom-order', 'newsletter', 'footer'],
    sampleProducts: ['Diamond Solitaire Ring 1ct', 'Gold Chain Necklace 18k', 'Pearl Stud Earrings', 'Silver Bracelet Tennis', 'Emerald Pendant', 'Mechanical Watch Gold', 'Engagement Ring Set', 'Vintage Brooch'],
    imageSearchKeywords: {
      hero: ['luxury jewelry banner', 'gold necklace elegant', 'diamond ring closeup'],
      product: ['jewelry product shot', 'ring isolated black', 'necklace on white'],
      lifestyle: ['woman wearing jewelry', 'jewelry on model', 'luxury lifestyle'],
      team: ['jeweler craftsman', 'gemologist working', 'jewelry designer'],
      workspace: ['jewelry store interior', 'jeweller workshop', 'luxury boutique'],
      detail: ['diamond facet macro', 'gold texture closeup', 'gemstone detail'],
    },
    fontPairing: 'Cormorant Garamond + Inter',
  },
  {
    id: 'books',
    nameEn: 'Books & Stationery',
    nameFa: 'کتاب و لوازم‌التحریر',
    group: 'E-commerce',
    groupFa: 'فروشگاهی',
    keywords: ['book', 'کتاب', 'bookstore', 'کتابفروشی', 'stationery', 'لوازم‌التحریر', 'notebook', 'دفتر', 'publisher', 'نشر'],
    subIndustries: [
      { id: 'fiction', nameEn: 'Fiction', nameFa: 'داستانی', keywords: ['fiction', 'novel', 'رمان', 'داستان', 'fiction'] },
      { id: 'academic', nameEn: 'Academic', nameFa: 'درسی و دانشگاهی', keywords: ['academic', 'درسی', 'دانشگاهی', 'textbook', 'university'] },
      { id: 'children', nameEn: "Children's Books", nameFa: 'کتاب کودک', keywords: ['children', 'کودک', 'kids book', 'picture book'] },
      { id: 'stationery', nameEn: 'Stationery', nameFa: 'لوازم‌التحریر', keywords: ['stationery', 'لوازم‌التحریر', 'pen', 'خودکار', 'notebook', 'دفتر'] },
    ],
    palette: {
      light: { bg: '#FDF6E3', surface: '#FFFFFF', accent: '#7C2D12', text: '#1C1917', muted: '#78716C' },
      dark: { bg: '#1C1917', surface: '#292524', accent: '#FCD34D', text: '#FAFAF7', muted: '#A8A29E' },
    },
    suggestedSections: ['hero', 'bestsellers', 'new-releases', 'categories', 'author-spotlight', 'reading-lists', 'reviews', 'newsletter', 'footer'],
    sampleProducts: ['Mystery Novel Bestseller', 'Cookbook Mediterranean', 'Children Picture Book', 'Academic Textbook Physics', 'Leather Journal A5', 'Fountain Pen Matte Black', 'Art Print Set', 'Poetry Collection'],
    imageSearchKeywords: {
      hero: ['books banner cozy', 'library aesthetic', 'reading nook banner'],
      product: ['book cover product', 'notebook flatlay', 'book stack white'],
      lifestyle: ['person reading book', 'coffee and book', 'cozy reading scene'],
      team: ['author portrait', 'bookstore owner', 'writer at desk'],
      workspace: ['bookstore interior', 'library shelves', 'bookshop cozy'],
      detail: ['book page texture', 'pen writing closeup', 'book spine stack'],
    },
    fontPairing: 'Playfair Display + Lora',
  },
  {
    id: 'sports',
    nameEn: 'Sports & Outdoors',
    nameFa: 'ورزشی و خارج از خانه',
    group: 'E-commerce',
    groupFa: 'فروشگاهی',
    keywords: ['sport', 'ورزشی', 'fitness', 'تمرین', 'gym', 'outdoor', 'کوهنوردی', 'camping', 'کلیمینگ', 'bicycle', 'دوچرخه', 'sporting goods'],
    subIndustries: [
      { id: 'fitness', nameEn: 'Fitness Equipment', nameFa: 'تجهیزات تناسب اندام', keywords: ['fitness', 'تناسب', 'gym', 'دوچرخه ثابت', 'treadmill'] },
      { id: 'outdoor', nameEn: 'Outdoor & Camping', nameFa: 'کوهنوردی و کمپینگ', keywords: ['outdoor', 'کوهنوردی', 'camping', 'کمپ', 'hiking', 'trekking'] },
      { id: 'cycling', nameEn: 'Cycling', nameFa: 'دوچرخه', keywords: ['cycling', 'دوچرخه', 'bike', 'bicycle'] },
      { id: 'climbing', nameEn: 'Climbing', nameFa: 'صعود و کلیمینگ', keywords: ['climbing', 'کلیمینگ', 'صعود', 'bouldering'] },
      { id: 'team-sports', nameEn: 'Team Sports', nameFa: 'ورزش‌های تیمی', keywords: ['football', 'فوتبال', 'soccer', 'basketball', 'بسکتبال'] },
    ],
    palette: {
      light: { bg: '#F0FDF4', surface: '#FFFFFF', accent: '#15803D', text: '#14532D', muted: '#6B7280' },
      dark: { bg: '#0A1F12', surface: '#102818', accent: '#4ADE80', text: '#F0FDF4', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'category-cards', 'featured-gear', 'brand-spotlight', 'sizing-guide', 'gear-reviews', 'expert-tips', 'newsletter', 'footer'],
    sampleProducts: ['Trail Running Shoes', 'Carbon Road Bike', 'Climbing Harness Pro', 'Yoga Mat Eco 6mm', 'Camping Tent 4-Person', 'Adjustable Dumbbell Set', 'Hiking Backpack 60L', 'Smart Fitness Watch'],
    imageSearchKeywords: {
      hero: ['sports gear banner', 'outdoor adventure hero', 'fitness equipment flatlay'],
      product: ['running shoe product', 'yoga mat isolated', 'dumbbell product shot'],
      lifestyle: ['athlete training outdoor', 'hiker mountain trail', 'cyclist road'],
      team: ['athlete portrait', 'personal trainer', 'sports coach'],
      workspace: ['sporting goods store', 'fitness shop interior', 'outdoor gear shop'],
      detail: ['shoe sole texture', 'bike chain closeup', 'fabric weave detail'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'toys',
    nameEn: 'Toys & Kids',
    nameFa: 'اسباب‌بازی و کودک',
    group: 'E-commerce',
    groupFa: 'فروشگاهی',
    keywords: ['toy', 'اسباب‌بازی', 'kids', 'کودک', 'children', 'بچگانه', 'game', 'بازی', 'puzzle', 'پازل', 'doll', 'عروسک'],
    subIndustries: [
      { id: 'infant', nameEn: 'Infant 0-2', nameFa: 'نوزاد ۰-۲', keywords: ['infant', 'نوزاد', 'baby', 'بچه'] },
      { id: 'preschool', nameEn: 'Preschool 3-5', nameFa: 'پیش‌دبستانی ۳-۵', keywords: ['preschool', 'پیش‌دبستانی', 'toddler'] },
      { id: 'school-age', nameEn: 'School Age 6+', nameFa: 'مدرسه ۶+', keywords: ['school', 'مدرسه', 'kid', 'بچه'] },
      { id: 'educational', nameEn: 'Educational', nameFa: 'آموزشی', keywords: ['educational', 'آموزشی', 'stem', 'learning'] },
    ],
    palette: {
      light: { bg: '#FEF3C7', surface: '#FFFFFF', accent: '#7C3AED', text: '#1E1B4B', muted: '#6B7280' },
      dark: { bg: '#1E1B2E', surface: '#2A2440', accent: '#A78BFA', text: '#FEF3C7', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'age-categories', 'featured-toys', 'educational-zone', 'gift-ideas', 'safety-info', 'reviews', 'newsletter', 'footer'],
    sampleProducts: ['Wooden Building Blocks 100pc', 'STEM Robot Kit', 'Plush Bear 30cm', 'Art Supplies Set', 'Puzzle 500 pieces', 'Remote Car RC', 'Doll House Wooden', 'Board Game Family'],
    imageSearchKeywords: {
      hero: ['colorful toys banner', 'kids playing happy', 'playroom bright'],
      product: ['toy product shot', 'plush toy isolated', 'wooden toy flatlay'],
      lifestyle: ['child playing toy', 'kids building blocks', 'family game night'],
      team: ['toy designer working', 'preschool teacher', 'craftsman wooden toys'],
      workspace: ['toy store interior', 'kids shop colorful', 'playroom design'],
      detail: ['toy texture closeup', 'wooden block detail', 'plush fabric macro'],
    },
    fontPairing: 'Quicksand + Nunito',
  },
  {
    id: 'pet-supplies',
    nameEn: 'Pet Supplies',
    nameFa: 'لوازم حیوانات خانگی',
    group: 'E-commerce',
    groupFa: 'فروشگاهی',
    keywords: ['pet', 'حیوان', 'pet supplies', 'pet store', 'سگ', 'گربه', 'dog', 'cat', 'animal', 'پت شاپ', 'pet shop'],
    subIndustries: [
      { id: 'dog', nameEn: 'Dog', nameFa: 'سگ', keywords: ['dog', 'سگ', 'puppy', 'توله سگ'] },
      { id: 'cat', nameEn: 'Cat', nameFa: 'گربه', keywords: ['cat', 'گربه', 'kitten', 'گربه بچه'] },
      { id: 'fish', nameEn: 'Fish & Aquarium', nameFa: 'ماهی و آکواریوم', keywords: ['fish', 'ماهی', 'aquarium', 'آکواریوم'] },
      { id: 'bird', nameEn: 'Bird', nameFa: 'پرنده', keywords: ['bird', 'پرنده', 'parrot', 'طوطی'] },
    ],
    palette: {
      light: { bg: '#F0FDFA', surface: '#FFFFFF', accent: '#0D9488', text: '#134E4A', muted: '#6B7280' },
      dark: { bg: '#042F2E', surface: '#0A3F3C', accent: '#2DD4BF', text: '#F0FDFA', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'shop-by-pet', 'featured-products', 'nutrition-guide', 'care-tips', 'adoption-stories', 'reviews', 'newsletter', 'footer'],
    sampleProducts: ['Premium Dog Food 5kg', 'Cat Tree Tower 150cm', 'Aquarium Starter Kit', 'Dog Bed Orthopedic', 'Cat Litter Clumping 10L', 'Bird Cage Large', 'Dog Leash Retractable', 'Fish Food Flakes 100g'],
    imageSearchKeywords: {
      hero: ['pet supplies banner', 'happy dog cat', 'pet shop hero'],
      product: ['dog food product', 'cat toy isolated', 'pet bowl product'],
      lifestyle: ['dog playing outdoor', 'cat in cozy home', 'pet and owner'],
      team: ['veterinarian portrait', 'pet groomer working', 'pet shop staff'],
      workspace: ['pet store interior', 'veterinary clinic', 'pet grooming salon'],
      detail: ['pet fur texture', 'dog nose closeup', 'cat paw macro'],
    },
    fontPairing: 'Quicksand + Nunito',
  },
  {
    id: 'automotive-parts',
    nameEn: 'Auto Parts & Accessories',
    nameFa: 'لوازم یدکی و خودرو',
    group: 'E-commerce',
    groupFa: 'فروشگاهی',
    keywords: ['auto parts', 'لوازم یدکی', 'car parts', 'خودرو', 'automotive', 'تایر', 'tire', 'engine', 'موتر', 'car accessories', 'لوازم خودرو'],
    subIndustries: [
      { id: 'engine', nameEn: 'Engine Parts', nameFa: 'قطعات موتور', keywords: ['engine', 'موتور', 'motor'] },
      { id: 'tires', nameEn: 'Tires & Wheels', nameFa: 'تایر و رینگ', keywords: ['tire', 'تایر', 'wheel', 'رینگ'] },
      { id: 'body', nameEn: 'Body Parts', nameFa: 'بدنه', keywords: ['body', 'بدنه', 'bumper', 'spoiler'] },
      { id: 'accessories', nameEn: 'Accessories', nameFa: 'اکسسوری', keywords: ['accessory', 'اکسسوری', 'cover', 'seat'] },
      { id: 'oils', nameEn: 'Oils & Fluids', nameFa: 'روغن و مایعات', keywords: ['oil', 'روغن', 'fluid', 'lubricant'] },
    ],
    palette: {
      light: { bg: '#F8FAFC', surface: '#FFFFFF', accent: '#DC2626', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0F172A', surface: '#1E293B', accent: '#F87171', text: '#F8FAFC', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'category-grid', 'brand-strip', 'featured-parts', 'fitment-guide', 'compatibility-checker', 'reviews', 'newsletter', 'footer'],
    sampleProducts: ['Brake Pad Set Ceramic', 'Engine Oil 5W-30 5L', 'Air Filter Performance', 'Spark Plug Iridium 4pc', 'Headlight LED Projector', 'Car Battery 70Ah', 'Alloy Wheel 18 inch', 'Wiper Blade Set'],
    imageSearchKeywords: {
      hero: ['auto parts banner', 'car engine bay', 'mechanic workshop'],
      product: ['car part product', 'brake pad isolated', 'engine oil bottle'],
      lifestyle: ['mechanic working car', 'garage interior', 'car repair'],
      team: ['mechanic portrait', 'auto technician', 'car specialist'],
      workspace: ['auto parts store', 'workshop garage', 'mechanic shop'],
      detail: ['engine closeup', 'tire tread macro', 'metal part detail'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'plant-nursery',
    nameEn: 'Plants & Garden',
    nameFa: 'گل و گیاه و باغچه',
    group: 'E-commerce',
    groupFa: 'فروشگاهی',
    keywords: ['plant', 'گل', 'گیاه', 'garden', 'باغچه', 'nursery', 'گلخانه', 'flower', 'flower shop', 'گلفروشی', 'indoor plant', 'houseplant'],
    subIndustries: [
      { id: 'indoor', nameEn: 'Indoor Plants', nameFa: 'گیاه آپارتمانی', keywords: ['indoor', 'آپارتمانی', 'houseplant', 'inside'] },
      { id: 'outdoor', nameEn: 'Outdoor & Garden', nameFa: 'باغچه و بیرونی', keywords: ['outdoor', 'بیرونی', 'garden', 'باغچه'] },
      { id: 'seeds', nameEn: 'Seeds & Bulbs', nameFa: 'بذر و پیاز', keywords: ['seed', 'بذر', 'bulb', 'پیاز'] },
      { id: 'tools', nameEn: 'Garden Tools', nameFa: 'ابزار باغچه', keywords: ['tool', 'ابزار', 'shovel', 'بیل'] },
    ],
    palette: {
      light: { bg: '#F7FEE7', surface: '#FFFFFF', accent: '#65A30D', text: '#1A2E05', muted: '#6B7280' },
      dark: { bg: '#0A1A05', surface: '#14240D', accent: '#A3E635', text: '#F7FEE7', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'shop-by-type', 'featured-plants', 'care-guides', 'seasonal-picks', 'plant-care-tips', 'reviews', 'newsletter', 'footer'],
    sampleProducts: ['Monstera Deliciosa Large', 'Snake Plant Sansevieria', 'Fiddle Leaf Fig 5ft', 'Succulent Collection 6-pc', 'Ceramic Planter White', 'Organic Potting Soil 20L', 'Pruning Shears Pro', 'Herb Garden Kit'],
    imageSearchKeywords: {
      hero: ['plants banner green', 'garden nursery hero', 'indoor plants collection'],
      product: ['potted plant product', 'succulent isolated', 'houseplant white pot'],
      lifestyle: ['plant in living room', 'indoor garden home', 'plant on shelf'],
      team: ['gardener working', 'plant shop owner', 'florist arranging'],
      workspace: ['plant nursery interior', 'garden center shop', 'greenhouse interior'],
      detail: ['leaf texture macro', 'soil closeup', 'flower petal detail'],
    },
    fontPairing: 'Cormorant Garamond + Inter',
  },
  {
    id: 'generic-ecommerce',
    nameEn: 'General E-commerce',
    nameFa: 'فروشگاه عمومی',
    group: 'E-commerce',
    groupFa: 'فروشگاهی',
    keywords: ['shop', 'store', 'فروشگاه', 'آنلاین شاپ', 'online shop', 'ecommerce', 'store', 'خرید'],
    subIndustries: [],
    palette: {
      light: { bg: '#FFFFFF', surface: '#F8FAFC', accent: '#7C3AED', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0F172A', surface: '#1E293B', accent: '#A78BFA', text: '#F8FAFC', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'categories', 'featured', 'bestsellers', 'sale', 'newsletter', 'footer'],
    sampleProducts: ['Premium Product 1', 'Featured Item 2', 'Bestseller 3', 'New Arrival 4', 'Sale Item 5'],
    imageSearchKeywords: {
      hero: ['online shop banner', 'ecommerce hero', 'shopping flatlay'],
      product: ['product photo white', 'boxed product', 'consumer goods'],
      lifestyle: ['shopping lifestyle', 'happy customer', 'unboxing'],
      team: ['shop owner', 'customer service team', 'warehouse staff'],
      workspace: ['modern store', 'warehouse logistics', 'office team'],
      detail: ['product texture', 'material closeup', 'packaging detail'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
];
