import type { IndustryMeta } from './types';

// ─── Food & Beverage industries ───────────────────────────────────────────
// 5 industries: restaurant, cafe, bakery, fast-food, bar-pub

export const FOOD_INDUSTRIES: IndustryMeta[] = [
  {
    id: 'restaurant',
    nameEn: 'Restaurant',
    nameFa: 'رستوران',
    group: 'Food & Beverage',
    groupFa: 'غذا و نوشیدنی',
    keywords: ['restaurant', 'رستوران', 'fine dining', 'dining', 'شام', 'ناهار', 'restaurant menu', 'chef', 'آشپزخانه'],
    subIndustries: [
      { id: 'italian', nameEn: 'Italian', nameFa: 'ایتالیایی', keywords: ['italian', 'ایتالیایی', 'pasta', 'پاستا', 'pizza'] },
      { id: 'asian', nameEn: 'Asian', nameFa: 'آسیایی', keywords: ['asian', 'آسیایی', 'sushi', 'سوشی', 'chinese', 'چینی'] },
      { id: 'mediterranean', nameEn: 'Mediterranean', nameFa: 'مدیترانه‌ای', keywords: ['mediterranean', 'مدیترانه', 'greek', 'lebanese', 'لبنانی'] },
      { id: 'steakhouse', nameEn: 'Steakhouse', nameFa: 'استیک هاوس', keywords: ['steak', 'استیک', 'grill', 'باربیکیو'] },
      { id: 'vegetarian', nameEn: 'Vegetarian & Vegan', nameFa: 'گیاهی و وگان', keywords: ['vegetarian', 'گیاهی', 'vegan', 'وگان', 'plant based'] },
    ],
    palette: {
      light: { bg: '#FFFBEB', surface: '#FFFFFF', accent: '#B91C1C', text: '#451A03', muted: '#78716C' },
      dark: { bg: '#1C1410', surface: '#2A2018', accent: '#F59E0B', text: '#FFFBEB', muted: '#A8A29E' },
    },
    suggestedSections: ['hero', 'about-chef', 'signature-dishes', 'full-menu', 'reservation', 'gallery', 'testimonials', 'location-hours', 'footer'],
    sampleProducts: ['Truffle Risotto', 'Wagyu Ribeye Steak', 'Margherita Pizza DOP', 'Pan-Seared Salmon', 'Tiramisu Classico', 'Lamb Osso Buco', 'Caesar Salad', 'Crème Brûlée'],
    imageSearchKeywords: {
      hero: ['restaurant interior elegant', 'fine dining table', 'restaurant ambiance'],
      product: ['gourmet plate food', 'fine dining dish', 'chef plating food'],
      lifestyle: ['friends dining restaurant', 'couple romantic dinner', 'wine pairing'],
      team: ['chef portrait kitchen', 'sous chef working', 'restaurant staff team'],
      workspace: ['restaurant kitchen', 'fine dining room', 'bar area restaurant'],
      detail: ['food garnish closeup', 'wine glass detail', 'plate texture macro'],
    },
    fontPairing: 'Playfair Display + Inter',
  },
  {
    id: 'cafe',
    nameEn: 'Café & Coffee Shop',
    nameFa: 'کافه و قهوه‌خانه',
    group: 'Food & Beverage',
    groupFa: 'غذا و نوشیدنی',
    keywords: ['cafe', 'کافه', 'coffee', 'قهوه', 'coffee shop', 'barista', 'بارиста', 'espresso', 'اسپرسو', 'cappuccino', 'کاپوچینو'],
    subIndustries: [
      { id: 'specialty-coffee', nameEn: 'Specialty Coffee', nameFa: 'اسپشیالتی', keywords: ['specialty', 'اسپشیالتی', 'third wave', 'single origin'] },
      { id: 'breakfast', nameEn: 'Breakfast & Brunch', nameFa: 'صبحانه و برانچ', keywords: ['breakfast', 'صبحانه', 'brunch', 'برانچ'] },
      { id: 'dessert', nameEn: 'Dessert Café', nameFa: 'کافه دسر', keywords: ['dessert', 'دسر', 'cake', 'کیک', 'pastry'] },
      { id: 'study-cafe', nameEn: 'Study & Work Café', nameFa: 'کافه مطالعه', keywords: ['study', 'مطالعه', 'work', 'کار', 'coworking'] },
    ],
    palette: {
      light: { bg: '#FAF6F0', surface: '#FFFFFF', accent: '#92400E', text: '#1C1917', muted: '#78716C' },
      dark: { bg: '#1C1410', surface: '#2A2018', accent: '#D6A065', text: '#FAF6F0', muted: '#A8A29E' },
    },
    suggestedSections: ['hero', 'coffee-menu', 'signature-drinks', 'breakfast-menu', 'gallery', 'events', 'about-roastery', 'location-hours', 'footer'],
    sampleProducts: ['Single Origin Pour Over', 'Flat White Oat Milk', 'Cold Brew Tonic', 'Avocado Toast Sourdough', 'Almond Croissant', 'Matcha Latte', 'Affogato Espresso', 'Banana Bread Slice'],
    imageSearchKeywords: {
      hero: ['coffee shop interior cozy', 'barista pouring latte', 'cafe atmosphere'],
      product: ['coffee cup latte art', 'croissant isolated', 'coffee bag product'],
      lifestyle: ['person working cafe', 'friends coffee chat', 'morning coffee ritual'],
      team: ['barista portrait apron', 'cafe owner working', 'coffee roaster'],
      workspace: ['coffee shop counter', 'cafe interior wood', 'espresso machine bar'],
      detail: ['latte art closeup', 'coffee beans macro', 'pastry texture detail'],
    },
    fontPairing: 'Playfair Display + Inter',
  },
  {
    id: 'bakery',
    nameEn: 'Bakery & Patisserie',
    nameFa: 'نانوایی و شیرینی‌پزی',
    group: 'Food & Beverage',
    groupFa: 'غذا و نوشیدنی',
    keywords: ['bakery', 'نانوایی', 'patisserie', 'شیرینی‌پزی', 'bread', 'نان', 'cake', 'کیک', 'pastry', 'شیرینی', 'cookie', 'کلوچه'],
    subIndustries: [
      { id: 'bread', nameEn: 'Artisan Bread', nameFa: 'نان سنتی', keywords: ['bread', 'نان', 'sourdough', 'سوردو', 'baguette'] },
      { id: 'pastry', nameEn: 'Pastries', nameFa: 'شیرینی', keywords: ['pastry', 'شیرینی', 'croissant', 'کراسان', 'danish'] },
      { id: 'cake', nameEn: 'Cakes & Desserts', nameFa: 'کیک و دسر', keywords: ['cake', 'کیک', 'dessert', 'دسر', 'tart'] },
      { id: 'persian-sweets', nameEn: 'Persian Sweets', nameFa: 'شیرینی ایرانی', keywords: ['persian', 'ایرانی', 'سوهان', 'باقلوا', 'نبات', 'گز'] },
    ],
    palette: {
      light: { bg: '#FEF3C7', surface: '#FFFFFF', accent: '#B45309', text: '#451A03', muted: '#78716C' },
      dark: { bg: '#1F1410', surface: '#2A2018', accent: '#FBBF24', text: '#FEF3C7', muted: '#A8A29E' },
    },
    suggestedSections: ['hero', 'daily-bread', 'signature-pastries', 'custom-cakes', 'about-baker', 'gallery', 'order-custom', 'location-hours', 'footer'],
    sampleProducts: ['Sourdough Boule 800g', 'Butter Croissant', 'Pain au Chocolat', 'Cinnamon Roll', 'Lemon Tart', 'Red Velvet Cake Slice', 'Sourdough Baguette', 'Almond Danish'],
    imageSearchKeywords: {
      hero: ['bakery display case', 'fresh bread banner', 'pastry shop interior'],
      product: ['croissant isolated white', 'bread loaf product', 'cake slice photo'],
      lifestyle: ['person eating croissant', 'bread on cutting board', 'morning breakfast spread'],
      team: ['baker portrait apron', 'pastry chef working', 'bread artisan'],
      workspace: ['bakery kitchen interior', 'pastry workshop', 'bread oven bakery'],
      detail: ['bread crust texture', 'pastry layers closeup', 'cake frosting detail'],
    },
    fontPairing: 'Playfair Display + Inter',
  },
  {
    id: 'fast-food',
    nameEn: 'Fast Food & Takeaway',
    nameFa: 'فست‌فود و تحویلی',
    group: 'Food & Beverage',
    groupFa: 'غذا و نوشیدنی',
    keywords: ['fast food', 'فست‌فود', 'فست فود', 'takeaway', 'تحویلی', 'burger', 'برگر', 'pizza delivery', 'پیتزا', 'kebab', 'کباب'],
    subIndustries: [
      { id: 'burger', nameEn: 'Burger Joint', nameFa: 'برگر', keywords: ['burger', 'برگر', 'hamburger', 'همبرگر'] },
      { id: 'pizza', nameEn: 'Pizza', nameFa: 'پیتزا', keywords: ['pizza', 'پیتزا', 'pizza delivery'] },
      { id: 'kebab', nameEn: 'Kebab & Grill', nameFa: 'کباب و گریل', keywords: ['kebab', 'کباب', 'grill', 'گریل'] },
      { id: 'fried-chicken', nameEn: 'Fried Chicken', nameFa: 'مرغ سوخاری', keywords: ['chicken', 'مرغ', 'fried', 'سوخاری'] },
      { id: 'sandwich', nameEn: 'Sandwich & Sub', nameFa: 'ساندویچ', keywords: ['sandwich', 'ساندویچ', 'sub', 'panini'] },
    ],
    palette: {
      light: { bg: '#FFF7ED', surface: '#FFFFFF', accent: '#EA580C', text: '#431407', muted: '#78716C' },
      dark: { bg: '#1F1006', surface: '#2A1808', accent: '#FB923C', text: '#FFF7ED', muted: '#A8A29E' },
    },
    suggestedSections: ['hero', 'combo-deals', 'menu-categories', 'signature-items', 'delivery-info', 'order-online', 'reviews', 'location-hours', 'footer'],
    sampleProducts: ['Double Cheeseburger Combo', 'Pepperoni Pizza Large', 'Crispy Chicken Bucket 8pc', 'Beef Kebab Plate', 'Philly Cheesesteak Sub', 'Loaded Fries', 'Milkshake Chocolate', 'Chicken Wrap Meal'],
    imageSearchKeywords: {
      hero: ['fast food banner', 'burger pizza hero', 'food delivery'],
      product: ['burger product shot', 'pizza isolated', 'fried chicken box'],
      lifestyle: ['people eating fast food', 'food delivery bag', 'family pizza night'],
      team: ['fast food cook', 'kitchen staff team', 'delivery person'],
      workspace: ['fast food counter', 'kitchen interior', 'food truck'],
      detail: ['burger texture closeup', 'pizza cheese pull', 'fries macro'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'bar-pub',
    nameEn: 'Bar & Pub',
    nameFa: 'بار و کافه شبانه',
    group: 'Food & Beverage',
    groupFa: 'غذا و نوشیدنی',
    keywords: ['bar', 'بار', 'pub', 'کافه شبانه', 'cocktail', 'کوکتل', 'wine bar', 'بار شراب', 'craft beer', 'watering hole'],
    subIndustries: [
      { id: 'cocktail', nameEn: 'Cocktail Bar', nameFa: 'بار کوکتل', keywords: ['cocktail', 'کوکتل', 'mixology'] },
      { id: 'wine', nameEn: 'Wine Bar', nameFa: 'بار شراب', keywords: ['wine', 'شراب', 'tasting'] },
      { id: 'craft-beer', nameEn: 'Craft Beer', nameFa: 'آبجوی دست‌ساز', keywords: ['beer', 'آبجو', 'craft', 'brewery'] },
      { id: 'whiskey', nameEn: 'Whiskey Lounge', nameFa: 'ویسکی‌بار', keywords: ['whiskey', 'ویسکی', 'lounge'] },
    ],
    palette: {
      light: { bg: '#1C1410', surface: '#2A2018', accent: '#92400E', text: '#FFFBEB', muted: '#A8A29E' },
      dark: { bg: '#0A0604', surface: '#1A1310', accent: '#F59E0B', text: '#FFFBEB', muted: '#94837A' },
    },
    suggestedSections: ['hero', 'signature-cocktails', 'drink-menu', 'small-plates', 'events-calendar', 'gallery', 'reservation', 'location-hours', 'footer'],
    sampleProducts: ['Old Fashioned Classic', 'Negroni Cocktail', 'Margarita Premium', 'Whiskey Flight 3pc', 'Craft IPA Pint', 'Wine Tasting Flight', 'Charcuterie Board', 'Truffle Fries'],
    imageSearchKeywords: {
      hero: ['cocktail bar interior', 'dark moody bar atmosphere', 'bartender pouring'],
      product: ['cocktail glass product', 'whiskey bottle shot', 'beer glass isolated'],
      lifestyle: ['people enjoying drinks', 'friends at bar', 'date night cocktail'],
      team: ['bartender portrait', 'mixologist working', 'sommelier wine'],
      workspace: ['bar counter interior', 'cocktail bar design', 'wine cellar'],
      detail: ['cocktail garnish closeup', 'ice in glass macro', 'whiskey barrel detail'],
    },
    fontPairing: 'Playfair Display + Inter',
  },
];
