import type { IndustryMeta } from './types';

// ─── Industrial, Personal & Misc industries ───────────────────────────────
// 10 industries.

export const MISC_INDUSTRIES: IndustryMeta[] = [
  {
    id: 'construction',
    nameEn: 'Construction & Contracting',
    nameFa: 'ساخت‌وساز و پیمانکاری',
    group: 'Industrial',
    groupFa: 'صنعتی',
    keywords: ['construction', 'ساخت‌وساز', 'contractor', 'پیمانکار', 'building', 'ساختمان', 'builder', 'سازنده', 'renovation', 'بازسازی'],
    subIndustries: [
      { id: 'residential-construction', nameEn: 'Residential Construction', nameFa: 'مسکونی', keywords: ['residential', 'مسکونی', 'home building'] },
      { id: 'commercial-construction', nameEn: 'Commercial Construction', nameFa: 'تجاری', keywords: ['commercial', 'تجاری'] },
      { id: 'renovation', nameEn: 'Renovation & Remodeling', nameFa: 'بازسازی', keywords: ['renovation', 'بازسازی', 'remodel'] },
      { id: 'infrastructure', nameEn: 'Infrastructure', nameFa: 'زیرساخت', keywords: ['infrastructure', 'زیرساخت', 'civil'] },
      { id: 'specialty-trade', nameEn: 'Specialty Trades', nameFa: 'تخصصی', keywords: ['specialty', 'تخصصی', 'trade', 'plumbing', 'لوله‌کشی'] },
    ],
    palette: {
      light: { bg: '#F8FAFC', surface: '#FFFFFF', accent: '#EA580C', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0F172A', surface: '#1E293B', accent: '#FB923C', text: '#F8FAFC', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'services', 'project-portfolio', 'process', 'team', 'safety-quality', 'testimonials', 'free-quote', 'footer'],
    sampleProducts: ['Custom Home Build', 'Commercial Build-Out', 'Kitchen Renovation', 'Bathroom Remodel', 'Home Addition', 'Roofing Project', 'Foundation Repair', 'Full House Renovation'],
    imageSearchKeywords: {
      hero: ['construction site banner', 'modern building under construction', 'construction worker hero'],
      product: ['construction equipment', 'building materials', 'tools product'],
      lifestyle: ['construction worker lifestyle', 'site safety', 'builder working'],
      team: ['construction worker portrait', 'contractor professional', 'construction team'],
      workspace: ['construction site', 'building frame', 'modern construction project'],
      detail: ['brick wall texture', 'concrete closeup', 'steel beam detail'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'manufacturing',
    nameEn: 'Manufacturing',
    nameFa: 'تولید و تولیدی',
    group: 'Industrial',
    groupFa: 'صنعتی',
    keywords: ['manufacturing', 'تولید', 'factory', 'کارخانه', 'production', 'تولیدی', 'manufacturer', 'تولیدکننده', 'industrial'],
    subIndustries: [
      { id: 'food-mfg', nameEn: 'Food Manufacturing', nameFa: 'مواد غذایی', keywords: ['food', 'غذا', 'beverage'] },
      { id: 'textile-mfg', nameEn: 'Textile & Apparel', nameFa: 'نساجی', keywords: ['textile', 'نساجی', 'fabric'] },
      { id: 'metal-mfg', nameEn: 'Metal & Machining', nameFa: 'فلز', keywords: ['metal', 'فلز', 'machining'] },
      { id: 'plastic-mfg', nameEn: 'Plastic & Polymer', nameFa: 'پلاستیک', keywords: ['plastic', 'پلاستیک', 'polymer'] },
      { id: 'electronics-mfg', nameEn: 'Electronics Manufacturing', nameFa: 'الکترونیک', keywords: ['electronics', 'الکترونیک'] },
    ],
    palette: {
      light: { bg: '#F1F5F9', surface: '#FFFFFF', accent: '#0F766E', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0A0F1A', surface: '#131A2B', accent: '#2DD4BF', text: '#F1F5F9', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'capabilities', 'industries-served', 'quality-certifications', 'facility-tour', 'case-studies', 'team', 'request-quote', 'footer'],
    sampleProducts: ['CNC Machining Service', 'Custom Plastic Molding', 'Metal Fabrication', 'PCB Assembly', 'Textile Production', 'Food Packaging Run', 'Quality Testing Service', 'Prototyping Service'],
    imageSearchKeywords: {
      hero: ['factory production line', 'manufacturing facility banner', 'modern factory interior'],
      product: ['industrial product photo', 'machinery isolated', 'manufactured parts'],
      lifestyle: ['factory worker lifestyle', 'production team working', 'modern manufacturing'],
      team: ['manufacturing engineer portrait', 'factory worker team', 'production manager'],
      workspace: ['factory floor interior', 'production line', 'warehouse industrial'],
      detail: ['machine closeup macro', 'metal surface texture', 'circuit detail'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'logistics',
    nameEn: 'Logistics & Shipping',
    nameFa: 'لجستیک و حمل‌ونقل',
    group: 'Industrial',
    groupFa: 'صنعتی',
    keywords: ['logistics', 'لجستیک', 'shipping', 'حمل‌ونقل', 'freight', 'بار', 'warehouse', 'انبار', 'courier', 'پیک', 'delivery', 'تحویل', 'transport'],
    subIndustries: [
      { id: 'freight', nameEn: 'Freight & Cargo', nameFa: 'باربری', keywords: ['freight', 'باربری', 'cargo'] },
      { id: 'courier', nameEn: 'Courier & Last-Mile', nameFa: 'پیک', keywords: ['courier', 'پیک', 'last-mile'] },
      { id: 'warehouse', nameEn: 'Warehousing', nameFa: 'انبارداری', keywords: ['warehouse', 'انبار'] },
      { id: 'international', nameEn: 'International Shipping', nameFa: 'بین‌المللی', keywords: ['international', 'بین‌المللی'] },
      { id: 'cold-chain', nameEn: 'Cold Chain', nameFa: 'زنجیره سرد', keywords: ['cold', 'سرد', 'refrigerated'] },
    ],
    palette: {
      light: { bg: '#F0F9FF', surface: '#FFFFFF', accent: '#1E40AF', text: '#0C4A6E', muted: '#64748B' },
      dark: { bg: '#0C1A2A', surface: '#13293F', accent: '#3B82F6', text: '#F0F9FF', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'services', 'coverage-map', 'tracking', 'pricing', 'industries-served', 'fleet', 'request-quote', 'footer'],
    sampleProducts: ['Standard Parcel Delivery', 'Express Next-Day', 'Freight Truck Load', 'International Air Cargo', 'Cold Chain Logistics', 'Warehouse Storage', 'E-commerce Fulfillment', 'Same-Day Local'],
    imageSearchKeywords: {
      hero: ['logistics warehouse banner', 'shipping trucks highway', 'cargo port aerial'],
      product: ['shipping container isolated', 'cardboard box product', 'pallet wrapped'],
      lifestyle: ['delivery person lifestyle', 'warehouse worker team', 'logistics professional'],
      team: ['logistics manager portrait', 'warehouse team', 'delivery driver uniform'],
      workspace: ['warehouse interior modern', 'distribution center', 'loading dock'],
      detail: ['cardboard box closeup', 'shipping label detail', 'pallet texture'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'automotive-dealer',
    nameEn: 'Car Dealership',
    nameFa: 'نمایشگاه خودرو',
    group: 'Industrial',
    groupFa: 'صنعتی',
    keywords: ['car dealership', 'نمایشگاه خودرو', 'auto dealer', 'dealer خودرو', 'cars for sale', 'فروش خودرو', 'used cars', 'خودرو دست‌دوم', 'new cars', 'خودرو نو'],
    subIndustries: [
      { id: 'new-cars', nameEn: 'New Cars', nameFa: 'نو', keywords: ['new', 'نو', 'new cars'] },
      { id: 'used-cars', nameEn: 'Used Cars', nameFa: 'دست‌دوم', keywords: ['used', 'دست‌دوم', 'preowned'] },
      { id: 'luxury-cars', nameEn: 'Luxury & Exotic', nameFa: 'لوکس', keywords: ['luxury', 'لوکس', 'exotic'] },
      { id: 'electric', nameEn: 'Electric Vehicles', nameFa: 'الکتریکی', keywords: ['electric', 'الکتریکی', 'ev', 'tesla'] },
      { id: 'motorcycle', nameEn: 'Motorcycles', nameFa: 'موتورسیکلت', keywords: ['motorcycle', 'موتور', 'bike'] },
    ],
    palette: {
      light: { bg: '#F8FAFC', surface: '#FFFFFF', accent: '#DC2626', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0A0A0A', surface: '#171717', accent: '#EF4444', text: '#FAFAFA', muted: '#9CA3AF' },
    },
    suggestedSections: ['hero', 'inventory', 'brand-categories', 'financing', 'service-center', 'trade-in', 'test-drive', 'special-offers', 'footer'],
    sampleProducts: ['New Sedan 2024', 'Used SUV 2021', 'Luxury Coupe Sport', 'Electric Hatchback', 'Pickup Truck 4x4', 'Convertible Roadster', 'Family Minivan', 'Motorcycle Cruiser'],
    imageSearchKeywords: {
      hero: ['car dealership showroom', 'luxury cars display', 'modern car dealer'],
      product: ['car exterior photo', 'luxury car isolated', 'vehicle product shot'],
      lifestyle: ['person with new car', 'family in car', 'customer test drive'],
      team: ['salesperson portrait professional', 'dealership team', 'car salesman'],
      workspace: ['modern showroom interior', 'car dealership lot', 'service center'],
      detail: ['car wheel closeup', 'car interior detail', 'headlight macro'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  // ── Personal & Misc ──
  {
    id: 'portfolio',
    nameEn: 'Personal Portfolio',
    nameFa: 'نمونه‌کار شخصی',
    group: 'Personal',
    groupFa: 'شخصی',
    keywords: ['portfolio', 'نمونه‌کار', 'personal', 'شخصی', 'resume', 'رزومه', 'cv', 'personal site', 'وب‌سایت شخصی', 'freelancer'],
    subIndustries: [
      { id: 'developer-portfolio', nameEn: 'Developer Portfolio', nameFa: 'برنامه‌نویس', keywords: ['developer', 'برنامه‌نویس', 'engineer'] },
      { id: 'designer-portfolio', nameEn: 'Designer Portfolio', nameFa: 'طراح', keywords: ['designer', 'طراح'] },
      { id: 'writer-portfolio', nameEn: 'Writer / Author', nameFa: 'نویسنده', keywords: ['writer', 'نویسنده', 'author'] },
      { id: 'consultant-portfolio', nameEn: 'Consultant', nameFa: 'مشاور', keywords: ['consultant', 'مشاور'] },
      { id: 'student-portfolio', nameEn: 'Student / Academic', nameFa: 'دانشجو', keywords: ['student', 'دانشجو'] },
    ],
    palette: {
      light: { bg: '#FFFFFF', surface: '#F8FAFC', accent: '#7C3AED', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0A0A0A', surface: '#161616', accent: '#A78BFA', text: '#FAFAFA', muted: '#9CA3AF' },
    },
    suggestedSections: ['hero', 'about-me', 'skills', 'projects', 'experience', 'education', 'testimonials', 'blog', 'contact', 'footer'],
    sampleProducts: ['Project Case Study', 'Service Offering', 'Consultation 1hr', 'Course Creation', 'Speaking Engagement', 'Freelance Project', 'Workshop Hosting', 'Mentorship 4-week'],
    imageSearchKeywords: {
      hero: ['professional workspace desk', 'creative person working', 'modern office banner'],
      product: ['project mockup', 'laptop with work', 'design showcase'],
      lifestyle: ['professional lifestyle', 'creative working cafe', 'remote work'],
      team: ['professional headshot portrait', 'person working laptop', 'creative professional'],
      workspace: ['minimal home office', 'designer workspace', 'developer setup'],
      detail: ['laptop screen detail', 'keyboard closeup', 'desk accessories macro'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'blog',
    nameEn: 'Blog / Magazine',
    nameFa: 'بلاگ و مجله',
    group: 'Personal',
    groupFa: 'شخصی',
    keywords: ['blog', 'بلاگ', 'وبلاگ', 'magazine', 'مجله', 'news', 'اخبار', 'publication', 'نشریه', 'online magazine'],
    subIndustries: [
      { id: 'personal-blog', nameEn: 'Personal Blog', nameFa: 'شخصی', keywords: ['personal', 'شخصی'] },
      { id: 'tech-magazine', nameEn: 'Tech Magazine', nameFa: 'فناوری', keywords: ['tech', 'فناوری', 'technology'] },
      { id: 'lifestyle-magazine', nameEn: 'Lifestyle Magazine', nameFa: 'سبک زندگی', keywords: ['lifestyle', 'سبک زندگی'] },
      { id: 'news-magazine', nameEn: 'News', nameFa: 'اخبار', keywords: ['news', 'اخبار'] },
      { id: 'food-blog', nameEn: 'Food Blog', nameFa: 'غذا', keywords: ['food', 'غذا', 'recipe'] },
    ],
    palette: {
      light: { bg: '#FFFBEB', surface: '#FFFFFF', accent: '#B45309', text: '#451A03', muted: '#78716C' },
      dark: { bg: '#1C1410', surface: '#2A2018', accent: '#FBBF24', text: '#FFFBEB', muted: '#A8A29E' },
    },
    suggestedSections: ['hero', 'featured-articles', 'categories', 'recent-posts', 'newsletter', 'about-author', 'popular-tags', 'archive', 'footer'],
    sampleProducts: ['Weekly Newsletter', 'Premium Subscription', 'E-book Bundle', 'Online Course', 'Print Magazine Issue', 'Membership Tier', 'Ad-free Experience', 'Exclusive Content'],
    imageSearchKeywords: {
      hero: ['blog writing workspace', 'magazine cover design', 'writer at desk'],
      product: ['magazine product', 'book on table', 'ebook on tablet'],
      lifestyle: ['writer lifestyle', 'reading magazine', 'coffee and book'],
      team: ['blogger portrait', 'writer professional', 'editor working'],
      workspace: ['home office writing', 'minimal desk setup', 'creative writing space'],
      detail: ['laptop writing closeup', 'pen on paper macro', 'book page detail'],
    },
    fontPairing: 'Playfair Display + Lora',
  },
  {
    id: 'wedding',
    nameEn: 'Wedding Services',
    nameFa: 'خدمات عروسی',
    group: 'Events',
    groupFa: 'رویدادها',
    keywords: ['wedding', 'عروسی', 'bridal', 'داماد', 'عروس', 'wedding venue', 'مکان عروسی', 'wedding planner', 'مجری عروسی', 'wedding photography'],
    subIndustries: [
      { id: 'wedding-venue', nameEn: 'Wedding Venue', nameFa: 'مکان', keywords: ['venue', 'مکان'] },
      { id: 'wedding-photographer', nameEn: 'Wedding Photography', nameFa: 'عکاسی', keywords: ['photographer', 'عکاسی'] },
      { id: 'wedding-florist', nameEn: 'Wedding Florist', nameFa: 'گل‌آرایی', keywords: ['florist', 'گل', 'flowers'] },
      { id: 'wedding-catering', nameEn: 'Wedding Catering', nameFa: 'پذیرایی', keywords: ['catering', 'پذیرایی'] },
      { id: 'wedding-dress', nameEn: 'Bridal Fashion', nameFa: 'لباس عروس', keywords: ['dress', 'لباس', 'bridal'] },
    ],
    palette: {
      light: { bg: '#FDF2F8', surface: '#FFFFFF', accent: '#BE185D', text: '#500724', muted: '#9D8B96' },
      dark: { bg: '#1A0F18', surface: '#261822', accent: '#F472B6', text: '#FDF2F8', muted: '#A78AA0' },
    },
    suggestedSections: ['hero', 'services', 'packages', 'gallery', 'real-weddings', 'testimonials', 'vendor-team', 'inquiry', 'footer'],
    sampleProducts: ['All-Inclusive Wedding Package', 'Venue Rental 200 guests', 'Photography 10hr', 'Floral Design Premium', 'Catering 5-course', 'Bridal Gown Designer', 'Wedding Cake Custom', 'Honeymoon Planning'],
    imageSearchKeywords: {
      hero: ['elegant wedding decoration', 'bridal bouquet hero', 'wedding venue beautiful'],
      product: ['wedding ring product', 'bridal bouquet', 'wedding cake'],
      lifestyle: ['happy couple wedding', 'bride and groom', 'wedding celebration'],
      team: ['wedding planner portrait', 'florist professional', 'photographer creative'],
      workspace: ['wedding venue interior', 'florist workshop', 'bridal boutique'],
      detail: ['wedding ring closeup', 'bouquet flower macro', 'lace fabric detail'],
    },
    fontPairing: 'Cormorant Garamond + Inter',
  },
  {
    id: 'veterinary',
    nameEn: 'Veterinary Clinic',
    nameFa: 'کلینیک دامپزشکی',
    group: 'Health & Wellness',
    groupFa: 'سلامت و درمان',
    keywords: ['veterinary', 'دامپزشکی', 'vet', 'دامپزشک', 'animal hospital', 'بیمارستان حیوانات', 'pet clinic', 'کلینیک حیوانات', 'animal care'],
    subIndustries: [
      { id: 'small-animal', nameEn: 'Small Animals', nameFa: 'حیوانات کوچک', keywords: ['small', 'کوچک', 'dog', 'cat'] },
      { id: 'large-animal', nameEn: 'Large Animals', nameFa: 'حیوانات بزرگ', keywords: ['large', 'بزرگ', 'horse', 'cow'] },
      { id: 'exotic', nameEn: 'Exotic Pets', nameFa: 'اکزوتیک', keywords: ['exotic', 'اکزوتیک', 'bird', 'reptile'] },
      { id: 'emergency-vet', nameEn: 'Emergency Care', nameFa: 'اورژانس', keywords: ['emergency', 'اورژانس', '24hr'] },
      { id: 'surgery', nameEn: 'Surgery', nameFa: 'جراحی', keywords: ['surgery', 'جراحی'] },
    ],
    palette: {
      light: { bg: '#F0F9FF', surface: '#FFFFFF', accent: '#0D9488', text: '#134E4A', muted: '#64748B' },
      dark: { bg: '#042F2E', surface: '#0A3F3C', accent: '#2DD4BF', text: '#F0F9FF', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'services', 'team', 'facilities', 'emergency-info', 'pricing', 'resources', 'booking', 'footer'],
    sampleProducts: ['Annual Wellness Exam', 'Vaccination Package', 'Dental Cleaning', 'Spay/Neuter Surgery', 'Emergency Visit', 'Microchipping', 'Health Certificate', 'Telemedicine Consult'],
    imageSearchKeywords: {
      hero: ['veterinary clinic modern', 'vet with pet', 'animal hospital banner'],
      product: ['pet medicine product', 'pet care supplies', 'vet instrument'],
      lifestyle: ['happy pet and owner', 'pet lifestyle', 'veterinary care'],
      team: ['veterinarian portrait', 'vet tech team', 'animal care specialist'],
      workspace: ['veterinary clinic interior', 'examination room', 'modern animal hospital'],
      detail: ['cat paw macro', 'dog nose closeup', 'stethoscope detail'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'nonprofit',
    nameEn: 'Non-Profit / Charity',
    nameFa: 'سازمان مردم‌نهاد',
    group: 'Community',
    groupFa: 'اجتماعی',
    keywords: ['nonprofit', 'مردم‌نهاد', 'charity', 'خیریه', 'ngo', 'سازمان غیردولتی', 'foundation', 'بنیاد', 'cause', 'donation'],
    subIndustries: [
      { id: 'education-npo', nameEn: 'Education', nameFa: 'آموزش', keywords: ['education', 'آموزش'] },
      { id: 'health-npo', nameEn: 'Health', nameFa: 'سلامت', keywords: ['health', 'سلامت', 'medical'] },
      { id: 'environment-npo', nameEn: 'Environment', nameFa: 'محیط زیست', keywords: ['environment', 'محیط زیست'] },
      { id: 'humanitarian', nameEn: 'Humanitarian', nameFa: 'بشردوستانه', keywords: ['humanitarian', 'بشردوستانه', 'relief'] },
      { id: 'animal-npo', nameEn: 'Animal Welfare', nameFa: 'رفاه حیوانات', keywords: ['animal', 'حیوانات'] },
    ],
    palette: {
      light: { bg: '#F0FDF4', surface: '#FFFFFF', accent: '#15803D', text: '#14532D', muted: '#6B7280' },
      dark: { bg: '#0A1F12', surface: '#102818', accent: '#4ADE80', text: '#F0FDF4', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'mission', 'programs', 'impact-stats', 'get-involved', 'donate', 'volunteer', 'news-events', 'footer'],
    sampleProducts: ['One-time Donation', 'Monthly Giving $25', 'Sponsor a Child', 'Volunteer Program', 'Corporate Partnership', 'Legacy Giving', 'In-Kind Donation', 'Event Sponsorship'],
    imageSearchKeywords: {
      hero: ['volunteers helping community', 'charity work banner', 'nonprofit impact'],
      product: ['donation campaign', 'charity brochure', 'impact report'],
      lifestyle: ['volunteers working together', 'community service lifestyle', 'charity event'],
      team: ['nonprofit staff portrait', 'volunteer team', 'charity founder'],
      workspace: ['nonprofit office interior', 'community center', 'volunteer space'],
      detail: ['hands helping closeup', 'donation jar detail', 'community handshake macro'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'generic-business',
    nameEn: 'Generic Business',
    nameFa: 'کسب‌وکار عمومی',
    group: 'Other',
    groupFa: 'سایر',
    keywords: ['business', 'کسب‌وکار', 'company', 'شرکت', 'corporate', 'organization', 'سازمان'],
    subIndustries: [],
    palette: {
      light: { bg: '#FFFFFF', surface: '#F8FAFC', accent: '#0F172A', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0A0A0A', surface: '#171717', accent: '#FAFAFA', text: '#FAFAFA', muted: '#9CA3AF' },
    },
    suggestedSections: ['hero', 'about', 'services', 'team', 'testimonials', 'contact', 'footer'],
    sampleProducts: ['Core Service 1', 'Core Service 2', 'Core Service 3', 'Premium Package', 'Basic Plan', 'Consultation'],
    imageSearchKeywords: {
      hero: ['modern business office', 'corporate team meeting', 'professional business banner'],
      product: ['business product photo', 'service showcase', 'office supplies'],
      lifestyle: ['business professional lifestyle', 'office work lifestyle', 'meeting professional'],
      team: ['business team portrait', 'corporate professional', 'office team'],
      workspace: ['modern office interior', 'business workspace', 'corporate meeting room'],
      detail: ['office supplies closeup', 'laptop screen detail', 'business card macro'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
];
