import type { IndustryMeta } from './types';

// ─── Services, Health & Professional industries ───────────────────────────
// 14 industries.

export const SERVICES_INDUSTRIES: IndustryMeta[] = [
  // ── Health & Wellness ──
  {
    id: 'medical-clinic',
    nameEn: 'Medical Clinic',
    nameFa: 'کلینیک پزشکی',
    group: 'Health & Wellness',
    groupFa: 'سلامت و درمان',
    keywords: ['medical', 'پزشکی', 'clinic', 'کلینیک', 'doctor', 'پزشک', 'دکتر', 'healthcare', 'درمان', 'hospital', 'بیمارستان', 'physician'],
    subIndustries: [
      { id: 'general', nameEn: 'General Practice', nameFa: 'عمومی', keywords: ['general', 'عمومی', 'family', 'خانواده'] },
      { id: 'pediatric', nameEn: 'Pediatric', nameFa: 'اطفال', keywords: ['pediatric', 'اطفال', 'children', 'کودک'] },
      { id: 'cardiology', nameEn: 'Cardiology', nameFa: 'قلب', keywords: ['cardio', 'قلب', 'cardiac'] },
      { id: 'dermatology', nameEn: 'Dermatology', nameFa: 'پوست', keywords: ['derma', 'پوست', 'skin'] },
      { id: 'orthopedic', nameEn: 'Orthopedic', nameFa: 'استخوان', keywords: ['orthopedic', 'استخوان', 'bone'] },
    ],
    palette: {
      light: { bg: '#F0F9FF', surface: '#FFFFFF', accent: '#0284C7', text: '#0C4A6E', muted: '#64748B' },
      dark: { bg: '#0C1A2A', surface: '#13293F', accent: '#38BDF8', text: '#F0F9FF', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'services', 'specialists', 'booking', 'insurance', 'patient-resources', 'testimonials', 'location-hours', 'footer'],
    sampleProducts: ['General Consultation', 'Annual Physical Exam', 'Vaccination Service', 'Lab Test Package', 'ECG Heart Check', 'Skin Cancer Screening', 'Travel Health Advice', 'Telemedicine Visit'],
    imageSearchKeywords: {
      hero: ['modern medical clinic', 'doctor with patient', 'healthcare banner'],
      product: ['medical equipment', 'stethoscope isolated', 'medicine bottle'],
      lifestyle: ['patient consultation', 'healthy lifestyle', 'family doctor visit'],
      team: ['doctor portrait white coat', 'nurse team', 'medical specialist'],
      workspace: ['clinic reception', 'examination room', 'modern hospital interior'],
      detail: ['medical instrument closeup', 'ecg heart detail', 'pill capsule macro'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'dental',
    nameEn: 'Dental Clinic',
    nameFa: 'کلینیک دندانپزشکی',
    group: 'Health & Wellness',
    groupFa: 'سلامت و درمان',
    keywords: ['dental', 'دندانپزشکی', 'dentist', 'دندانپزشک', 'teeth', 'دندان', 'orthodontics', 'ارتودنسی', 'dental clinic'],
    subIndustries: [
      { id: 'general-dental', nameEn: 'General Dentistry', nameFa: 'عمومی', keywords: ['general', 'عمومی'] },
      { id: 'orthodontics', nameEn: 'Orthodontics', nameFa: 'ارتودنسی', keywords: ['orthodontics', 'ارتودنسی', 'braces', 'الیگنسر'] },
      { id: 'cosmetic', nameEn: 'Cosmetic Dentistry', nameFa: 'زیبایی', keywords: ['cosmetic', 'زیبایی', 'veneer', 'ونیر', 'whitening'] },
      { id: 'pediatric-dental', nameEn: 'Pediatric Dentistry', nameFa: 'اطفال', keywords: ['pediatric', 'اطفال', 'kids dental'] },
      { id: 'implant', nameEn: 'Implant Surgery', nameFa: 'ایمپلنت', keywords: ['implant', 'ایمپلنت', 'surgery'] },
    ],
    palette: {
      light: { bg: '#F0FDFA', surface: '#FFFFFF', accent: '#0D9488', text: '#134E4A', muted: '#64748B' },
      dark: { bg: '#042F2E', surface: '#0A3F3C', accent: '#2DD4BF', text: '#F0FDFA', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'services', 'treatments', 'before-after', 'specialists', 'booking', 'insurance', 'testimonials', 'footer'],
    sampleProducts: ['Routine Cleaning', 'Teeth Whitening', 'Porcelain Veneers', 'Invisalign Treatment', 'Dental Implant', 'Root Canal Therapy', 'Wisdom Tooth Extraction', 'Pediatric Check-up'],
    imageSearchKeywords: {
      hero: ['modern dental clinic', 'smiling patient dentist', 'dental office bright'],
      product: ['dental tool product', 'tooth model', 'invisalign tray'],
      lifestyle: ['person smiling white teeth', 'healthy smile lifestyle', 'family dental visit'],
      team: ['dentist portrait', 'dental hygienist', 'dental team staff'],
      workspace: ['dental office interior', 'treatment room', 'dental chair modern'],
      detail: ['tooth closeup', 'dental instrument macro', 'smile teeth detail'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'fitness-gym',
    nameEn: 'Fitness & Gym',
    nameFa: 'باشگاه ورزشی',
    group: 'Health & Wellness',
    groupFa: 'سلامت و درمان',
    keywords: ['fitness', 'تناسب اندام', 'gym', 'باشگاه', 'workout', 'تمرین', 'bodybuilding', 'بدنسازی', 'crossfit', 'کراس‌فیت', 'health club'],
    subIndustries: [
      { id: 'strength', nameEn: 'Strength Training', nameFa: 'وزنه‌برداری', keywords: ['strength', 'وزنه', 'bodybuilding', 'بدنسازی'] },
      { id: 'crossfit', nameEn: 'CrossFit', nameFa: 'کراس‌فیت', keywords: ['crossfit', 'کراس‌فیت'] },
      { id: 'group-fitness', nameEn: 'Group Classes', nameFa: 'کلاس گروهی', keywords: ['group', 'گروهی', 'class', 'کلاس'] },
      { id: 'personal-training', nameEn: 'Personal Training', nameFa: 'مربی شخصی', keywords: ['personal', 'شخصی', 'trainer', 'مربی'] },
    ],
    palette: {
      light: { bg: '#FFFFFF', surface: '#F8FAFC', accent: '#DC2626', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0A0A0A', surface: '#171717', accent: '#EF4444', text: '#FAFAFA', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'classes', 'trainers', 'membership-plans', 'schedule', 'gallery', 'testimonials', 'free-trial', 'footer'],
    sampleProducts: ['Monthly Membership', 'Annual Premium', 'Personal Training 10-pack', 'Group Class Pass', 'CrossFit Unlimited', 'Nutrition Coaching', 'Recovery Sauna Pass', 'Couple Membership'],
    imageSearchKeywords: {
      hero: ['gym interior banner', 'athlete working out', 'fitness motivation dark'],
      product: ['dumbbell product', 'kettlebell isolated', 'yoga mat product'],
      lifestyle: ['person exercising gym', 'workout lifestyle', 'fitness athlete training'],
      team: ['personal trainer portrait', 'fitness coach working', 'gym instructor'],
      workspace: ['modern gym interior', 'fitness studio', 'weight room gym'],
      detail: ['dumbbell closeup macro', 'muscle definition detail', 'sweat drop texture'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'yoga-spa',
    nameEn: 'Yoga & Spa',
    nameFa: 'یوگا و اسپا',
    group: 'Health & Wellness',
    groupFa: 'سلامت و درمان',
    keywords: ['yoga', 'یوگا', 'spa', 'اسپا', 'meditation', 'مدیتیشن', 'wellness', 'سلامت روان', 'massage', 'ماساژ', 'wellness retreat'],
    subIndustries: [
      { id: 'yoga', nameEn: 'Yoga Studio', nameFa: 'استودیو یوگا', keywords: ['yoga', 'یوگا'] },
      { id: 'meditation', nameEn: 'Meditation', nameFa: 'مدیتیشن', keywords: ['meditation', 'مدیتیشن', 'mindfulness'] },
      { id: 'spa-massage', nameEn: 'Spa & Massage', nameFa: 'اسپا و ماساژ', keywords: ['spa', 'اسپا', 'massage', 'ماساژ'] },
      { id: 'wellness-retreat', nameEn: 'Wellness Retreat', nameFa: 'مرکز سلامت', keywords: ['retreat', 'مرکز سلامت', 'wellness'] },
    ],
    palette: {
      light: { bg: '#F0FDF4', surface: '#FFFFFF', accent: '#15803D', text: '#14532D', muted: '#6B7280' },
      dark: { bg: '#0A1F12', surface: '#102818', accent: '#4ADE80', text: '#F0FDF4', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'class-schedule', 'instructors', 'membership', 'private-sessions', 'wellness-blog', 'gallery', 'booking', 'footer'],
    sampleProducts: ['Drop-in Class', '10-Class Pack', 'Monthly Unlimited', 'Private Yoga Session', 'Couples Massage 60min', 'Hot Stone Therapy', 'Sound Bath Meditation', 'Wellness Day Retreat'],
    imageSearchKeywords: {
      hero: ['yoga studio peaceful', 'meditation banner calm', 'spa wellness hero'],
      product: ['yoga mat product', 'essential oil bottle', 'candle spa product'],
      lifestyle: ['woman doing yoga', 'meditation lifestyle', 'spa relaxation'],
      team: ['yoga instructor portrait', 'massage therapist', 'wellness coach'],
      workspace: ['yoga studio interior', 'spa treatment room', 'meditation hall'],
      detail: ['candle flame closeup', 'yoga pose detail', 'spa stone texture'],
    },
    fontPairing: 'Cormorant Garamond + Inter',
  },
  {
    id: 'mental-health',
    nameEn: 'Mental Health Therapy',
    nameFa: 'روان‌درمانی',
    group: 'Health & Wellness',
    groupFa: 'سلامت و درمان',
    keywords: ['mental health', 'سلامت روان', 'therapy', 'درمان', 'psychology', 'روان‌شناسی', 'counseling', 'مشاوره', 'psychiatrist', 'روان‌پزشک', 'therapist', 'تراپیست'],
    subIndustries: [
      { id: 'individual', nameEn: 'Individual Therapy', nameFa: 'فردی', keywords: ['individual', 'فردی', 'personal'] },
      { id: 'couples', nameEn: 'Couples Therapy', nameFa: 'زوج‌درمانی', keywords: ['couples', 'زوج', 'marriage'] },
      { id: 'family', nameEn: 'Family Therapy', nameFa: 'خانواده', keywords: ['family', 'خانواده'] },
      { id: 'child', nameEn: 'Child & Adolescent', nameFa: 'کودک و نوجوان', keywords: ['child', 'کودک', 'teen', 'نوجوان'] },
      { id: 'group-therapy', nameEn: 'Group Therapy', nameFa: 'گروهی', keywords: ['group', 'گروهی'] },
    ],
    palette: {
      light: { bg: '#F5F3FF', surface: '#FFFFFF', accent: '#6D28D9', text: '#2E1065', muted: '#6B7280' },
      dark: { bg: '#1A1033', surface: '#251847', accent: '#A78BFA', text: '#F5F3FF', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'services', 'therapists', 'approach', 'insurance-pricing', 'resources', 'faq', 'booking', 'footer'],
    sampleProducts: ['Initial Consultation 60min', 'Individual Therapy 50min', 'Couples Session 75min', 'Family Therapy 90min', 'Psychiatry Evaluation', 'Group Therapy 8-week', 'Online Therapy Session', 'Crisis Support'],
    imageSearchKeywords: {
      hero: ['therapy office calm', 'peaceful counseling room', 'mental wellness'],
      product: ['journal notebook', 'meditation cushion', 'self-care book'],
      lifestyle: ['person meditating calm', 'peaceful morning routine', 'journaling lifestyle'],
      team: ['therapist portrait warm', 'counselor professional', 'psychologist friendly'],
      workspace: ['therapy office interior', 'counseling room cozy', 'private practice'],
      detail: ['hands writing journal', 'tea cup steam detail', 'plant leaf texture'],
    },
    fontPairing: 'Cormorant Garamond + Inter',
  },
  {
    id: 'pharmacy',
    nameEn: 'Pharmacy',
    nameFa: 'داروخانه',
    group: 'Health & Wellness',
    groupFa: 'سلامت و درمان',
    keywords: ['pharmacy', 'داروخانه', 'drugstore', 'medicine', 'دارو', 'prescription', 'نسخه', 'pharmacist', 'داروساز'],
    subIndustries: [
      { id: 'general-pharmacy', nameEn: 'General Pharmacy', nameFa: 'عمومی', keywords: ['general', 'عمومی'] },
      { id: 'compounding', nameEn: 'Compounding', nameFa: 'ترکیبی', keywords: ['compounding', 'ترکیبی', 'custom'] },
      { id: 'specialty', nameEn: 'Specialty Pharmacy', nameFa: 'تخصصی', keywords: ['specialty', 'تخصصی'] },
      { id: 'online-pharmacy', nameEn: 'Online Pharmacy', nameFa: 'آنلاین', keywords: ['online', 'آنلاین', 'delivery'] },
    ],
    palette: {
      light: { bg: '#F0F9FF', surface: '#FFFFFF', accent: '#0284C7', text: '#0C4A6E', muted: '#64748B' },
      dark: { bg: '#0C1A2A', surface: '#13293F', accent: '#38BDF8', text: '#F0F9FF', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'services', 'prescription-refill', 'health-products', 'consultation', 'delivery', 'insurance', 'contact', 'footer'],
    sampleProducts: ['Prescription Refill', 'Vitamin Supplements', 'First Aid Kit', 'Blood Pressure Monitor', 'Diabetic Supplies', 'Flu Vaccination', 'Medication Review', 'Home Delivery Service'],
    imageSearchKeywords: {
      hero: ['modern pharmacy interior', 'pharmacist consultation', 'medicine counter'],
      product: ['medicine bottle product', 'pill bottle isolated', 'vitamin supplement'],
      lifestyle: ['person taking medicine', 'healthy lifestyle', 'family wellness'],
      team: ['pharmacist portrait', 'pharmacy staff team', 'lab coat professional'],
      workspace: ['pharmacy counter interior', 'medicine shelves', 'compounding lab'],
      detail: ['pill capsule macro', 'medicine label closeup', 'pharmacy glass detail'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  // ── Professional Services ──
  {
    id: 'law-firm',
    nameEn: 'Law Firm',
    nameFa: 'دفتر وکالت',
    group: 'Professional Services',
    groupFa: 'خدمات حرفه‌ای',
    keywords: ['law firm', 'وکالت', 'lawyer', 'وکیل', 'attorney', 'legal', 'حقوقی', 'legal services', 'consultation legal'],
    subIndustries: [
      { id: 'corporate', nameEn: 'Corporate Law', nameFa: 'حقوق شرکت‌ها', keywords: ['corporate', 'شرکت', 'business law'] },
      { id: 'family', nameEn: 'Family Law', nameFa: 'خانواده', keywords: ['family', 'خانواده', 'divorce', 'طلاق'] },
      { id: 'criminal', nameEn: 'Criminal Defense', nameFa: 'کیفری', keywords: ['criminal', 'کیفری', 'defense'] },
      { id: 'immigration', nameEn: 'Immigration', nameFa: 'مهاجرت', keywords: ['immigration', 'مهاجرت', 'visa'] },
      { id: 'intellectual', nameEn: 'Intellectual Property', nameFa: 'مالکیت معنوی', keywords: ['ip', 'مالکیت', 'patent', 'اختراع', 'trademark'] },
    ],
    palette: {
      light: { bg: '#F8FAFC', surface: '#FFFFFF', accent: '#1E40AF', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0F172A', surface: '#1E293B', accent: '#3B82F6', text: '#F8FAFC', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'practice-areas', 'attorneys', 'case-results', 'client-testimonials', 'insights', 'consultation', 'contact', 'footer'],
    sampleProducts: ['Initial Consultation 60min', 'Contract Review', 'Corporate Formation', 'Estate Planning Package', 'Personal Injury Case', 'Family Law Matter', 'IP Filing Service', 'Court Representation'],
    imageSearchKeywords: {
      hero: ['law firm office elegant', 'lawyer library books', 'legal justice'],
      product: ['legal document stack', 'law book isolated', 'gavel product'],
      lifestyle: ['business meeting professional', 'signing contract', 'corporate office'],
      team: ['lawyer portrait suit', 'attorney professional', 'legal team office'],
      workspace: ['law office interior', 'library bookshelf', 'conference room'],
      detail: ['scales of justice', 'legal document closeup', 'gavel detail'],
    },
    fontPairing: 'Playfair Display + Inter',
  },
  {
    id: 'accounting',
    nameEn: 'Accounting & Tax',
    nameFa: 'حسابداری و مالیاتی',
    group: 'Professional Services',
    groupFa: 'خدمات حرفه‌ای',
    keywords: ['accounting', 'حسابداری', 'tax', 'مالیاتی', 'cpa', 'bookkeeping', 'حسابداری مالیاتی', 'audit', 'حسابرسی', 'financial services', 'مالی'],
    subIndustries: [
      { id: 'tax', nameEn: 'Tax Services', nameFa: 'مالیاتی', keywords: ['tax', 'مالیات'] },
      { id: 'audit', nameEn: 'Audit', nameFa: 'حسابرسی', keywords: ['audit', 'حسابرسی'] },
      { id: 'advisory', nameEn: 'Financial Advisory', nameFa: 'مشاوره مالی', keywords: ['advisory', 'مشاوره', 'financial'] },
      { id: 'bookkeeping', nameEn: 'Bookkeeping', nameFa: 'دفترداری', keywords: ['bookkeeping', 'دفترداری'] },
    ],
    palette: {
      light: { bg: '#F0FDF4', surface: '#FFFFFF', accent: '#15803D', text: '#14532D', muted: '#6B7280' },
      dark: { bg: '#0A1F12', surface: '#102818', accent: '#22C55E', text: '#F0FDF4', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'services', 'industries-served', 'team', 'resources', 'pricing', 'free-consultation', 'contact', 'footer'],
    sampleProducts: ['Annual Tax Filing', 'Monthly Bookkeeping', 'Audit Service', 'Payroll Management', 'Business Formation', 'Financial Statement Prep', 'Tax Planning Strategy', 'CFO Advisory'],
    imageSearchKeywords: {
      hero: ['accounting office modern', 'financial charts banner', 'business calculator'],
      product: ['calculator product', 'financial report document', 'laptop spreadsheet'],
      lifestyle: ['business meeting finance', 'professional working office', 'planning budget'],
      team: ['accountant portrait professional', 'cpa working desk', 'financial advisor'],
      workspace: ['modern office interior', 'accounting workspace', 'finance department'],
      detail: ['calculator closeup', 'spreadsheet screen detail', 'coins money macro'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'consulting',
    nameEn: 'Business Consulting',
    nameFa: 'مشاوره کسب‌وکار',
    group: 'Professional Services',
    groupFa: 'خدمات حرفه‌ای',
    keywords: ['consulting', 'مشاوره', 'business consultant', 'مشاور کسب‌وکار', 'management', 'مدیریت', 'strategy', 'استراتژی', 'advisory'],
    subIndustries: [
      { id: 'strategy', nameEn: 'Strategy', nameFa: 'استراتژی', keywords: ['strategy', 'استراتژی'] },
      { id: 'operations', nameEn: 'Operations', nameFa: 'عملیات', keywords: ['operations', 'عملیات'] },
      { id: 'marketing', nameEn: 'Marketing', nameFa: 'بازاریابی', keywords: ['marketing', 'بازاریابی'] },
      { id: 'hr', nameEn: 'HR Consulting', nameFa: 'منابع انسانی', keywords: ['hr', 'منابع انسانی', 'human'] },
      { id: 'digital', nameEn: 'Digital Transformation', nameFa: 'تحول دیجیتال', keywords: ['digital', 'دیجیتال', 'transformation'] },
    ],
    palette: {
      light: { bg: '#FFFFFF', surface: '#F8FAFC', accent: '#7C3AED', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0F172A', surface: '#1E293B', accent: '#A78BFA', text: '#F8FAFC', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'services', 'case-studies', 'methodology', 'team', 'insights', 'engagement-model', 'contact', 'footer'],
    sampleProducts: ['Strategy Assessment 4-week', 'Market Research Project', 'Operational Audit', 'Growth Strategy Workshop', 'Digital Transformation Roadmap', 'Brand Workshop', 'Executive Coaching 6-month', 'Implementation Sprint'],
    imageSearchKeywords: {
      hero: ['business strategy meeting', 'consulting whiteboard', 'corporate brainstorm'],
      product: ['business report document', 'laptop strategy', 'whiteboard plan'],
      lifestyle: ['business team planning', 'executive presentation', 'strategy session'],
      team: ['consultant portrait', 'business advisor professional', 'strategy expert'],
      workspace: ['modern consulting office', 'meeting room glass', 'coworking space'],
      detail: ['whiteboard diagram closeup', 'laptop screen charts', 'sticky notes plan'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'real-estate',
    nameEn: 'Real Estate',
    nameFa: 'املاک',
    group: 'Professional Services',
    groupFa: 'خدمات حرفه‌ای',
    keywords: ['real estate', 'املاک', 'property', 'ملک', 'realtor', 'مشاور املاک', 'real estate agent', 'house for sale', 'خانه فروش', 'apartment', 'آپارتمان'],
    subIndustries: [
      { id: 'residential', nameEn: 'Residential', nameFa: 'مسکونی', keywords: ['residential', 'مسکونی', 'house', 'خانه'] },
      { id: 'commercial', nameEn: 'Commercial', nameFa: 'تجاری', keywords: ['commercial', 'تجاری', 'office'] },
      { id: 'luxury', nameEn: 'Luxury Properties', nameFa: 'لوکس', keywords: ['luxury', 'لوکس', 'mansion'] },
      { id: 'rental', nameEn: 'Rental', nameFa: 'اجاره', keywords: ['rental', 'اجاره', 'rent'] },
      { id: 'investment', nameEn: 'Investment Properties', nameFa: 'سرمایه‌گذاری', keywords: ['investment', 'سرمایه‌گذاری'] },
    ],
    palette: {
      light: { bg: '#FFFBEB', surface: '#FFFFFF', accent: '#B45309', text: '#451A03', muted: '#78716C' },
      dark: { bg: '#1C1410', surface: '#2A2018', accent: '#FBBF24', text: '#FFFBEB', muted: '#A8A29E' },
    },
    suggestedSections: ['hero', 'featured-listings', 'search-filter', 'neighborhood-guide', 'agent-profile', 'market-insights', 'testimonials', 'contact-agent', 'footer'],
    sampleProducts: ['3-Bedroom Family Home', 'Luxury Penthouse', 'Downtown Loft', 'Commercial Office Space', 'Beachfront Villa', 'Suburban Townhouse', 'Investment Duplex', 'Studio Apartment'],
    imageSearchKeywords: {
      hero: ['luxury house exterior', 'modern home real estate', 'property banner'],
      product: ['house exterior photo', 'apartment building', 'modern home front'],
      lifestyle: ['family in new home', 'moving into house', 'house keys handover'],
      team: ['real estate agent portrait', 'realtor professional', 'property consultant'],
      workspace: ['real estate office', 'modern home interior', 'property showroom'],
      detail: ['house key closeup', 'door handle detail', 'window architecture'],
    },
    fontPairing: 'Playfair Display + Inter',
  },
  {
    id: 'architecture',
    nameEn: 'Architecture & Interior Design',
    nameFa: 'معماری و طراحی داخلی',
    group: 'Professional Services',
    groupFa: 'خدمات حرفه‌ای',
    keywords: ['architecture', 'معماری', 'architect', 'معمار', 'interior design', 'طراحی داخلی', 'design studio', 'استودیو طراحی', 'building design', 'طراحی ساختمان'],
    subIndustries: [
      { id: 'residential-arch', nameEn: 'Residential Architecture', nameFa: 'مسکونی', keywords: ['residential', 'مسکونی', 'house design'] },
      { id: 'commercial-arch', nameEn: 'Commercial', nameFa: 'تجاری', keywords: ['commercial', 'تجاری', 'office building'] },
      { id: 'interior', nameEn: 'Interior Design', nameFa: 'داخلی', keywords: ['interior', 'داخلی', 'decor'] },
      { id: 'landscape', nameEn: 'Landscape Architecture', nameFa: 'محوطه‌سازی', keywords: ['landscape', 'محوطه', 'garden design'] },
      { id: 'urban', nameEn: 'Urban Planning', nameFa: 'شهرسازی', keywords: ['urban', 'شهرسازی', 'planning'] },
    ],
    palette: {
      light: { bg: '#FAFAF9', surface: '#FFFFFF', accent: '#1C1917', text: '#1C1917', muted: '#78716C' },
      dark: { bg: '#0C0A09', surface: '#1C1917', accent: '#FAFAF9', text: '#FAFAF9', muted: '#A8A29E' },
    },
    suggestedSections: ['hero', 'projects-portfolio', 'services', 'design-process', 'team', 'awards-press', 'testimonials', 'inquiry', 'footer'],
    sampleProducts: ['Residential Design Full Service', 'Commercial Architecture', 'Interior Design Package', 'Renovation Project', 'Landscape Design', 'Feasibility Study', '3D Visualization', 'Project Management'],
    imageSearchKeywords: {
      hero: ['modern architecture building', 'minimal interior design', 'architectural hero'],
      product: ['architectural model', 'blueprint drawing', '3d render interior'],
      lifestyle: ['people in modern space', 'architect lifestyle', 'design studio work'],
      team: ['architect portrait', 'designer working', 'interior designer'],
      workspace: ['architecture studio interior', 'design office', 'model making workshop'],
      detail: ['building facade detail', 'material texture closeup', 'blueprint line detail'],
    },
    fontPairing: 'Cormorant Garamond + Inter',
  },
  {
    id: 'photography',
    nameEn: 'Photography Studio',
    nameFa: 'استودیو عکاسی',
    group: 'Professional Services',
    groupFa: 'خدمات حرفه‌ای',
    keywords: ['photography', 'عکاسی', 'photographer', 'عکس', 'photo studio', 'استودیو عکاسی', 'wedding photography', 'عکاسی عروسی', 'portrait', 'پرتره'],
    subIndustries: [
      { id: 'wedding-photo', nameEn: 'Wedding Photography', nameFa: 'عروسی', keywords: ['wedding', 'عروسی', 'bridal'] },
      { id: 'portrait-photo', nameEn: 'Portrait', nameFa: 'پرتره', keywords: ['portrait', 'پرتره', 'headshot'] },
      { id: 'product-photo', nameEn: 'Product Photography', nameFa: 'محصول', keywords: ['product', 'محصول', 'commercial'] },
      { id: 'event-photo', nameEn: 'Event Photography', nameFa: 'رویداد', keywords: ['event', 'رویداد', 'corporate'] },
      { id: 'fine-art', nameEn: 'Fine Art Photography', nameFa: 'هنری', keywords: ['fine art', 'هنری', 'art'] },
    ],
    palette: {
      light: { bg: '#FFFFFF', surface: '#F8FAFC', accent: '#0F172A', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0A0A0A', surface: '#171717', accent: '#FAFAFA', text: '#FAFAFA', muted: '#9CA3AF' },
    },
    suggestedSections: ['hero', 'portfolio', 'services-packages', 'about-photographer', 'pricing', 'booking', 'testimonials', 'blog', 'footer'],
    sampleProducts: ['Wedding Day Package 8hr', 'Engagement Session 2hr', 'Family Portrait Session', 'Headshot Package 1hr', 'Product Photography 10pc', 'Event Coverage 4hr', 'Fine Art Print 24x36', 'Newborn Session'],
    imageSearchKeywords: {
      hero: ['photographer with camera', 'photography banner dark', 'camera lens closeup'],
      product: ['camera product photo', 'lens isolated', 'photo print'],
      lifestyle: ['photographer working', 'photoshoot lifestyle', 'behind the scenes'],
      team: ['photographer portrait', 'creative professional', 'studio owner'],
      workspace: ['photo studio interior', 'photography workspace', 'studio lighting setup'],
      detail: ['camera lens macro', 'film roll detail', 'photo print closeup'],
    },
    fontPairing: 'Cormorant Garamond + Inter',
  },
  {
    id: 'event-planning',
    nameEn: 'Event Planning',
    nameFa: 'برگزاری رویداد',
    group: 'Professional Services',
    groupFa: 'خدمات حرفه‌ای',
    keywords: ['event planning', 'برگزاری رویداد', 'event planner', 'مجری رویداد', 'wedding planner', 'مجری عروسی', 'corporate event', 'رویداد شرکتی', 'party planning'],
    subIndustries: [
      { id: 'wedding-event', nameEn: 'Weddings', nameFa: 'عروسی', keywords: ['wedding', 'عروسی'] },
      { id: 'corporate-event', nameEn: 'Corporate Events', nameFa: 'شرکتی', keywords: ['corporate', 'شرکتی', 'conference'] },
      { id: 'private-party', nameEn: 'Private Parties', nameFa: 'مهمانی خصوصی', keywords: ['private', 'خصوصی', 'party'] },
      { id: 'festival', nameEn: 'Festivals', nameFa: 'جشنواره', keywords: ['festival', 'جشنواره'] },
    ],
    palette: {
      light: { bg: '#FDF4FF', surface: '#FFFFFF', accent: '#A21CAF', text: '#3B0764', muted: '#6B7280' },
      dark: { bg: '#1A0B1F', surface: '#2A1330', accent: '#E879F9', text: '#FDF4FF', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'services', 'signature-events', 'gallery', 'packages', 'about-planner', 'testimonials', 'inquiry', 'footer'],
    sampleProducts: ['Full Wedding Planning', 'Day-of Coordination', 'Corporate Conference 200pax', 'Birthday Party 50pax', 'Anniversary Celebration', 'Product Launch Event', 'Galaxy Dinner Gala', 'Festival Production'],
    imageSearchKeywords: {
      hero: ['elegant event decoration', 'wedding venue decorated', 'event setup beautiful'],
      product: ['event centerpiece', 'floral arrangement', 'event table setting'],
      lifestyle: ['people at elegant event', 'wedding celebration', 'party lifestyle'],
      team: ['event planner portrait', 'coordinator working', 'planning team'],
      workspace: ['event venue interior', 'ballroom decorated', 'outdoor event setup'],
      detail: ['floral detail closeup', 'table setting macro', 'decorative element'],
    },
    fontPairing: 'Cormorant Garamond + Inter',
  },
  {
    id: 'cleaning-services',
    nameEn: 'Cleaning Services',
    nameFa: 'خدمات نظافت',
    group: 'Professional Services',
    groupFa: 'خدمات حرفه‌ای',
    keywords: ['cleaning', 'نظافت', 'cleaning service', 'خدمات نظافت', 'maid service', 'home cleaning', 'نظافت منزل', 'office cleaning', 'janitorial'],
    subIndustries: [
      { id: 'residential-clean', nameEn: 'Residential Cleaning', nameFa: 'مسکونی', keywords: ['residential', 'مسکونی', 'home'] },
      { id: 'commercial-clean', nameEn: 'Commercial Cleaning', nameFa: 'تجاری', keywords: ['commercial', 'تجاری', 'office'] },
      { id: 'deep-clean', nameEn: 'Deep Cleaning', nameFa: 'تعمیقی', keywords: ['deep', 'تعمیقی', 'spring clean'] },
      { id: 'post-construction', nameEn: 'Post-Construction', nameFa: 'پس از ساخت', keywords: ['post', 'پس از', 'construction'] },
    ],
    palette: {
      light: { bg: '#F0F9FF', surface: '#FFFFFF', accent: '#0EA5E9', text: '#0C4A6E', muted: '#64748B' },
      dark: { bg: '#0C1A2A', surface: '#13293F', accent: '#38BDF8', text: '#F0F9FF', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'services', 'pricing', 'booking', 'service-area', 'reviews', 'team', 'contact', 'footer'],
    sampleProducts: ['Weekly Home Cleaning', 'Deep Clean Service', 'Move-in Cleaning', 'Office Daily Service', 'Window Cleaning', 'Carpet Shampoo', 'Post-Construction Clean', 'Monthly Subscription'],
    imageSearchKeywords: {
      hero: ['clean modern home', 'cleaning service banner', 'spotless interior'],
      product: ['cleaning supplies', 'spray bottle product', 'microfiber cloth'],
      lifestyle: ['clean home lifestyle', 'tidy kitchen', 'organized living'],
      team: ['cleaning professional portrait', 'maid uniform', 'cleaning team'],
      workspace: ['modern kitchen spotless', 'clean office space', 'fresh bathroom'],
      detail: ['cleaning cloth macro', 'sparkling surface detail', 'soap bubble texture'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
];
