import type { IndustryMeta } from './types';

// ─── Technology, Education, Creative & Travel industries ──────────────────
// 13 industries.

export const TECH_EDU_CREATIVE_INDUSTRIES: IndustryMeta[] = [
  // ── Technology ──
  {
    id: 'saas-startup',
    nameEn: 'SaaS / Startup',
    nameFa: 'استارتاپ نرم‌افزار',
    group: 'Technology',
    groupFa: 'فناوری',
    keywords: ['saas', 'استارتاپ', 'startup', 'software', 'نرم‌افزار', 'app', 'اپلیکیشن', 'platform', 'پلتفرم', 'cloud', 'ابری'],
    subIndustries: [
      { id: 'b2b-saas', nameEn: 'B2B SaaS', nameFa: 'سازمانی', keywords: ['b2b', 'سازمانی', 'enterprise'] },
      { id: 'b2c-saas', nameEn: 'B2C SaaS', nameFa: 'مصرفی', keywords: ['b2c', 'مصرفی', 'consumer'] },
      { id: 'fintech', nameEn: 'Fintech', nameFa: 'فینتک', keywords: ['fintech', 'فینتک', 'payment'] },
      { id: 'martech', nameEn: 'Marketing Tech', nameFa: 'مارکتک', keywords: ['martech', 'بازاریابی'] },
      { id: 'hrtech', nameEn: 'HR Tech', nameFa: 'منابع انسانی', keywords: ['hr', 'منابع انسانی'] },
    ],
    palette: {
      light: { bg: '#FFFFFF', surface: '#F8FAFC', accent: '#7C3AED', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0A0A0A', surface: '#161616', accent: '#8B5CF6', text: '#FAFAFA', muted: '#9CA3AF' },
    },
    suggestedSections: ['hero', 'features', 'how-it-works', 'integrations', 'pricing', 'testimonials', 'case-studies', 'faq', 'cta', 'footer'],
    sampleProducts: ['Starter Plan $19/mo', 'Pro Plan $49/mo', 'Business Plan $99/mo', 'Enterprise Custom', 'Free 14-day Trial', 'Add-on Analytics', 'API Access Tier', 'Priority Support'],
    imageSearchKeywords: {
      hero: ['saas dashboard ui', 'modern startup office', 'tech product banner'],
      product: ['laptop with dashboard', 'mobile app screen', 'software interface'],
      lifestyle: ['person using laptop', 'team working startup', 'modern office lifestyle'],
      team: ['startup team portrait', 'founder working', 'developer at desk'],
      workspace: ['modern startup office', 'coworking space', 'tech office interior'],
      detail: ['laptop screen closeup', 'code editor detail', 'ui component macro'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'mobile-app',
    nameEn: 'Mobile App',
    nameFa: 'اپلیکیشن موبایل',
    group: 'Technology',
    groupFa: 'فناوری',
    keywords: ['mobile app', 'اپلیکیشن', 'app', 'ios', 'android', 'app store', 'اپ استور', 'iphone app', 'android app'],
    subIndustries: [
      { id: 'fitness-app', nameEn: 'Fitness App', nameFa: 'ورزشی', keywords: ['fitness', 'ورزشی', 'workout'] },
      { id: 'finance-app', nameEn: 'Finance App', nameFa: 'مالی', keywords: ['finance', 'مالی', 'banking'] },
      { id: 'social-app', nameEn: 'Social App', nameFa: 'اجتماعی', keywords: ['social', 'اجتماعی'] },
      { id: 'productivity-app', nameEn: 'Productivity', nameFa: 'بهره‌وری', keywords: ['productivity', 'بهره‌وری', 'task'] },
      { id: 'game-app', nameEn: 'Mobile Game', nameFa: 'بازی', keywords: ['game', 'بازی', 'gaming'] },
    ],
    palette: {
      light: { bg: '#FFFFFF', surface: '#F8FAFC', accent: '#EC4899', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0A0A0A', surface: '#161616', accent: '#F472B6', text: '#FAFAFA', muted: '#9CA3AF' },
    },
    suggestedSections: ['hero', 'features', 'screenshots', 'how-it-works', 'testimonials', 'app-store-cta', 'pricing', 'faq', 'footer'],
    sampleProducts: ['Free Download', 'Pro Monthly $9.99', 'Pro Annual $59.99', 'Family Plan $14.99', 'Lifetime License $199', 'Premium Add-on', 'Ad-free Upgrade', 'Cloud Storage 100GB'],
    imageSearchKeywords: {
      hero: ['mobile app on phone', 'app showcase hero', 'iphone with app'],
      product: ['phone screen app', 'app screenshot mockup', 'mobile ui design'],
      lifestyle: ['person using phone', 'mobile app lifestyle', 'smartphone daily use'],
      team: ['app developer portrait', 'mobile designer working', 'startup team'],
      workspace: ['mobile dev workspace', 'design studio app', 'modern tech office'],
      detail: ['phone screen macro', 'app icon closeup', 'mobile ui detail'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'software-company',
    nameEn: 'Software Development Company',
    nameFa: 'شرکت توسعه نرم‌افزار',
    group: 'Technology',
    groupFa: 'فناوری',
    keywords: ['software company', 'شرکت نرم‌افزاری', 'software development', 'توسعه نرم‌افزار', 'dev agency', 'آژانس توسعه', 'programming', 'برنامه‌نویسی'],
    subIndustries: [
      { id: 'web-dev', nameEn: 'Web Development', nameFa: 'وب', keywords: ['web', 'وب', 'website'] },
      { id: 'mobile-dev', nameEn: 'Mobile Development', nameFa: 'موبایل', keywords: ['mobile', 'موبایل'] },
      { id: 'ai-ml', nameEn: 'AI & Machine Learning', nameFa: 'هوش مصنوعی', keywords: ['ai', 'هوش مصنوعی', 'ml', 'machine learning'] },
      { id: 'blockchain', nameEn: 'Blockchain', nameFa: 'بلاکچین', keywords: ['blockchain', 'بلاکچین', 'web3'] },
      { id: 'devops', nameEn: 'DevOps & Cloud', nameFa: 'دواپس', keywords: ['devops', 'cloud', 'ابری'] },
    ],
    palette: {
      light: { bg: '#F8FAFC', surface: '#FFFFFF', accent: '#0EA5E9', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0A0F1A', surface: '#131A2B', accent: '#38BDF8', text: '#F8FAFC', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'services', 'tech-stack', 'portfolio', 'process', 'team', 'case-studies', 'careers', 'contact', 'footer'],
    sampleProducts: ['Web App Development', 'Mobile App Build', 'API Development', 'Cloud Migration', 'AI Integration', 'Code Audit', 'Maintenance Retainer', 'Staff Augmentation'],
    imageSearchKeywords: {
      hero: ['developer coding screen', 'software team office', 'tech workspace banner'],
      product: ['laptop code screen', 'monitor programming', 'code editor dark'],
      lifestyle: ['developer working', 'pair programming', 'tech team meeting'],
      team: ['software engineer portrait', 'developer at desk', 'tech team photo'],
      workspace: ['modern dev office', 'programming workspace', 'tech company office'],
      detail: ['code on screen macro', 'keyboard closeup', 'circuit board detail'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'ai-tech',
    nameEn: 'AI / Tech Platform',
    nameFa: 'پلتفرم هوش مصنوعی',
    group: 'Technology',
    groupFa: 'فناوری',
    keywords: ['ai', 'هوش مصنوعی', 'artificial intelligence', 'machine learning', 'یادگیری ماشین', 'llm', 'chatbot', 'چت‌بات', 'ai platform'],
    subIndustries: [
      { id: 'llm-platform', nameEn: 'LLM Platform', nameFa: 'مدل زبانی', keywords: ['llm', 'مدل زبانی', 'gpt', 'language model'] },
      { id: 'vision-ai', nameEn: 'Computer Vision', nameFa: 'بینایی ماشین', keywords: ['vision', 'بینایی', 'image recognition'] },
      { id: 'automation-ai', nameEn: 'AI Automation', nameFa: 'اتوماسیون', keywords: ['automation', 'اتوماسیون', 'workflow'] },
      { id: 'data-ai', nameEn: 'Data & Analytics', nameFa: 'تحلیل داده', keywords: ['data', 'داده', 'analytics'] },
    ],
    palette: {
      light: { bg: '#FFFFFF', surface: '#F5F3FF', accent: '#7C3AED', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0A0612', surface: '#13101F', accent: '#A78BFA', text: '#F5F3FF', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'capabilities', 'use-cases', 'models', 'pricing', 'documentation', 'research', 'api-reference', 'footer'],
    sampleProducts: ['API Free Tier', 'Pro API $99/mo', 'Enterprise License', 'Custom Model Training', 'Fine-tuning Service', 'Data Labeling', 'GPU Compute Hour', 'Consulting Package'],
    imageSearchKeywords: {
      hero: ['ai technology banner', 'neural network visualization', 'futuristic ai interface'],
      product: ['ai dashboard ui', 'data visualization screen', 'ml model interface'],
      lifestyle: ['researcher working ai', 'data scientist lifestyle', 'modern tech workspace'],
      team: ['ai researcher portrait', 'data scientist team', 'ml engineer'],
      workspace: ['modern ai lab', 'data center interior', 'tech research office'],
      detail: ['circuit ai macro', 'data flow visualization', 'gpu chip closeup'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  // ── Education ──
  {
    id: 'online-course',
    nameEn: 'Online Course / E-learning',
    nameFa: 'دوره آنلاین',
    group: 'Education',
    groupFa: 'آموزش',
    keywords: ['online course', 'دوره آنلاین', 'e-learning', 'آموزش آنلاین', 'course', 'دوره', 'tutorial', 'آموزش', 'masterclass', 'اکادمی'],
    subIndustries: [
      { id: 'tech-courses', nameEn: 'Tech Courses', nameFa: 'فناوری', keywords: ['tech', 'فناوری', 'programming', 'برنامه‌نویسی'] },
      { id: 'business-courses', nameEn: 'Business', nameFa: 'کسب‌وکار', keywords: ['business', 'کسب‌وکار', 'marketing'] },
      { id: 'creative-courses', nameEn: 'Creative', nameFa: 'خلاقیت', keywords: ['creative', 'خلاقیت', 'design', 'طراحی'] },
      { id: 'language-courses', nameEn: 'Languages', nameFa: 'زبان', keywords: ['language', 'زبان', 'english'] },
      { id: 'kids-courses', nameEn: "Kids' Learning", nameFa: 'کودکان', keywords: ['kids', 'کودک', 'children'] },
    ],
    palette: {
      light: { bg: '#FFFFFF', surface: '#F0F9FF', accent: '#0EA5E9', text: '#0C4A6E', muted: '#64748B' },
      dark: { bg: '#0A0F1A', surface: '#131A2B', accent: '#38BDF8', text: '#F0F9FF', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'featured-courses', 'categories', 'instructors', 'learning-path', 'testimonials', 'pricing', 'free-trial', 'footer'],
    sampleProducts: ['Complete Web Dev Bootcamp', 'Data Science Pro Track', 'UI/UX Design Masterclass', 'Digital Marketing Course', 'English Fluency Program', 'Python for Beginners', 'Photography Essentials', 'Business Strategy 101'],
    imageSearchKeywords: {
      hero: ['online learning banner', 'person studying laptop', 'education platform'],
      product: ['course thumbnail', 'video lesson screen', 'certificate template'],
      lifestyle: ['student learning online', 'study lifestyle home', 'person on laptop course'],
      team: ['instructor portrait', 'teacher professional', 'course creator'],
      workspace: ['modern study setup', 'home office learning', 'study desk minimal'],
      detail: ['laptop screen course', 'notebook study detail', 'pencil notes macro'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'school',
    nameEn: 'School / Educational Institution',
    nameFa: 'مدرسه و آموزشگاه',
    group: 'Education',
    groupFa: 'آموزش',
    keywords: ['school', 'مدرسه', 'academy', 'آکادمی', 'institute', 'آموزشگاه', 'education', 'آموزش', 'university', 'دانشگاه', 'college', 'کالج'],
    subIndustries: [
      { id: 'preschool', nameEn: 'Preschool', nameFa: 'پیش‌دبستانی', keywords: ['preschool', 'پیش‌دبستانی', 'kindergarten'] },
      { id: 'elementary', nameEn: 'Elementary', nameFa: 'ابتدایی', keywords: ['elementary', 'ابتدایی', 'primary'] },
      { id: 'high-school', nameEn: 'High School', nameFa: 'متوسطه', keywords: ['high', 'متوسطه', 'secondary'] },
      { id: 'university', nameEn: 'University', nameFa: 'دانشگاه', keywords: ['university', 'دانشگاه'] },
      { id: ' vocational', nameEn: 'Vocational', nameFa: 'حرفه‌ای', keywords: ['vocational', 'حرفه‌ای', 'technical'] },
    ],
    palette: {
      light: { bg: '#F0F9FF', surface: '#FFFFFF', accent: '#1D4ED8', text: '#0C4A6E', muted: '#64748B' },
      dark: { bg: '#0C1A2A', surface: '#13293F', accent: '#3B82F6', text: '#F0F9FF', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'about-school', 'programs', 'admissions', 'faculty', 'campus-life', 'news-events', 'testimonials', 'contact', 'footer'],
    sampleProducts: ['Fall Enrollment', 'Summer Program', 'After-school Activities', 'Scholarship Application', 'Online Classes', 'Tutoring Sessions', 'Sports Program', 'Music Lessons'],
    imageSearchKeywords: {
      hero: ['school building modern', 'students studying', 'classroom banner'],
      product: ['textbook product', 'school supplies', 'graduation cap'],
      lifestyle: ['students learning classroom', 'school lifestyle', 'kids studying'],
      team: ['teacher portrait professional', 'professor educator', 'school staff'],
      workspace: ['modern classroom interior', 'school library', 'university lecture hall'],
      detail: ['chalkboard closeup', 'books stack detail', 'pencil writing macro'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'tutoring',
    nameEn: 'Tutoring & Coaching',
    nameFa: 'تدریس و مربی‌گری',
    group: 'Education',
    groupFa: 'آموزش',
    keywords: ['tutoring', 'تدریس', 'tutor', 'مدرس', 'coaching', 'مربی‌گری', 'private tutor', 'مدرس خصوصی', 'mentoring', 'منتورینگ'],
    subIndustries: [
      { id: 'academic-tutoring', nameEn: 'Academic Subjects', nameFa: 'درسی', keywords: ['academic', 'درسی', 'subject'] },
      { id: 'test-prep', nameEn: 'Test Prep', nameFa: 'آزمون', keywords: ['test', 'آزمون', 'sat', 'gre'] },
      { id: 'language-tutoring', nameEn: 'Languages', nameFa: 'زبان', keywords: ['language', 'زبان'] },
      { id: 'music-tutoring', nameEn: 'Music Lessons', nameFa: 'موسیقی', keywords: ['music', 'موسیقی', 'piano', 'گیتار'] },
      { id: 'life-coaching', nameEn: 'Life Coaching', nameFa: 'مربی زندگی', keywords: ['life', 'coaching', 'مربی'] },
    ],
    palette: {
      light: { bg: '#F0FDF4', surface: '#FFFFFF', accent: '#15803D', text: '#14532D', muted: '#6B7280' },
      dark: { bg: '#0A1F12', surface: '#102818', accent: '#4ADE80', text: '#F0FDF4', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'subjects', 'tutors', 'pricing', 'booking', 'free-trial', 'testimonials', 'resources', 'footer'],
    sampleProducts: ['1-on-1 Math Tutoring', 'SAT Prep Course', 'English Conversation 10-pack', 'Piano Lessons Weekly', 'Chemistry Help', 'Coding Tutoring', 'Life Coaching Session', 'Group Study Class'],
    imageSearchKeywords: {
      hero: ['tutor with student', 'online tutoring banner', 'study session'],
      product: ['textbook product', 'notebook and pen', 'study planner'],
      lifestyle: ['student studying focused', 'online learning lifestyle', 'tutoring session'],
      team: ['tutor portrait friendly', 'teacher professional', 'coach mentor'],
      workspace: ['home study setup', 'online tutoring screen', 'study desk minimal'],
      detail: ['notebook writing detail', 'pencil closeup', 'study notes macro'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  // ── Creative ──
  {
    id: 'design-studio',
    nameEn: 'Design Studio',
    nameFa: 'استودیو طراحی',
    group: 'Creative',
    groupFa: 'خلاقیت',
    keywords: ['design studio', 'استودیو طراحی', 'graphic design', 'طراحی گرافیک', 'branding agency', 'آژانس برندینگ', 'ui ux', 'یوآی یوایکس', 'creative agency'],
    subIndustries: [
      { id: 'branding', nameEn: 'Branding', nameFa: 'برندینگ', keywords: ['branding', 'برندینگ', 'brand'] },
      { id: 'ui-ux', nameEn: 'UI/UX Design', nameFa: 'یوآی یوایکس', keywords: ['ui', 'ux', 'interface'] },
      { id: 'graphic', nameEn: 'Graphic Design', nameFa: 'گرافیک', keywords: ['graphic', 'گرافیک'] },
      { id: 'motion', nameEn: 'Motion Design', nameFa: 'موشن', keywords: ['motion', 'موشن', 'animation'] },
      { id: 'packaging', nameEn: 'Packaging', nameFa: 'بسته‌بندی', keywords: ['packaging', 'بسته‌بندی'] },
    ],
    palette: {
      light: { bg: '#FAFAF9', surface: '#FFFFFF', accent: '#EC4899', text: '#0F172A', muted: '#78716C' },
      dark: { bg: '#0A0A0A', surface: '#171717', accent: '#F472B6', text: '#FAFAFA', muted: '#9CA3AF' },
    },
    suggestedSections: ['hero', 'works-portfolio', 'services', 'process', 'team', 'case-studies', 'awards', 'contact', 'footer'],
    sampleProducts: ['Brand Identity Package', 'Logo Design Premium', 'Website UI/UX Design', 'Packaging Design', 'Motion Graphics Reel', 'Design System Build', 'Brand Strategy Workshop', 'Creative Direction'],
    imageSearchKeywords: {
      hero: ['design studio creative', 'designer workspace banner', 'creative agency hero'],
      product: ['brand book product', 'logo design mockup', 'design portfolio'],
      lifestyle: ['designer working creative', 'studio lifestyle', 'creative process'],
      team: ['designer portrait creative', 'design team studio', 'creative professional'],
      workspace: ['design studio interior', 'creative workspace', 'agency office modern'],
      detail: ['color swatches closeup', 'design tools macro', 'sketch detail'],
    },
    fontPairing: 'Playfair Display + Inter',
  },
  {
    id: 'art-gallery',
    nameEn: 'Art Gallery',
    nameFa: 'گالری هنر',
    group: 'Creative',
    groupFa: 'خلاقیت',
    keywords: ['art gallery', 'گالری هنر', 'gallery', 'گالری', 'art exhibition', 'نمایشگاه هنر', 'fine art', 'هنرهای زیبا', 'contemporary art', 'هنر معاصر'],
    subIndustries: [
      { id: 'contemporary', nameEn: 'Contemporary Art', nameFa: 'معاصر', keywords: ['contemporary', 'معاصر', 'modern art'] },
      { id: 'classical', nameEn: 'Classical Art', nameFa: 'کلاسیک', keywords: ['classical', 'کلاسیک', 'traditional'] },
      { id: 'photography-art', nameEn: 'Photography Art', nameFa: 'عکاسی هنری', keywords: ['photography', 'عکاسی'] },
      { id: 'sculpture', nameEn: 'Sculpture', nameFa: 'مجسمه', keywords: ['sculpture', 'مجسمه'] },
      { id: 'digital-art', nameEn: 'Digital Art', nameFa: 'دیجیتال', keywords: ['digital', 'دیجیتال', 'nft'] },
    ],
    palette: {
      light: { bg: '#FAFAF9', surface: '#FFFFFF', accent: '#0F172A', text: '#0F172A', muted: '#78716C' },
      dark: { bg: '#0A0A0A', surface: '#171717', accent: '#FAFAF9', text: '#FAFAF9', muted: '#9CA3AF' },
    },
    suggestedSections: ['hero', 'current-exhibition', 'artists', 'collection', 'upcoming-shows', 'about-gallery', 'press', 'visit', 'footer'],
    sampleProducts: ['Original Oil Painting', 'Limited Edition Print', 'Sculpture Bronze', 'Photography Print', 'Art Commission', 'Gallery Membership', 'Private Viewing', 'Art Consultation'],
    imageSearchKeywords: {
      hero: ['art gallery interior', 'contemporary art exhibition', 'gallery white wall'],
      product: ['artwork on wall', 'painting closeup', 'sculpture display'],
      lifestyle: ['people in gallery', 'art collector viewing', 'gallery opening event'],
      team: ['artist portrait', 'curator professional', 'gallery owner'],
      workspace: ['gallery space minimal', 'art studio creative', 'exhibition hall'],
      detail: ['painting brush stroke', 'canvas texture macro', 'frame detail'],
    },
    fontPairing: 'Cormorant Garamond + Inter',
  },
  {
    id: 'music',
    nameEn: 'Music / Band / Musician',
    nameFa: 'موسیقی و گروه',
    group: 'Creative',
    groupFa: 'خلاقیت',
    keywords: ['music', 'موسیقی', 'band', 'گروه موسیقی', 'musician', 'موسیقیدان', 'singer', 'خواننده', 'album', 'آلبوم', 'record label', 'لیبل موسیقی'],
    subIndustries: [
      { id: 'solo-musician', nameEn: 'Solo Musician', nameFa: 'تک‌نواز', keywords: ['solo', 'تک', 'musician'] },
      { id: 'band', nameEn: 'Band', nameFa: 'گروه', keywords: ['band', 'گروه'] },
      { id: 'dj', nameEn: 'DJ', nameFa: 'دی‌جی', keywords: ['dj', 'دی‌جی'] },
      { id: 'producer', nameEn: 'Music Producer', nameFa: 'تولیدکننده', keywords: ['producer', 'تولید', 'beat'] },
      { id: 'label', nameEn: 'Record Label', nameFa: 'لیبل', keywords: ['label', 'لیبل', 'record'] },
    ],
    palette: {
      light: { bg: '#FFFFFF', surface: '#F8FAFC', accent: '#DC2626', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0A0A0A', surface: '#171717', accent: '#F87171', text: '#FAFAFA', muted: '#9CA3AF' },
    },
    suggestedSections: ['hero', 'latest-release', 'music-videos', 'tour-dates', 'merch', 'about-artist', 'gallery', 'newsletter', 'footer'],
    sampleProducts: ['New Album Digital', 'Vinyl LP Limited', 'Concert Ticket VIP', 'Merch T-Shirt', 'Music Video Stream', 'Patreon Membership', 'Exclusive Acoustic EP', 'Signed Poster'],
    imageSearchKeywords: {
      hero: ['musician performing stage', 'concert lights banner', 'studio recording'],
      product: ['vinyl record product', 'album cover art', 'guitar isolated'],
      lifestyle: ['fan at concert', 'music lifestyle', 'studio session'],
      team: ['musician portrait', 'band photo', 'producer at work'],
      workspace: ['recording studio', 'music studio interior', 'concert stage'],
      detail: ['guitar strings macro', 'vinyl groove closeup', 'microphone detail'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  // ── Travel & Hospitality ──
  {
    id: 'hotel',
    nameEn: 'Hotel & Hospitality',
    nameFa: 'هتل و اقامتگاه',
    group: 'Travel & Hospitality',
    groupFa: 'گردشگری و اقامت',
    keywords: ['hotel', 'هتل', 'resort', 'اقامتگاه', 'boutique hotel', 'هتل بوتیک', 'lodging', 'اقامت', 'accommodation', 'accommodation'],
    subIndustries: [
      { id: 'luxury-hotel', nameEn: 'Luxury Hotel', nameFa: 'لوکس', keywords: ['luxury', 'لوکس', '5-star'] },
      { id: 'boutique-hotel', nameEn: 'Boutique Hotel', nameFa: 'بوتیک', keywords: ['boutique', 'بوتیک'] },
      { id: 'resort', nameEn: 'Resort', nameFa: 'اقامتگاه', keywords: ['resort', 'اقامتگاه'] },
      { id: 'business-hotel', nameEn: 'Business Hotel', nameFa: 'تجاری', keywords: ['business', 'تجاری'] },
      { id: 'eco-lodge', nameEn: 'Eco Lodge', nameFa: 'بوم‌گردی', keywords: ['eco', 'بوم', 'sustainable'] },
    ],
    palette: {
      light: { bg: '#FFFBEB', surface: '#FFFFFF', accent: '#92400E', text: '#451A03', muted: '#78716C' },
      dark: { bg: '#1C1410', surface: '#2A2018', accent: '#FBBF24', text: '#FFFBEB', muted: '#A8A29E' },
    },
    suggestedSections: ['hero', 'rooms-suites', 'amenities', 'dining', 'spa-wellness', 'gallery', 'special-offers', 'booking', 'footer'],
    sampleProducts: ['Standard King Room', 'Deluxe Suite', 'Presidential Suite', 'Family Room 2BR', 'Spa Package', 'Romantic Getaway', 'Business Travel Package', 'Extended Stay Weekly'],
    imageSearchKeywords: {
      hero: ['luxury hotel lobby', 'beautiful hotel exterior', 'resort pool banner'],
      product: ['hotel room interior', 'bed in luxury room', 'bathroom suite'],
      lifestyle: ['guest enjoying hotel', 'vacation lifestyle pool', 'couple romantic hotel'],
      team: ['hotel staff concierge', 'hospitality professional', 'hotel team uniform'],
      workspace: ['hotel lobby interior', 'luxury hotel restaurant', 'spa wellness center'],
      detail: ['bed linen closeup', 'bathroom detail luxury', 'spa candle texture'],
    },
    fontPairing: 'Playfair Display + Inter',
  },
  {
    id: 'travel-agency',
    nameEn: 'Travel Agency',
    nameFa: 'آژانس مسافرتی',
    group: 'Travel & Hospitality',
    groupFa: 'گردشگری و اقامت',
    keywords: ['travel agency', 'آژانس مسافرتی', 'travel', 'مسافرت', 'tour', 'تور', 'vacation', 'تعطیلات', 'trip', 'سفر', 'tour operator'],
    subIndustries: [
      { id: 'international-tours', nameEn: 'International Tours', nameFa: 'بین‌المللی', keywords: ['international', 'بین‌المللی'] },
      { id: 'domestic-tours', nameEn: 'Domestic Tours', nameFa: 'داخلی', keywords: ['domestic', 'داخلی'] },
      { id: 'adventure', nameEn: 'Adventure Travel', nameFa: 'ماجراجویانه', keywords: ['adventure', 'ماجراجویی'] },
      { id: 'luxury-travel', nameEn: 'Luxury Travel', nameFa: 'لوکس', keywords: ['luxury', 'لوکس'] },
      { id: 'pilgrimage', nameEn: 'Pilgrimage Tours', nameFa: 'زیارتی', keywords: ['pilgrimage', 'زیارتی', 'hajj', 'omrah'] },
    ],
    palette: {
      light: { bg: '#F0F9FF', surface: '#FFFFFF', accent: '#0EA5E9', text: '#0C4A6E', muted: '#64748B' },
      dark: { bg: '#0C1A2A', surface: '#13293F', accent: '#38BDF8', text: '#F0F9FF', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'featured-tours', 'destinations', 'tour-categories', 'about-us', 'testimonials', 'travel-blog', 'contact', 'footer'],
    sampleProducts: ['7-Day Bali Tour', '10-Day Europe Highlights', 'Turkey Cappadocia Package', 'Dubai Luxury Tour', 'Iran Cultural Tour', 'Japan Sakura Trip', 'Maldives Honeymoon', 'Umrah Package 10-day'],
    imageSearchKeywords: {
      hero: ['travel banner landscape', 'beautiful destination', 'adventure travel'],
      product: ['tourist destination photo', 'landmark travel', 'beach paradise'],
      lifestyle: ['tourists enjoying vacation', 'travel lifestyle', 'happy travelers'],
      team: ['tour guide portrait', 'travel agent professional', 'travel consultant'],
      workspace: ['travel agency office', 'modern booking office', 'tour operator workspace'],
      detail: ['passport map closeup', 'airplane window view', 'souvenir detail'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
  {
    id: 'restaurant-supply',
    nameEn: 'Restaurant Supply / Hospitality B2B',
    nameFa: 'تأمین رستوران',
    group: 'Travel & Hospitality',
    groupFa: 'گردشگری و اقامت',
    keywords: ['restaurant supply', 'تأمین رستوران', 'hospitality supplies', 'تجهیزات هتل', 'kitchen equipment', 'تجهیزات آشپزخانه', 'hotel supply'],
    subIndustries: [
      { id: 'kitchen-equip', nameEn: 'Kitchen Equipment', nameFa: 'تجهیزات آشپزخانه', keywords: ['kitchen', 'آشپزخانه', 'equipment'] },
      { id: 'tableware', nameEn: 'Tableware', nameFa: 'سرویس غذا', keywords: ['tableware', 'سرویس', 'dinnerware'] },
      { id: 'furniture', nameEn: 'Restaurant Furniture', nameFa: 'مبلمان رستوران', keywords: ['furniture', 'مبلمان', 'chair'] },
      { id: 'cleaning-supply', nameEn: 'Cleaning Supplies', nameFa: 'تأمین نظافتی', keywords: ['cleaning', 'نظافتی'] },
    ],
    palette: {
      light: { bg: '#F8FAFC', surface: '#FFFFFF', accent: '#475569', text: '#0F172A', muted: '#64748B' },
      dark: { bg: '#0F172A', surface: '#1E293B', accent: '#94A3B8', text: '#F8FAFC', muted: '#94A3B8' },
    },
    suggestedSections: ['hero', 'categories', 'featured-products', 'brands', 'special-offers', 'bulk-pricing', 'about-us', 'contact', 'footer'],
    sampleProducts: ['Commercial Range 6-burner', 'Stainless Steel Prep Table', 'Professional Blender', 'Dinnerware Set 24pc', 'Wine Glasses 12pc', 'Bar Stool Commercial', 'Dishwasher Industrial', 'Refrigeration Unit'],
    imageSearchKeywords: {
      hero: ['restaurant kitchen equipment', 'professional kitchen banner', 'hospitality supply'],
      product: ['kitchen equipment product', 'cookware isolated', 'dinnerware set'],
      lifestyle: ['chef using equipment', 'busy restaurant kitchen', 'professional cooking'],
      team: ['chef portrait professional', 'kitchen staff team', 'equipment specialist'],
      workspace: ['commercial kitchen interior', 'restaurant supply warehouse', 'professional kitchen'],
      detail: ['stainless steel texture', 'knife blade closeup', 'cookware detail'],
    },
    fontPairing: 'Inter + JetBrains Mono',
  },
];
